### PR TITLE
companion for try-runtime revamp

### PR DESCRIPTION
**Pull request by kianenigma**
https://github.com/paritytech/substrate/pull/12537

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]

**Review by niklasad1 — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2135533

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2153111

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2159914

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2160077

**Review by bkchr — APPROVED** [review]

**Review by ordian — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Comment by kianenigma** [comment]
bot rebase

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
