### PR TITLE
Set CurrentCodeHash before running some dispatchable benchmarks

### LINKED ISSUE #4616: Paras benchmarks log about inconsistencies
Running paras benchmarks produces logs like the following:

- Pallet paras storage is inconsistent, prior code not found <wasm:stripped>
- Missing prior code hash for para

Potentially might indicate that the benchmarks are off.

git-blame leads to @KiChjang

### PR DESCRIPTION
**Pull request by KiChjang**
Aims to fix #4616.

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Review by emostov — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
