### PR TITLE
ensure test accounts have balances

### LINKED ISSUE #238: Starting a Dev chain does not fund account Alice
Hey so I am having a little issue running a local Polkadot dev chain. The chain is running and I am connecting but the balance of Alice is 0.

node
```
Running target/debug/polkadot --dev --ws-port 9999 --rpc-port 9998 --ws-external --alice
Parity Polkadot
version 0.4.0-75e827c0-x86_64-linux-gnu

```

JS 
```
const keyring = new Keyring({ type: "sr25519" });

const alice = keyring.addFromUri('//Alice');
const previous = await api.query.balances.freeBalance(alice.publicKey());

```

### PR DESCRIPTION
**Pull request by xlc**
Fixes #238

### CODE REVIEW

**Comment by ltfschoen** [comment]
I tried testing your branch.

First cloned it and ran it

```
git clone https://github.com/xlc/polkadot
cd polkadot
git fetch origin fix-dev-genesis:fix-dev-genesis
git checkout fix-dev-genesis
cargo clean
./scripts/init.sh
./scripts/build.sh
cargo install --path ./ --force
target/release/polkadot --dev --alice
```

Then went to http://localhost:3000/#/settings and connected to localhost:9944

Then went to http://localhost:3000/#/js and ran:

```
const ALICE = '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY';
let previous = await api.query.balances.freeBalance(ALICE);
console.log('ALICE has a balance of ' + previous);

const user = keyring.addFromUri('//Bob//stash');
previous = await api.query.balances.freeBalance(user.publicKey());
console.log('Bob Stash has a balance of ' + previous);
```

But output displayed:

```
ALICE has a balance of 0
Bob Stash has a balance of 0
```

But when i go to http://localhost:3000/#/accounts, it lists ALICE_STASH with a large balance

If I run it with `target/release/polkadot --dev --key //Bob//stash --name BobTest`
Then when i go to http://localhost:3000/#/accounts, it still lists ALICE_STASH with a large balance, but it does'nt list BobTest at all
And when i try running the same JS code snippet it returns 0 for both ALICE and Bob Stash

**Comment by ltfschoen** [comment]
as an alternative, i just created development accounts that are preloaded with a large balance by cloning this branch of @jacogr 's. https://github.com/polkadot-js/apps/pull/1078, but i still get 0 balance returned when i run those JS code snippets

**Comment by xlc** [comment]
@ltfschoen I just tested it and it works as expected.

Please make sure you have rebuild Wasm file and purge-chain.

**Comment by ltfschoen** [comment]
> @ltfschoen I just tested it and it works as expected.
> 
> Please make sure you have rebuild Wasm file and purge chain.
> 
> `polkadot purge-chain --dev` or `cargo run -- purge-chain --dev` to purge chain

thanks, yes it works :1st_place_medal:

**Comment by rphmeier** [comment]
Thanks!

**Pull request merged**
