### PR TITLE
companion PR for https://github.com/paritytech/substrate/pull/13373

### PR DESCRIPTION
**Pull request by hirschenberger**
companion PR for https://github.com/paritytech/substrate/pull/13373

cumulus companion: https://github.com/paritytech/cumulus/pull/2547

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2670497

**Review by bkchr — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2798773

**Review by ggwpez — APPROVED** [review]

**Comment by ggwpez** [comment]
bot rebase

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
