### PR TITLE
parachain origin to frame v2

### PR DESCRIPTION
**Pull request by ferrell-code**
relates: #2882 

Following the upgrade guidelines here: https://crates.parity.io/frame_support/attr.pallet.html#upgrade-guidelines.

# :warning: Breaking Change :warning: 
From https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines

 >storages now use PalletInfo for module_prefix instead of the one given to decl_storage: Thus any use of this pallet in construct_runtime! should be careful to update name in order not to break storage or to upgrade storage (moreover for instantiable pallet). If pallet is published, make sure to warn about this breaking change.

The was no `decl_storage` so no migration needed

### CODE REVIEW

**Review by KiChjang — APPROVED** [review]
If it compiles, it works.

**Comment by shawntabrizi** [comment]
@ferrell-code when this PR is complete, can you please include your polkadot or kusama address so I can open a treasury tip?

Thanks!

**Comment by ferrell-code** [comment]
15zKd25HoSDPHCn1HjuuHTioXLT7PA2pZQ8gYjFsHW4r96qS

Or

DSSYqgJqdE6HmFAXpiq3y6eZ5FYZ3ZxmX3joRBkh345mxEN 

thanks :) 

If you have the time this week I think  [#8733](https://github.com/paritytech/substrate/pull/8733) got buried in the pile of PRs

**Review by thiolliere — APPROVED** [review]

**Comment by thiolliere** [comment]
there is no breaking change, as the pallet as no storage. (it didn't use decl_storage)

**Comment by thiolliere** [comment]
bot merge

**Comment by thiolliere** [comment]
> Edit: I'm not sure why CI is hanging I believe it compiles fully

FYI, CI check that some labels are set on the PR, nothing on your side

**Pull request merged**
