### PR TITLE
Add a few staking params to fast-runtime build

### PR DESCRIPTION
**Pull request by moh-eulith**
I left the default fast build values as is, in case someone is depending on those.

### CODE REVIEW

**Comment by moh-eulith** [comment]
Review please? The spellcheck failure appears to be something irrelevant.

**Review by gilescope — APPROVED** [review]
Good idea. No one wants to wait 28 days while testing.

**Comment by gilescope** [comment]
The spellcheck error was that the word was not in https://github.com/paritytech/polkadot/blob/master/scripts/ci/gitlab/lingua.dic but it is now so if you merge master then that build issue should go away.

**Review by bkchr — APPROVED** [review]

**Comment by ordian** [comment]
bot merge

**Pull request merged**
