### PR TITLE
companion to substrate 11411

### PR DESCRIPTION
**Pull request by kianenigma**
https://github.com/paritytech/substrate/pull/11411

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]
Did you try it with the `try-runtime`?

**Review by bkchr — APPROVED** [review]

**Comment by kianenigma** [comment]
/cmd queue -v RUST_LOG=debug -c try-runtime $ --chain=westend-dev --execution=Wasm on-runtime-upgrade live --uri wss://westend-try-runtime-node.parity-chains.parity.io

**Comment by joao-paulo-parity** [comment]
/cmd queue -v RUST_LOG=debug -c try-runtime $ --chain=westend-dev --execution=Wasm on-runtime-upgrade live --uri wss://westend-try-runtime-node.parity-chains.parity.io:443

**Comment by joao-paulo-parity** [comment]
@kianenigma Seems like `RUST_LOG=debug` from https://github.com/paritytech/polkadot/pull/5524#issuecomment-1128595450 was too excessive

https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/1571025#L19

> Job's log exceeded limit of 33554432 bytes.
> Job execution will continue but no more output will be collected.

**Review by shawntabrizi — APPROVED** [review]

**Review by sergejparity — APPROVED** [review]

**Comment by kianenigma** [comment]
bot merge

**Pull request merged**
