### PR TITLE
runtime: skip insufficiently backed candidates instead of bailing

### PR DESCRIPTION
**Pull request by slumber**
Part of #4576

### CODE REVIEW

**Comment by rphmeier** [comment]
I don't like this change.

Previously, it was always the case that you could scrape the block bodies and know that parachain candidates were actually backed within a block.

**Comment by Lldenaurois** [comment]
> I understand it, is about having good runtime-level filtering at the `create_inherent` phase, not during block execution itself. Even that, IMO, should be up for discussion because node-side logic will always be faster than runtime-side, although runtime-side is without a doubt easier.

I am also of the opinion that we should always bail if block execution contains anything that is not sufficient to act upon, i.e. insufficiently backed candidate, unsigned bitfields, disputes with no vote for/against etc

**Comment by eskimor** [comment]
I am not really arguing against that. I did suggest that change because:

1. This way we are not introducing two code paths, but keep the one we have right now.
2. It should not really make much of a difference - assuming the block producer is honest, the filtering will never happen. If it is dishonest the candidate will be dropped, instead of the whole inherent - which should be fine as well, as everything else gets checked too. Although it will increase potential attack vectors in case of subtle bugs.

Not saying I particularly like the solution, but given the current code structure it seemed like the least intrusive path. In general we should revisit the create_inherent/block import duality - @drahnr  is already doing some writeup on that - really looking forward to it. Given our discussions we had with @jakoblell, I think the two code paths are unavoidable, but I think we need a more structured approach for making sure they are consistent. E.g. have something like having a `check_....` function for each `create_....` function, where each of those pairs can be reviewed & tested individually with a strong guarantee that if each of those pairs is correct, the whole stack will be correct.

**Review by drahnr — CHANGES_REQUESTED** [review]
I don't think we should be more lenient on-chain.

**Comment by rphmeier** [comment]
>  In general we should revisit the create_inherent/block import duality - @drahnr is already doing some writeup on that - really looking forward to it.

Me too. Refactoring is needed, clearly, and I think a 'check' / 'operate' duality is very reasonable. 

> We will only provide the very next candidate of any prospective chain to create_inherent, which will accept it when sufficiently backed, if not it will be accepted (likely) at the next block. 

Yes

> Relying purely on the node side for e.g. signature checking at block production

I think our ending point should be to allow the node-side to specify in the `InherentData` which checks it would like the runtime to do. As you mention, working on the node-side will simply be more efficient and but working in the runtime is more obviously correct. So we might start with node-side code that does very little by way of checking, but end with node-side code that does every possible check and the runtime only needs to do pass-through.

> I am also of the opinion that we should always bail if block execution contains anything that is not sufficient to act upon, i.e. insufficiently backed candidate, unsigned bitfields, disputes with no vote for/against etc

Anyway, I'm not sure what this has to do with making the on-chain logic more lenient but it seems we have a rough consensus that it's a bad idea. That is, it seems that myself, @drahnr, @Lldenaurois are against it and @eskimor, you seem to be neutral? If I understand you correctly, it seems that you've only suggested this change as a route to refactoring and you don't consider it an end-goal unto itself. Please correct me if that is an inaccurate portrayal. If that sounds right, then I move to close this PR.

**Comment by eskimor** [comment]
Neutral ... I guess, less opposed. I did not like it, but it seemed ok until we have that refactor. Anyhow, this is not urgent as we are well aware that node side checks and runtime checks have to stay in sync for the time being, so I think we can manage to not break chains for a while, even if we have to adjust the backing threshold again.

**Comment by rphmeier** [comment]
FWIW #4790 might help.

**Pull request closed without merging**
