### PR TITLE
Added Dwellir bootnodes for Kusama and Polkadot

### PR DESCRIPTION
**Pull request by Maharacha**

### CODE REVIEW

**Comment by Ank4n** [comment]
@bkchr This PR has been here for a long time. Can you have a look?

**Review by bkchr — APPROVED** [review]

**Comment by ggwpez** [comment]
How can I check that these work correctly?

**Review by wpank — APPROVED** [review]

**Review by shawntabrizi — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
Thanks for helping the network!

**Comment by ggwpez** [comment]
bot merge

**Comment by sandreim** [comment]
Got this during Kusama burnin of v0.9.28 release:
```
tokio-runtime-worker sc_network::service: 💔 The bootnode you want to connect to at /dns/kusama-bootnode.dwellir.com/tcp/30333/ws/p2p/12D3KooWFj2ndawdYyk2spc42Y2arYwb2TUoHLHFAsKuHRzWXwoJ provided a different peer ID 12D3KooWBG546egfHMgY3Dm5GXcgRMMei6Ce3NmRsQHMgy5KV7Ce than the one you expect 12D3KooWFj2ndawdYyk2spc42Y2arYwb2TUoHLHFAsKuHRzWXwoJ.
```

**Comment by PierreBesson** [comment]
We can check that the bootnode is working with:
```
polkadot --chain kusama --reserved-nodes "/dns/kusama-bootnode.dwellir.com/tcp/30333/ws/p2p/12D3KooWFj2ndawdYyk2spc42Y2arYwb2TUoHLHFAsKuHRzWXwoJ" --reserved-only
```
As of "Fri Aug 19 05:36:33 PM CEST 2022", it is DOWN for me.

**Comment by Ank4n** [comment]
I think we had a system upgrade and our keys got overwritten by our CI. I am fixing it now but can you check if it works now for you.

**Comment by Ank4n** [comment]
I have tested it and should be working now. Apologies for the trouble.

**Comment by bkchr** [comment]
Ty for the fast response @Ank4n 👍

**Pull request merged**
