### PR TITLE
Add stake.plus bootnodes for westend, kusama and polkadot

### PR DESCRIPTION
**Pull request by senseless**
Add stake.plus bootnodes to westend, kusama and polkadot chain-spec files.

### CODE REVIEW

**Comment by bkchr** [comment]
@senseless do you have websocket with a certificate in front of it enabled for light clients? https://forum.polkadot.network/t/community-bootnodes-and-snapshot-providers/630/3?u=bkchr

**Comment by senseless** [comment]
@bkchr I do not, thank you for bringing this to my attention. I'll do the necessary work and request a new merge once I've deployed support.

**Comment by bkchr** [comment]
@senseless no, please no load balancers. These are not required.

**Comment by senseless** [comment]
> 

If you have a moment, can you explain why no load balancers? We would prefer to run redundant endpoints in case of a failure it stays online. I thought we might be able to utilize our RPC endpoints as boot nodes. It would be ideal for us to use the same rpc cluster as our boot node cluster.

**Comment by bkchr** [comment]
> If you have a moment, can you explain why no load balancers?

If your bootnode is down for a moment, that isn't a problem. There are other bootnodes as well. The point of a bootnode is anyway to provide some known connection point for a new node. It connects to a bootnode and gets a list of known peers and will start connecting to those. The new node will then eventually disconnect from the bootnode anyway.

**Comment by senseless** [comment]
> > If you have a moment, can you explain why no load balancers?
> 
> If your bootnode is down for a moment, that isn't a problem. There are other bootnodes as well. The point of a bootnode is anyway to provide some known connection point for a new node. It connects to a bootnode and gets a list of known peers and will start connecting to those. The new node will then eventually disconnect from the bootnode anyway.

Is a boot node required to contain a full archive of the blockchain? It seems like what we're really after in a bootnode is state not history. Is that correct?

**Comment by bkchr** [comment]
No, a bootnode doesn't need to be an archive node.

**Pull request closed without merging**
