### PR TITLE
Fix XCM benchmark template

### PR DESCRIPTION
**Pull request by ggwpez**
Update the weight template for XCM benchmarks. Discovered in https://github.com/paritytech/polkadot/pull/7245/

### CODE REVIEW

**Comment by ggwpez** [comment]
bot bench $ xcm kusama pallet_xcm_benchmarks::generic
bot bench $ xcm westend pallet_xcm_benchmarks::generic
bot bench $ xcm rococo pallet_xcm_benchmarks::generic

**Comment by ggwpez** [comment]
bot cancel  
bot clean  
bot bench $ xcm kusama pallet_xcm_benchmarks::generic
bot bench $ xcm westend pallet_xcm_benchmarks::generic
bot bench $ xcm rococo pallet_xcm_benchmarks::generic

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2927835

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2928246

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2928420

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2928524

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2930304

**Review by vstam1 — APPROVED** [review]

**Review by KiChjang — APPROVED** [review]

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
