### PR TITLE
Maintenance of bootnodes - gatotech

### PR DESCRIPTION
**Pull request by miloskriz**
Dear all, hello!

Please consider the following changes to the bootnode information for the chains indicated below:

- **Polkadot**: Update of `url` + `port` for gatotech's bootnode. Removal of unsecure websocket endpoint.
- **Kusama**: Update of `url` + `port` for gatotech's bootnode. Removal of unsecure websocket endpoint.
- **Westend**: Update of `url` + `port` for gatotech's bootnode. Removal of unsecure websocket endpoint.

(These bootnodes were originally added in PR #6499)

The changes have been tested at length and can be quickly checked with the following commands:

```shell
# Polkadot
polkadot --no-hardware-benchmarks --no-mdns --chain polkadot --reserved-only --reserved-nodes "/dns/boot-cr.gatotech.network/tcp/33100/p2p/12D3KooWK4E16jKk9nRhvC4RfrDVgcZzExg8Q3Q2G7ABUUitks1w"
polkadot --no-hardware-benchmarks --no-mdns --chain polkadot --reserved-only --reserved-nodes "/dns/boot-cr.gatotech.network/tcp/35100/wss/p2p/12D3KooWK4E16jKk9nRhvC4RfrDVgcZzExg8Q3Q2G7ABUUitks1w"

# Kusama
polkadot --no-hardware-benchmarks --no-mdns --chain kusama --reserved-only --reserved-nodes "/dns/boot-cr.gatotech.network/tcp/33200/p2p/12D3KooWRNZXf99BfzQDE1C8YhuBbuy7Sj18UEf7FNpD8egbURYD"
polkadot --no-hardware-benchmarks --no-mdns --chain kusama --reserved-only --reserved-nodes "/dns/boot-cr.gatotech.network/tcp/35200/wss/p2p/12D3KooWRNZXf99BfzQDE1C8YhuBbuy7Sj18UEf7FNpD8egbURYD"

# Westend
polkadot --no-hardware-benchmarks --no-mdns --chain westend --reserved-only --reserved-nodes "/dns/boot-cr.gatotech.network/tcp/33300/p2p/12D3KooWQGR1vUhoy6mvQorFp3bZFn6NNezhQZ6NWnVV7tpFgoPd"
polkadot --no-hardware-benchmarks --no-mdns --chain westend --reserved-only --reserved-nodes "/dns/boot-cr.gatotech.network/tcp/35300/wss/p2p/12D3KooWQGR1vUhoy6mvQorFp3bZFn6NNezhQZ6NWnVV7tpFgoPd"

``` 

**Note**: Bootnode support via previous endpoints will continue to be provided for a while even after this request is merged into a new binary version, to allow the networks to progressively upgrade to the new endpoints.

Many thanks!! have a great week!!

Best regards

**_Milos_**

### CODE REVIEW

**Review by ggwpez — COMMENTED** [review]
We now got a check for the bootnodes and it reported one failure:. You can check it by clicking on the `check-bootnodes` CI output. I restarted it, maybe that helps.  
```pre
[!] Bad bootnodes found for polkadot-new-chainspec:
    /dns/boot-cr.gatotech.network/tcp/[35](https://github.com/paritytech/polkadot/actions/runs/5176320840/jobs/9324991806?pr=7331#step:4:36)100/wss/p2p/12D3KooWK4E16jKk9nRhvC4RfrDVgcZzExg8Q3Q2G7ABUUitks1w

**Comment by miloskriz** [comment]
Thanks for the heads-up @ggwpez!!!

I can confirm that the rough test using `--reserved-only` method is still resulting OK for the Westend `wss` endpoint... 

I am re-checking all the details of this endpoint, specially those regarding offloading of the adequate SSL certificate...

I will edit this comment to add the results of these checks...

Thanks again!!

**_Milos_**

**Comment by miloskriz** [comment]
Dear @ggwpez, dear team, 

Could you please re-run the checks for the bootnodes?

Please note that I just realised that the issue was in polkadot's WSS connection (instead of Westend as I initially thought)..

A quick correction to the SSL offloading fixed the issue.

Many thanks for your help on this, and for considering this PR for further processing!!

Best regards

**_Milos_**

**Review by ggwpez — APPROVED** [review]
Yes the check is green now. Thanks @miloskriz!

**Review by bkchr — APPROVED** [review]

**Pull request merged**
