### PR TITLE
Runtime Updates for Rococo v1 Onboarding

### PR DESCRIPTION
**Pull request by shawntabrizi**
More runtime upgrades for the onboarding pallets in Rococo v1

### CODE REVIEW

**Review by rphmeier — APPROVED** [review]

**Comment by rphmeier** [comment]
bot merge

**Comment by shawntabrizi** [comment]
bot merge

**Comment by joao-paulo-parity** [comment]
https://github.com/paritytech/polkadot/pull/2756#issuecomment-809486370 is not intended behavior. Related to https://github.com/paritytech/parity-processbot/issues/266.

**Comment by shawntabrizi** [comment]
bot merge

**Comment by joao-paulo-parity** [comment]
bot merge

**Pull request merged**
