### PR TITLE
Add license to crates

### PR DESCRIPTION
**Pull request by Morganamilo**
This is required to publish to crates.io

I'm assuming all crates share the GPL3 license as polkadot main. If that's not the case please let me know about any exceptions.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3326080

**Review by ggwpez — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3328572

**Review by coderobe — APPROVED** [review]

**Comment by ggwpez** [comment]
bot rebase

**Review by mrcnski — APPROVED** [review]

**Comment by coderobe** [comment]
bot merge

**Pull request merged**
