### PR TITLE
Companion for impl Zero and One for fixed point numbers

### PR DESCRIPTION
**Pull request by xlc**
Companion for paritytech/substrate#8647

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by shawntabrizi** [comment]
@xlc need to `cargo update -p sp-io`

**Comment by shawntabrizi** [comment]
Merged the other PR.

@xlc make sure you turn on the setting so that parity people can contribute to the pr 🤷‍♂️

**Comment by xlc** [comment]
Humm I always thought it is enabled by default. I can't even see that setting in this screen...

**Comment by joao-paulo-parity** [comment]
Hey @xlc, bot maintainer here. Apparently this is a Github limitation reported in https://github.com/isaacs/github/issues/1681. I think that is why you don't see the setting. Sorry about that.

Probably would work if were to submit the PR from your own account's fork rather than the organization's, but it's understandable if you don't want to do that.

**Comment by xlc** [comment]
oh good to know. will do from my personal account next time

**Pull request closed without merging**
