### PR TITLE
Companion PR for #6846

### PR DESCRIPTION
**Pull request by seunlanlege**
Companion PR for paritytech/substrate#6846

### CODE REVIEW

**Comment by seunlanlege** [comment]
Honestly not sure what I'm doing wrong, but isn't CI supposed to automagically figure out that this a companion pr and adjust the branch accordingly?

**Comment by expenses** [comment]
@seunlanlege https://github.com/paritytech/polkadot/pull/1549 not any more.

**Comment by expenses** [comment]
I think you just ignore the CI failures.

**Comment by cecton** [comment]
Yes! Thank you. Just ignore the failures and re-run the build when substrate has been merge (or just use bot merge and it should merge anyway) @seunlanlege 

copy-pasting what I said the other day:

1. you push your companion PR
2. you DON'T update the substrate branch of your companion PR
3. you let the CI be red, this is expected
4. you wait for substrate to be green and merged
5. then only you retrigger the builds in polkadot
6. merge

**Comment by cecton** [comment]
@sjeohp This should not happen IMO. This branch has already been tested in substrate with check-polkadot-companion-build.

Now this build is running in polkadot but substrate has been merged. Everybody who is **right now** trying to make a branch on substrate with a companion branch are stuck because substrate and polkadot are out-of-sync for some time (the time of this build).

Would it be possible to bypass the checks and make the merge happens immediately (in general, I'm not talking about this PR as it is the weekend anyway)?

**Comment by cecton** [comment]
(I mean it is fine that the Cargo.lock is updated before merge but it shouldn't wait for the status to succeed)

**Comment by cecton** [comment]
I waited this build to show the problem:

image

The build failed because the labels are not set properly. But we don't care because it really is a change in substrate where there are labels already.

But now we have a permanent state where nobody can merge their PR on substrate until this issue is manually fixed by someone. This should not happen: if substrate succeeded, it should be merged right away, without additional check, without additional build time.

cc @sjeohp @TriplEight @kianenigma

**Comment by cecton** [comment]
bot merge

**Comment by sjeohp** [comment]
> Would it be possible to bypass the checks and make the merge happens immediately (in general, I'm not talking about this PR as it is the weekend anyway)?
>

@cecton It would mean granting processbot admin privileges I think, where currently it is only maintainer.

**Pull request merged**
