### PR TITLE
Companion PR for 'Make choosing an executor an explicit part of service construction' (#9525)

### PR DESCRIPTION
**Pull request by expenses**
See https://github.com/paritytech/substrate/pull/9525.

### CODE REVIEW

**Review by gilescope — APPROVED** [review]

**Review by chevdor — APPROVED** [review]
LGTM

**Review by HCastano — APPROVED** [review]

**Review by drahnr — APPROVED** [review]

**Comment by expenses** [comment]
I merged in https://github.com/paritytech/polkadot/pull/3657 to get `check-polkadot-companion-build` to run properly.

**Comment by expenses** [comment]
bot merge

**Comment by expenses** [comment]
bot merge

**Pull request merged**
