### PR TITLE
Fix migrations (#7340)

### PR DESCRIPTION
**Pull request by chevdor**
Backport of #7340 

cc @ggwpez

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]
Thanks!  
Lets double check the CI output here. Will probably still fail with max code size error until https://github.com/paritytech/polkadot/issues/7108

**Comment by chevdor** [comment]
Westend is now on `9430` already. 
Would it still be helpful to make a new Westend v9431 to test the new runtimes ?

**Comment by ggwpez** [comment]
>Westend is now on 9430 already.
Would it still be helpful to make a new Westend v9431 to test the new runtimes ?

It will need to be reverted though. Not sure what best release-engineering practice is in this case 😆

**Comment by chevdor** [comment]
The problem with reverting is that we won't undo the migrations already applied.
So ss long as the version is lower than 9430 after a downgrade, we could re-upgrade using  a new 9430 or simply upgrade again with a runtime v9431 without a downgrade that won't bring much.

**Comment by ggwpez** [comment]
AFAIK it is fine to use .43 again, since devops should be able to censor out the `Sudo::set_code` transactions.  
So it will be as if .43 got never enacted on Westend.  
But you can also do .431 I have no strong opinion on this.

**Comment by chevdor** [comment]
Let's keep it simple then. We will get a new set of 9430 runtimes once this PR is merged.

**Comment by ggwpez** [comment]
> AFAIK it is fine to use .43 again, since devops should be able to censor out the Sudo::set_code transactions.
So it will be as if .43 got never enacted on Westend.
But you can also do .431 I have no strong opinion on this.

This should work, or @bkchr ?

**Comment by ggwpez** [comment]
bot fmt

**Comment by bkchr** [comment]
> > 
> 
> This should work, or @bkchr ?

Yes that is right, if we revert. Then 9430 was never enacted on chain.

**Review by coderobe — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
Okay all :heavy_check_mark:  
- [Polkadot](https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2971449)
- [Kusama](https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2971450)
- [Westend](https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2971451)

**Comment by coderobe** [comment]
merged in https://github.com/paritytech/polkadot/commit/ba42b9ce51d25bdaf52d2c61e0763a6e3da50d25

**Pull request closed without merging**
