### PR TITLE
Test how long it takes to run tests with checked in and freshly built runtimes.

### PR DESCRIPTION
**Pull request by pepyakin**
Nothing to see here yet, come along...

### CODE REVIEW

**Comment by pepyakin** [comment]
So here it is. 

We can trade some of CI time to run tests both with checked in wasms and with rebuilt ones. This will help to avoid issues similar to https://github.com/paritytech/polkadot/pull/325

**Comment by pepyakin** [comment]
> This would be slower because we are running apt-get update every time now?

Previously, we ran `cargo test --all` only for `native` target but not for `wasm`. Now we run `cargo test --all` for both `wasm` and `native`.

So now `wasm` does everything that `native` did, but also rebuilds all wasm binaries (btw, this is the reason why the targets have been renamed). Thus `wasm` became slower than `native`.

**Comment by gavofyork** [comment]
would prefer to get our CI sped up a little before increasing the time for it to run by 30%.

**Comment by pepyakin** [comment]
Closing this for now. Will see what we can do with gitlab on that matter

**Pull request closed without merging**
