### PR TITLE
Specify Ethereum networks by their chain id

### PR DESCRIPTION
**Pull request by vgeddes**
Updates `NetworkId` to improve Ethereum chain selection. There are now several dozen EVM chains besides foundation and classic. Useful for XCM bridges that want to be interoperable with Polygon, Arbitum, Avalanche, and others as listed in https://chainlist.org/. 

Generally, every ethereum network has its own unique id, the chain id specified in [EIP-155](https://eips.ethereum.org/EIPS/eip-155). This ID is included in all signed transactions, and Ethereum nodes check the ID when validating a transaction. More recently [EIP-2294](https://eips.ethereum.org/EIPS/eip-2294) proposes to clamp the max value of the chain id to `u64`.

### CODE REVIEW

**Review by gavofyork — APPROVED** [review]

**Comment by gavofyork** [comment]
This will need code to convert `v2::Junction` to `v3::Junction` and back.

**Review by gavofyork — CHANGES_REQUESTED** [review]
This will need code to convert `v2::Junction` to `v3::Junction` and back.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2217461

**Comment by vgeddes** [comment]
> This will need code to convert `v2::Junction` to `v3::Junction` and back.

Hey, If I understand correctly, are you suggesting that we should add conversions between `v2::NetworkId::Named("Ethereum")` and `v3::NetworkId::Ethereum { chain_id: 1 }`?

If we do that, then for consistency we may also have to add other conversions such as `v2::NetworkId::Named("Rococo")` and `v3::NetworkId::Rococo`, which will bloat the conversion code a bit.

**Comment by gavofyork** [comment]
`TryFrom<v3::Junction>` must be properly impled for `v2::Junction` and vice versa. This PR breaks it.

**Comment by gavofyork** [comment]
More specifically, `Option<v3::NetworkId>` should fully implement `From<v2::NetworkId>`. That said, on retrospect, I don't think this PR really makes matters worse as nothing beyond Polkadot and Kusama were covered in the conversion. So I'll just approve.

**Review by KiChjang — APPROVED** [review]

**Pull request merged**
