### PR TITLE
Don't store available data on disputes

### PR DESCRIPTION
**Pull request by eskimor**
If there are lots of disputes, this leads to blowing up disk space on
validators. Rob luckily remembered that we do store the full
availability in participation.

The argument in the code does not make too much sense with the current
implementation, as no validator will ever request anything else from us,
than "our" piece.

### CODE REVIEW

**Review by slumber — APPROVED** [review]

**Review by ordian — APPROVED** [review]
Should we call `StoreChunk` to store our chunk in case it's missing?

**Comment by eskimor** [comment]
> Should we call `StoreChunk` to store our chunk in case it's missing?

We could, but I believe the current availability is already very robust*). In other words, we have bigger fish to fry - I don't think we should bother for now.

*) Thanks to a recent PR by @slumber availability-distribution will keep trying to fetch a chunk, even after inclusion has been reached.

There are some sophisticated attacks, which involve only sending chunks to certain validators and for these kind of attacks storing our chunk in case it is missing could actually help - on the other hand those attacks are outside of our threat model (they 1/3 dishonest + nodes offline), hence: Let's focus on more important things.

**Comment by ordian** [comment]
> Thanks to a recent PR by @slumber availability-distribution will keep trying to fetch a chunk, even after inclusion has been reached.

Do you have a link?

**Comment by slumber** [comment]
> > Thanks to a recent PR by @slumber availability-distribution will keep trying to fetch a chunk, even after inclusion has been reached.
> 
> Do you have a link?

https://github.com/paritytech/polkadot/pull/4596

**Pull request merged**
