### PR TITLE
Backport updates of substrate

### PR DESCRIPTION
**Pull request by thiolliere**
backport both update of substrate:

https://github.com/paritytech/polkadot/pull/407
https://github.com/paritytech/polkadot/pull/411

### CODE REVIEW

**Comment by bkchr** [comment]
This breaks syncing Kusama at around block 20k. We first need to investigate this.

**Comment by bkchr** [comment]
This pr breaks syncing: https://github.com/paritytech/substrate/commit/ca7f4c9273cff541407c2f3a24cf2077c5ffe1c3

We initialize the storage of the uncles and that breaks the storage root hash. 

@thiolliere please increment the `spec_version` and it should be fine.

**Comment by thiolliere** [comment]
As rob told me we might want to include  ICMP message-routing gossip #304 in the backport as well.
So now it is included

**Comment by thiolliere** [comment]
I synced to kusama with this branch

**Pull request merged**
