### PR TITLE
Companion for removal of execution strategies

### PR DESCRIPTION
**Pull request by bkchr**
https://github.com/paritytech/substrate/pull/14387

cumulus companion: https://github.com/paritytech/cumulus/pull/2836

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3095534

**Review by sergejparity — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3112383

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3160948

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3161019

**Review by koute — APPROVED** [review]

**Review by michalkucharczyk — APPROVED** [review]

**Review by melekes — APPROVED** [review]

**Review by rcny — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3167210

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge force

**Pull request merged**
