### PR TITLE
New runners for weights and new weights

### PR DESCRIPTION
**Pull request by alvicsam**
Switching `weights` job to run on new, dynamically created runners. The results differ from current `bm` runners but they are consistent. Examples can be found here:

https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2282626
https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2279308
https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2279411

cc https://github.com/paritytech/ci_cd/issues/697
close https://github.com/paritytech/command-bot/issues/131

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2227603

**Comment by alvicsam** [comment]
bot rebase

**Comment by alvicsam** [comment]
bot rebase

**Comment by alvicsam** [comment]
bot rebase

**Review by oleg-plakida — APPROVED** [review]

**Review by oleg-plakida — APPROVED** [review]

**Comment by ggwpez** [comment]
Could we re-run them please?  
Some of the weights changes since last release and now its difficult to compare. For example the bounties pallet on Polkadot https://weights.tasty.limo/compare?repo=polkadot&threshold=0&path_pattern=runtime%2F*%2Fsrc%2Fweights%2F**%2F*.rs%2Cbridges%2Fmodules%2F*%2Fsrc%2Fweights.rs&method=guess-worst&ignore_errors=true&unit=time&old=master&new=as-weights-2&git_pull=false

**Comment by alvicsam** [comment]
bot rebase

**Comment by alvicsam** [comment]
@ggwpez I re-ran the benches and added updated weights. Could you check them please?

**Review by ggwpez — APPROVED** [review]
Looks great :tada:

**Review by sergejparity — APPROVED** [review]

**Review by coderobe — APPROVED** [review]

**Pull request merged**
