### PR TITLE
Add event to asset claim

### PR DESCRIPTION
**Pull request by girazoki**
Throws an event for asset claims for better traceability

### CODE REVIEW

**Review by KiChjang — APPROVED** [review]

**Comment by KiChjang** [comment]
I think this should really be merged into the XCM v3 branch, but not sure if it's also OK to just merge to master. I could simply merge master on the XCM v3 branch afterwards.

**Comment by girazoki** [comment]
I'm fine with any, you prefer if I do it against v3?

**Comment by KiChjang** [comment]
It's probably fine to merge to master. It's not a huge deal for me to merge master in the XCM v3 branch.

**Comment by girazoki** [comment]
Oh cool. Is there anyone I can ping to review?

**Review by shawntabrizi — APPROVED** [review]

**Comment by KiChjang** [comment]
bot merge

**Pull request merged**
