### PR TITLE
Re-export current primitives in crate root

### LINKED ISSUE #6480: Polkadot primitives versioning
A necessity to bump the primitives' version to the next one results in 2000+ lines of PR. The actual logic of such a PR gets buried under purely technical changes of versioning. (See #6161)

The problem is that primitives are referred by their current version, and bumping the version requires moving all the primitives to a new module with a higher version number. So, any source referring to a primitive (that is, effectively, every source file of Polkadot) needs to be altered only to adopt that simple change: `use polkadot_primitives::v2` -> `use polkadot_primitives::v3`.

The proposal is to reexport all the primitives not currently requiring versioning in the root of the `polkadot_primitives` crate.

That is, if we have a `StablePrimitive` that does not change from `v1` to `v2` and an `UpgradedPrimitive` which changes from `v1` to `v2`, `primitives/src/lib.rs` would look like the following:

```rust
pub mod v1;
pub mod v2;
pub use v2::StablePrimitive;
```

Thus, any module referring to `polkadot_primitives::StablePrimitive` doesn't need to be changed to adopt a new version in which the primitive did not change anyway. Still, if a module uses `UpgradedPrimitive`, it is forced to explicitly choose between either `v1` or `v2` as we have two different versions of the primitive.

A further upgrade to `v3` would involve changes in the `polkadot_primitives` crate root and point changes to the code using primitives that became versioned during the upgrade, and it will not be as awfully polluting as it is right now.

CC @rphmeier @eskimor @tdimitrov

### PR DESCRIPTION
**Pull request by s0me0ne-unkn0wn**
Closes #6480 

Current primitives not requiring versioning are re-exported from the `primitives` crate root.

For those who don't want to scroll a lot, all the meaningful changes are in `primitives/src/lib.rs`.

Cumulus companion: paritytech/cumulus#2067

### CODE REVIEW

**Review by mrcnski — COMMENTED** [review]
I like this change and I *think* this is good and sound, but don't feel totally qualified to say whether we want this or not.

**Review by sandreim — APPROVED** [review]
This change at least makes code look a bit cleaner. It will also make PRs bumping version less verbose. 

One thing I am unsure is if being implicit in this case is better than explicit when it comes to primitives that are changed. It might be error prone, for example in the case of primitives that are used in network protocol which also has versioning and might need to support 2 versions at the same time.

**Review by acatangiu — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2234270

**Review by ordian — APPROVED** [review]
I would be in favor of merging this PR and then rebasing #6161 on top of that. That will make audit of the latter PR much easier.

I understand the concern about being explicit vs implicit, however, networking code has its own versioning, which is separate from from primitives versioning. We should obviously not change the fundamental types, such as `Hash` as it will break everything, but I don't think this is a concern here.

**Comment by ordian** [comment]
(disabled auto-merge; it needs to be merged with `bot` because of companion)

**Review by eskimor — APPROVED** [review]

**Comment by s0me0ne-unkn0wn** [comment]
bot merge

**Comment by ordian** [comment]
The linked issue https://github.com/paritytech/polkadot/issues/6480 mentioned the idea of separating stable primitives from upgradable. I think that might be useful and in that case, `SessionInfo` would fall into upgradable category.

**Comment by s0me0ne-unkn0wn** [comment]
bot merge

**Pull request merged**
