### PR TITLE
Exploration of using graphwiz

### PR DESCRIPTION
**Pull request by pepyakin**
Working on #1297 made me curious what's the experience of using graphviz of diagrams.

Screenshot 2020-06-20 at 20 06 01

They do look nice when rendered, but otherwise unreadable in plain markdown and are rather indirect when drawing. Also, not sure if every diagram would be drawable with it and it will make us into the the graphviz framework.

All in all, I have a conflicting feelings about this. Therefore, feel free to close.

### CODE REVIEW

**Comment by rphmeier** [comment]
I'm for this, it's fine if it's not readable within the markdown IMO

**Comment by coriolinus** [comment]
Agree, the rendered output is a lot nicer than ASCII-art, and IMO the relative ease-of-use of graphviz will encourage contributors to add more diagrams.

**Comment by montekki** [comment]
Awesome the only thing that worries me is the dark color scheme in the docs. And I can't test it bc  `mdbook-graphviz` does not seem to work on my box

**Comment by rphmeier** [comment]
Will test on my machine, worrying that it doesn't work for @montekki

**Comment by montekki** [comment]
fwiw here is the log (graphviz is installed):
```
2020-06-22 14:11:48 [INFO] (mdbook::book): Book building has started
2020-06-22 14:11:48 [WARN] (mdbook::preprocess::cmd): The command wasn't found, is the "graphviz" preprocessor installed?
2020-06-22 14:11:48 [WARN] (mdbook::preprocess::cmd):   Command: mdbook-graphviz
2020-06-22 14:11:48 [INFO] (mdbook::book): Running the html backend
2020-06-22 14:11:48 [WARN] (mdbook::preprocess::cmd): The command wasn't found, is the "graphviz" preprocessor installed?
```

**Comment by rphmeier** [comment]
You installed `cargo install mdbook-graphviz` but it can't find the binary?

**Comment by montekki** [comment]
yes

**Comment by montekki** [comment]
Reinstalling fails with
```
  = note: cc: fatal error: cannot read spec file ‘./specs’: Is a directory
          compilation terminated.


error: aborting due to previous error

error: could not compile `pulldown-cmark`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...

```

**Comment by riusricardo** [comment]
@montekki You may need to install the [graphviz](https://graphviz.gitlab.io/download/) binary, not just mdbook-graphviz

**Comment by rphmeier** [comment]
Does `mdbook-graphviz` show up in the `$PATH`? If so then I'm not sure why the `mdbook` would not be able to find it, since it is just running subcommands.

**Pull request merged**
