### PR TITLE
[DNM] Debug bench bot

### PR DESCRIPTION
**Pull request by ggwpez**
Testing https://github.com/paritytech/pipeline-scripts/pull/79 on top of https://github.com/paritytech/polkadot/pull/5205

### CODE REVIEW

**Comment by ggwpez** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=oty-enable-instance-benchmarking -c bench-bot $ runtime kusama-dev pallet_referenda

**Comment by ggwpez** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=oty-enable-instance-benchmarking -c bench-bot $ runtime kusama-dev pallet_referenda

**Comment by ggwpez** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=9ecc0607cb85b29301ab4cdfcb02a2fe37bbbf9d -c bench-bot $ runtime kusama-dev pallet_referenda

**Comment by ggwpez** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=hello-is-this-even-used -c bench-bot $ runtime kusama-dev pallet_referenda

**Comment by ggwpez** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=oty-enable-instance-benchmarking -v PIPELINE_SCRIPTS_REPOSITORY=https://github.com/paritytech/pipeline-scripts -c bench-bot $ runtime kusama-dev pallet_referenda

**Comment by ggwpez** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=oty-enable-instance-benchmarking PIPELINE_SCRIPTS_REPOSITORY=https://github.com/paritytech/pipeline-scripts -c bench-bot $ runtime kusama-dev pallet_referenda

**Comment by ggwpez** [comment]
/cmd queue -c bench-bot -v PIPELINE_SCRIPTS_REPOSITORY=https://github.com/paritytech/pipeline-scripts -v PIPELINE_SCRIPTS_REF=hello-invalid-test $ runtime kusama-dev pallet_referenda

**Comment by ggwpez** [comment]
/cmd queue -c bench-bot $ runtime kusama-dev pallet_referenda

**Comment by ggwpez** [comment]
The bot now creates one weight file for each instance, when called with the standard syntax. See the last commit f10cdf3e7c6b5b6bddec8ac2e39ddeb4af80f492.

**Comment by ggwpez** [comment]
/cmd queue -v PATCH_substrate=tmp-oty-debug-bench-bot-revert -c bench-bot $ runtime polkadot-dev pallet_bounties

**Comment by alvicsam** [comment]
/cmd queue -v PATCH_substrate=tmp-oty-debug-bench-bot-revert -c bench-bot $ runtime polkadot-dev pallet_bounties

**Comment by alvicsam** [comment]
/cmd queue -v PATCH_substrate=tmp-oty-debug-bench-bot-revert -c bench-bot $ runtime polkadot-dev pallet_bounties

**Comment by mordamax** [comment]
bot rebase

**Comment by mordamax** [comment]
/cmd queue -v PATCH_substrate=tmp-oty-debug-bench-bot-revert -v PIPELINE_SCRIPTS_REF=mak/fix-locked-for-patched-bench -c bench-bot $ runtime polkadot-dev pallet_bounties

**Comment by ggwpez** [comment]
/cmd queue -v PATCH_substrate=tmp-oty-debug-bench-bot-revert -v PIPELINE_SCRIPTS_REF=mak/fix-locked-for-patched-bench -c bench-bot $ runtime polkadot-dev pallet_child_bounties

**Comment by ggwpez** [comment]
/cmd queue -v PATCH_substrate=tmp-oty-debug-bench-bot-revert -v PIPELINE_SCRIPTS_REF=mak/fix-locked-for-patched-bench -c bench-bot $ runtime kusama-dev pallet_child_bounties

**Comment by ggwpez** [comment]
/cmd queue -v PATCH_substrate=tmp-oty-debug-bench-bot-revert -v PIPELINE_SCRIPTS_REF=mak/fix-locked-for-patched-bench -c bench-bot $ runtime westend-dev pallet_child_bounties

**Comment by ggwpez** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=mak/fix-locked-for-patched-bench -c bench-bot $ runtime westend-dev pallet_child_bounties

**Pull request closed without merging**
