### PR TITLE
Co #14586: `WeightMeter`: more consistent naming

### PR DESCRIPTION
**Pull request by ggwpez**
Companion for https://github.com/paritytech/substrate/pull/14586

Changes:
- Dont use deprecated functions

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3202878

**Review by bkchr — APPROVED** [review]

**Review by juangirini — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3210166

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3212906

**Comment by ggwpez** [comment]
Merged into https://github.com/paritytech/polkadot/pull/7432

**Pull request closed without merging**
