### PR TITLE
[don't merge] try-runtime testing

### PR DESCRIPTION
**Pull request by coderobe**

### CODE REVIEW

**Comment by coderobe** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=kusama-dev --execution=Wasm --no-spec-name-check on-runtime-upgrade live --uri wss://kusama-try-runtime-node.parity-chains.parity.io:443

/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=polkadot-dev --execution=Wasm --no-spec-name-check on-runtime-upgrade live --uri wss://polkadot-try-runtime-node.parity-chains.parity.io:443

**Comment by coderobe** [comment]
...

/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=kusama-dev --execution=Wasm --no-spec-check-panic on-runtime-upgrade live --uri wss://kusama-try-runtime-node.parity-chains.parity.io:443

/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=polkadot-dev --execution=Wasm --no-spec-check-panic on-runtime-upgrade live --uri wss://polkadot-try-runtime-node.parity-chains.parity.io:443

**Comment by coderobe** [comment]
getting auto-canceled again

/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=kusama-dev --execution=Wasm --no-spec-check-panic on-runtime-upgrade live --uri wss://kusama-try-runtime-node.parity-chains.parity.io:443

**Comment by coderobe** [comment]
canceled again...

**Comment by ggwpez** [comment]
Yep the nodes somehow time out. I am talking to Devops but no idea what is the actual cause.

**Comment by ggwpez** [comment]
But the `Not enough data to fill buffer` looks like a legit migration error to me. Gonna test it locally.

**Pull request closed without merging**
