### PR TITLE
Fix sorting for 0.9.16

### PR DESCRIPTION
**Pull request by eskimor**

### CODE REVIEW

**Review by chevdor — APPROVED** [review]

**Comment by eskimor** [comment]
> could you backport the rest of the commits of #4795?

I really don't want to. I checked, functionality wise it is the same. This waiting for CI to finally carry on with tasks is driving me crazy - I want that to finally stop.

**Comment by eskimor** [comment]
I would prefer a workflow next time, where fixes just go to the release branch and once the release is done, we merge the release branch to master. - Would be way less tedious and error prone.

**Comment by drahnr** [comment]
If we only have one release at a time, this might work sufficiently well, iff and only iff master doesn't move too fast. As soon as one has more than one release branch at the same time or master picking up with our team growth, this will become a mess.

**Comment by eskimor** [comment]
> If we only have one release at a time, this might work sufficiently well, iff and only iff master doesn't move too fast. As soon as one has more than one release branch at the same time or master picking up with our team growth, this will become a mess.

Once the release is out, this is a different thing- then I am actually fine with back-porting. I am only concerned with the release branch prior to release.

**Comment by eskimor** [comment]
> It seems the real problem here is long CI times. My main concern if we're to backport some urgent changes for 0.9.17 to 0.9.16 branch we might end up fixing some merge conflicts, which is unnecessary.

Yes, long CI times are a big source of delays. Amplified by unnecessary/unknown changes, which cause PRs to fail, although they worked fine when based on master. So you end up not only waiting once for CI, but several times for a single stupid PR, that actually was already fine on master.

**Comment by chevdor** [comment]
Could you please change the base so we merge this PR into `wk-prep-v0.9.16-rc7` ?

**Pull request closed without merging**
