### PR TITLE
Substrate Companion for #9566

### PR DESCRIPTION
**Pull request by ferrell-code**
Companion for [paritytech/substrate#9566](https://github.com/paritytech/substrate/pull/9566)

Migration of Pallet Prefix of "Treasury" to "Bounties" for `pallet_bounties`

### CODE REVIEW

**Review by thiolliere — APPROVED** [review]
looks good to me, I tested with try-runtime on current state kusama and polkadot

**Comment by ferrell-code** [comment]
Thanks for the help @thiolliere , but take care that it works right, I don't quite fully trust myself with the storage migration :package:

**Comment by shawntabrizi** [comment]
any updates on testing the migration?

**Comment by thiolliere** [comment]
I tested with try-runtime 4 days ago, the substrate has no new change since, apart from benchmarking fix.

**Comment by ferrell-code** [comment]
yeah its good on my end too, storage migrations just give me anxiety haha

**Comment by ordian** [comment]
cc @joao-paulo-parity ^^^

**Review by ordian — APPROVED** [review]

**Comment by joao-paulo-parity** [comment]
https://github.com/paritytech/polkadot/pull/3704#issuecomment-923970597 is related to https://github.com/paritytech/parity-processbot/issues/302. I guess some workflow files were unintentionally brought in during `merge master` and that is why it failed.

**Comment by ordian** [comment]
bot merge

**Comment by ordian** [comment]
Does Westend also need a migration?

**Pull request merged**
