### PR TITLE
[DNM] testing-all-pallets-bench

### PR DESCRIPTION
**Pull request by mordamax**

### CODE REVIEW

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all kusama

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all kusama

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all kusama

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all kusama

**Comment by mordamax** [comment]
bot rebase

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all kusama

**Comment by mordamax** [comment]
bot rebase

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all polkadot

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all polkadot

**Comment by mordamax** [comment]
bot rebase

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all polkadot

**Comment by ggwpez** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all polkadot

**Comment by ggwpez** [comment]
Lets see if there is a diff between the consecutive runs.

**Comment by ggwpez** [comment]
Hm there is a conflict with the `.patch` file :unamused:. Maybe we should also upload all the weight files, instead of just the diff.

**Pull request closed without merging**
