### PR TITLE
Fix bench bot

### PR DESCRIPTION
**Pull request by kianenigma**
that whole `is_polkadot` was wrong, I looked around and it seems like we only have `is_xxx` for chains other than polkadot and `else`, it is polkadot. It makes sense given the name of the repo :P

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
