### PR TITLE
export xcm_pallet config

### PR DESCRIPTION
**Pull request by 0x8f701**
Signed-off-by: Cheng JIANG <alex_cj96@foxmail.com>

close: #4115 

cc: @KiChjang 

Not sure if I should touch kusama's genesis config, but it can be useful to be able to test against kusama-local

### CODE REVIEW

**Comment by GopherJ** [comment]
> Exporting the `Config` part from XCM pallet is fine, I just want to ensure that we're not trying to change any sort of config on Kusama (though it's rather pointless since Kusama's already launched and `GenesisConfig` won't ever affect it again...)

yes that's why I changed it, because now  I have to test against kusama-local because westend-local is broken with weight issue

**Comment by GopherJ** [comment]
> https://github.com/paritytech/polkadot/blob/666e67d2e753644dfc9f042195bfc9e1051e4eb5/xcm/pallet-xcm/src/lib.rs#L391-L394
> 
> ```
> pub struct GenesisConfig<T: Config> {
>         /// The default version to encode outgoing XCM messages with.
>         pub safe_xcm_version: Option<XcmVersion>,
>         pub phantom: sp_std::marker::PhantomData<T>,
> }
> ```
> 
> Can you change this? So can change it in TestExternalities
> 
> ```
> pallet_xcm::GenesisConfig::<Runtime> {
>         safe_xcm_version: Some(2),
>         ..Default::default()
> }
> .assimilate_storage(&mut t)
> .unwrap();
> 
> 
> .assimilate_storage(&mut t)
>     |      ^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `T` declared on the trait `GenesisBuild`
> ```

can you review now to see if it's ok?

**Comment by KiChjang** [comment]
> https://github.com/paritytech/polkadot/blob/666e67d2e753644dfc9f042195bfc9e1051e4eb5/xcm/pallet-xcm/src/lib.rs#L391-L394
> 
> ```
> pub struct GenesisConfig<T: Config> {
>         /// The default version to encode outgoing XCM messages with.
>         pub safe_xcm_version: Option<XcmVersion>,
>         pub phantom: sp_std::marker::PhantomData<T>,
> }
> ```
> 
> Can you change this? So can change it in TestExternalities
> 
> ```
> pallet_xcm::GenesisConfig::<Runtime> {
>         safe_xcm_version: Some(2),
>         ..Default::default()
> }
> .assimilate_storage(&mut t)
> .unwrap();
> 
> 
> .assimilate_storage(&mut t)
>     |      ^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `T` declared on the trait `GenesisBuild`
> ```

@zjb0807 I'm actually unsure why you're hitting this issue, but I don't think adding a type parameter to `GenesisConfig` solves your problem, in fact it looks to me like a hack if it did "accidentally" solve your issue.

**Comment by zjb0807** [comment]
> @zjb0807 I'm actually unsure why you're hitting this issue, but I don't think adding a type parameter to `GenesisConfig` solves your problem, in fact it looks to me like a hack if it did "accidentally" solve your issue.

I realized that this is not good, so I suggested this way again.



> ```
>     #[cfg(feature = "std")]
>     impl GenesisConfig {
>         /// Direct implementation of `GenesisBuild::build_storage`.
>         ///
>         /// Kept in order not to break dependency.
>         pub fn build_storage<T: Config>(&self) -> Result<sp_runtime::Storage, String> {
>             <Self as frame_support::traits::GenesisBuild<T>>::build_storage(self)
>         }
> 
>         /// Direct implementation of `GenesisBuild::assimilate_storage`.
>         ///
>         /// Kept in order not to break dependency.
>         pub fn assimilate_storage<T: Config>(
>             &self,
>             storage: &mut sp_runtime::Storage,
>         ) -> Result<(), String> {
>             <Self as frame_support::traits::GenesisBuild<T>>::assimilate_storage(self, storage)
>         }
>     }
> ```
> 
> ```
>     pallet_xcm::GenesisConfig { safe_xcm_version: Some(2) }
>         .assimilate_storage::<Test>(&mut t)
>         .unwrap();
> ```
> 
> The implementation of `GenesisBuild::assimilate_storage` avoide `PhantomData`.

**Comment by zjb0807** [comment]
> > @GopherJ Can we revert the changes that made `GenesisConfig` generic?
> 
> done

Can you help add this implementation?

> ```
>     #[cfg(feature = "std")]
>     impl GenesisConfig {
>         /// Direct implementation of `GenesisBuild::build_storage`.
>         ///
>         /// Kept in order not to break dependency.
>         pub fn build_storage<T: Config>(&self) -> Result<sp_runtime::Storage, String> {
>             <Self as frame_support::traits::GenesisBuild<T>>::build_storage(self)
>         }
> 
>         /// Direct implementation of `GenesisBuild::assimilate_storage`.
>         ///
>         /// Kept in order not to break dependency.
>         pub fn assimilate_storage<T: Config>(
>             &self,
>             storage: &mut sp_runtime::Storage,
>         ) -> Result<(), String> {
>             <Self as frame_support::traits::GenesisBuild<T>>::assimilate_storage(self, storage)
>         }
>     }
> ```
> 
> ```
>     pallet_xcm::GenesisConfig { safe_xcm_version: Some(2) }
>         .assimilate_storage::<Test>(&mut t)
>         .unwrap();
> ```
> 
> The implementation of `GenesisBuild::assimilate_storage` avoide `PhantomData`.

**Comment by KiChjang** [comment]
@zjb0807 Sorry, what exactly is going on here? Are you asking for a technical support, or are you suggesting a change on this PR?

**Comment by zjb0807** [comment]
> @zjb0807 Sorry, what exactly is going on here? Are you asking for a technical support, or are you suggesting a change on this PR?

I want to modify the genesis config in TestExternalities.
```
pallet_xcm::GenesisConfig { safe_xcm_version: Some(2) }
        .assimilate_storage::<Test>(&mut t)
        .unwrap();
```

**Comment by KiChjang** [comment]
@zjb0807 And why are you asking about that here in this PR?

**Comment by zjb0807** [comment]
> @zjb0807 And why are you asking about that here in this PR?

Ok. You can approve the PR and I'll do it through another PR.

**Comment by GopherJ** [comment]
> > @zjb0807 And why are you asking about that here in this PR?
> 
> Ok. You can approve the PR and I'll do it through another PR.

yes that'll be easier because I didn't understand it yet sorry didn't help:)

**Pull request merged**
