### PR TITLE
Remove check_web_wasm job

### PR DESCRIPTION
**Pull request by s3krit**
companion for https://github.com/paritytech/substrate/pull/9541

### CODE REVIEW

**Review by dvdplm — APPROVED** [review]
Oh is this why #9541 is stuck? You're my new best friend.

**Comment by s3krit** [comment]
> Oh is this why #9541 is stuck? You're my new best friend.

Nah, see my comment in #9541 for why it's stuck (required check hasn't yet been removed)

**Review by TriplEight — APPROVED** [review]
LGTM!

**Comment by TriplEight** [comment]
`check-web-wasm` was not required for merging.

**Pull request merged**
