### PR TITLE
Refactor XCM Executor: move `process_instruction` to a trait

### PR DESCRIPTION
**Pull request by librelois**
The goal of this PR is to make the execution of some XCM instructions customizable, while still being able to rely on the reference implementation as much as possible.

The only idea that came to me to achieve this goal is to move the `process_instruction` function into a new trait. It seems that this also requires moving the state of the XCVM into its own struct.

Thus, if a parachain needs to modify the behavior of some instructions, or/and add some pre/post hooks, it can create a wrapper that implement the `ProcessInstruction` trait and rely on an inner implementation:

```rust
pub struct XcmProcessorWrapper<Inner: ProcessInstruction> {
	inner: Inner,
	custom_registers: CustomRegisters,
}

impl<Call, Inner: ProcessInstruction> ProcessInstruction<Call> for XcmProcessorWrapper<Inner> {
	fn new() -> Self {
		Self { inner: Inner::new(), custom_registers: CustomRegisters::new() }
	}

	fn process_instruction(
		&mut self,
		vm_state: &mut StateOf<Config>,
		instr: Instruction<Config::RuntimeCall>,
	) -> Result<(), XcmError> {
                // Do some pre stuff
               pre_hook(vm_state, &instr)?;

                // Execute some specific XCM instructions in a custom way
                if let CUSTOM_PATTERN = instr {
                  custom_execution(...)?;
	        } else  {
                  // Rely on the polkadot implementation in any other case
                  self.inner.process_instruction(vm_state, instr)?;
                }

               // Do some post stuff
               post_hook(vm_state, &instr)
        }
```

If you have a simpler idea to achieve the same goal, it is welcome :) 

---

cumulus companion: https://github.com/paritytech/cumulus/pull/2370

### CODE REVIEW

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/how-to-handle-not-withdrawable-assets-properly-with-xcm/2270/10

**Comment by crystalin** [comment]
@KiChjang , can we get a review on this. This is the related to the discussion there https://forum.polkadot.network/t/how-to-handle-not-withdrawable-assets-properly-with-xcm/2270

**Comment by KiChjang** [comment]
To me, it feels like the entire approach is rendering the `ExecuteXcm` trait pointless. Is it not possible to simply create a wrapper around `XcmExecutor` to accomplish the same task? E.g. something like `struct MyXcmExecutor<Exec: ExecuteXcm> { some_state: u8, _base_executor: PhantomData<Exec> }` and then implement `ExecuteXcm` on `MyXcmExecutor`, performing some bookkeeping details in `execute_xcm` until it hands off execution back to `Exec::execute_xcm` by calling it.

**Comment by librelois** [comment]
> Is it not possible to simply create a wrapper around `XcmExecutor` to accomplish the same task? E.g. something like `struct MyXcmExecutor<Exec: ExecuteXcm> { some_state: u8, _base_executor: PhantomData<Exec> }` and then implement `ExecuteXcm` on `MyXcmExecutor`, performing some bookkeeping details in `execute_xcm` until it hands off execution back to `Exec::execute_xcm` by calling it.

Unfortunately, no, this is not possible. We have already tried this approach without success. We need to change the **internal logic** of some instructions, today we can't do that without maintaining a fork of polkadot code.

> it feels like the entire approach is rendering the ExecuteXcm trait pointless

I don't think so, these 2 features don't have the same objective nor the same target.
The `ExecuteXcm` trait defines the interface to execute an XCM message, while the `ProcessInstruction` trait is internal to the configuration of a particular executor to make it more configurable, these are two different things that cannot be merged into the same trait.

**Comment by girazoki** [comment]
> To me, it feels like the entire approach is rendering the `ExecuteXcm` trait pointless. Is it not possible to simply create a wrapper around `XcmExecutor` to accomplish the same task? E.g. something like `struct MyXcmExecutor<Exec: ExecuteXcm> { some_state: u8, _base_executor: PhantomData<Exec> }` and then implement `ExecuteXcm` on `MyXcmExecutor`, performing some bookkeeping details in `execute_xcm` until it hands off execution back to `Exec::execute_xcm` by calling it.

Since we need to modify the behavior of just a few instructions (potentially only 2), although I think the solution proposed by @KiChjang would work (perhaps, making the process_instruction public), it might be harder to maintain. Here is my reasoning about it:

- `execute_xcm` works on a message basis, and not on an instruction basis. That means that `MyXcmExecutor` would need to re-implement most of the stuff `ExecuteXcm` implements, but relay on the inner `ExecuteXcm.process_instruction` if the instruction to be processed is not one of the few we need to modify.

- The inner  `ExecuteXcm.process_instruction` would need to know the state with which we need to work, so we would need a way to pass this state (`holding_limit, context, etc`). Right now there does not seem to be a way to do this.

That being said, I also dont like something that this PR introduces: We are defining XCVm process instruction configuration (`AssetTransactor`, `SafeCallFilter`, etc while we later pass a `ProcessInstruction` trait that could simply ignore all this I think. 

I think the process of decoupling instruction processing and making it configuratble goes into the right direction, but we might want to put some more thought in there. Even if I know its overkill, how would you feel about a separate Config for `ProcessInstruction` and for `XcmExecute`?

**Comment by crystalin** [comment]
@gavofyork what is your opinion on it ? This is an important part for us to move forward.

**Comment by KiChjang** [comment]
I think instead of something like this, we could configure an instruction pre-processor for the XCM executor. The way it works is that we'd consult it first before calling `process_instruction`, and if the function returns something like `Some(ControlFlow::Continue)`, it'll refuse to call `process_instruction`, and likewise if it returns `Some(ControlFlow::Break)`.

In code, it would look something like the following:

```rust
let inst_res = recursion_count::using_once(&mut 1, || {
	recursion_count::with(|count| {
		if *count > RECURSION_LIMIT {
			return Err(XcmError::ExceedsStackLimit)
		}
		*count = count.saturating_add(1);
		Ok(())
	})
	// This should always return `Some`, but let's play it safe.
	.unwrap_or(Ok(()))?;

	// Ensure that we always decrement the counter whenever we finish processing
	// the instruction.
	defer! {
		recursion_count::with(|count| {
			*count = count.saturating_sub(1);
		});
	}

	match InstructionPreprocessor::preprocess(&mut self, &mut instr) {
		Some(ControlFlow::Continue(res)) => return res.map(ControlFlow::Continue(())),
		Some(ControlFlow::Break(res)) => return res.map(ControlFlow::Break(())),
		None => (),
	}

	self.process_instruction(instr)
});
```

**Comment by gavofyork** [comment]
At the risk of regurgitating @KiChjang's suggestion, one possibility would be to introduce an XCVM processor-extension trait.

This would basically be a trait:

```
trait XcmExecutorOverride<Config> {
	fn process_instruction_override(
		exec: &mut XcmExecutor<Config>,
		instr: Instruction<Config::RuntimeCall>,
	) -> Option<Result<(), XcmError>> {
		// This returns Some(..) if it doesn't want `XcmExecutor::process_instruction` to
		// be called for this `instr`. Returning `None` just does what it does currently.
		None
	}
}
```

It is questionable whether you would want to introduce non-standard state into the XCVM given that the extra state could lead to am implementation incompatible with the standard. If it were decided that it's needed, then I'd include a `&mut self` argument in `process_instruction_override` and a `fn new() -> Self;`. The `Option` could be a tristate or `enum` if we wanted to allow the override to include control-flow stuff. One important issue would be weights/benchmarks: we'd have to be congniscant that sophisticated logic in the override could confuse the benchmarking and possibly lead to occasions of heavy-weight instructions being underestimated.

**Comment by librelois** [comment]
> This can be done anyway through passing an &mut XcmExecutor reference, as I showed in my example. 

The purpose of this PR is to allow to create a custom implementation of the pre-processor outside this repository, so in a crate that does not have access to the internal fields of `XcmExecutor`. That's why I moved the VM state into a new structure, an alternative would be to make the XcmExecutor fields publics, but it seemed less appropriate, but I can do so.

> What is not clear to me is whether it is wise to allow _additional_ state to be referenced

In the case of Moonbeam for example, we need to add our own state, it's the main goal of this PR, if you don't want to allow that, we will close this PR and maintain our own fork.

**Comment by KiChjang** [comment]
Since there has not been too much code movement on this lately, I suggest that we reopen this PR in the https://github.com/paritytech/xcm repository once it's ready. Closing for now.

**Pull request closed without merging**
