### PR TITLE
Companion for #14265

### PR DESCRIPTION
**Pull request by lexnv**
Companion for https://github.com/paritytech/substrate/pull/14265

cumulus companion: https://github.com/paritytech/cumulus/pull/2655

// @paritytech/subxt-team

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2917106

**Review by niklasad1 — APPROVED** [review]

**Review by jsdw — APPROVED** [review]

**Comment by lexnv** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2921394

**Comment by lexnv** [comment]
bot merge

**Pull request merged**
