### PR TITLE
Updated docker documentation.

### PR DESCRIPTION
**Pull request by legacycode**
The path /data is not correct for the docker bind mount. It should be /polkadot. I updated the documentation and added some examples, i am using for testing node. There is also an outdated docker documentation docker/readme-docker.adoc that should be deleted to avoid misunderstanding.

I would also suggest moving this documentation to the [docker wiki](https://wiki.polkadot.network/docs/en/maintain-sync#using-docker) and update the wiki as well. I can do that, if you are interested.

### CODE REVIEW

**Comment by bkchr** [comment]
Ping @s3krit

**Review by TriplEight — APPROVED** [review]
Thanks for your contribution! Looks very good!

**Comment by bkchr** [comment]
@legacycode could you please merge master?

**Comment by TriplEight** [comment]
I think it makes sense to put parts of it to the "maintain" part of the Polkadot doc

**Comment by legacycode** [comment]
> @legacycode could you please merge master?

done

**Comment by bkchr** [comment]
Ty

bot merge

**Comment by s3krit** [comment]
bot merge

**Pull request merged**
