### PR TITLE
Unlimited Proof size per block

### PR DESCRIPTION
**Pull request by ggwpez**
This change is needed for https://github.com/paritytech/substrate/pull/12383. The companion CI did not catch the test failure in the runtime integrity checks. You can see it failing over here https://github.com/paritytech/polkadot/pull/6061.  
```pre
tests::remove_keys_weight_is_sensible stdout ----
thread 'tests::remove_keys_weight_is_sensible' panicked at 'Builder finished with `build_or_panic`; The panic is expected if runtime weights are not correct: ValidationErrors { has_errors: true, errors: ["[DispatchClass::Normal] Weight { ref_time: 1500000000000, proof_size: 0 } (total) has to be greater than Weight { ref_time: 6192341000, proof_size: 0 } (base block) & Weight { ref_time: 86309000, proof_size: 0 } (base extrinsic)", "[DispatchClass::Normal] Some(Weight { ref_time: 1479913691000, proof_size: 0 }) (max_extrinsic) must not be 0. Check base cost and average initialization cost.", "[DispatchClass::Normal] Weight { ref_time: 2000000000000, proof_size: 0 } (max block) must fit at least one extrinsic Weight { ref_time: 6278650000, proof_size: 0 } (base weight)", "[DispatchClass::Operational] Weight { ref_time: 2000000000000, proof_size: 0 } (total) has to be greater than Weight { ref_time: 6192341000, proof_size: 0 } (base block) & Weight { ref_time: 86309000, proof_size: 0 } (base extrinsic)", "[DispatchClass::Operational] Some(Weight { ref_time: 1979913691000, proof_size: 0 }) (max_extrinsic) must not be 0. Check base cost and average initialization cost.", "[DispatchClass::Operational] Weight { ref_time: 500000000000, proof_size: 0 } (reserved) has to be greater than Weight { ref_time: 86309000, proof_size: 0 } (base extrinsic) if set", "[DispatchClass::Operational] Weight { ref_time: 2000000000000, proof_size: 0 } (max block) must fit at least one extrinsic Weight { ref_time: 6278650000, proof_size: 0 } (base weight)", "[DispatchClass::Mandatory] Weight { ref_time: 2000000000000, proof_size: 0 } (max block) must fit at least one extrinsic Weight { ref_time: 6278650000, proof_size: 0 } (base weight)"] }', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/952030c/frame/system/src/limits.rs:436:22
```

Changes:
- Set the proof block limit to `u64::MAX`. This affects all runtimes.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by BustaNit — APPROVED** [review]

**Review by ordian — APPROVED** [review]

**Comment by ordian** [comment]
you probably need `cargo update -p sp-io --precise "61b9a4d1a8a9bf39c1d89a8dd02f82785c10860c"` to fix the build

**Comment by KiChjang** [comment]
Changes are being rolled into #6061, closing here.

**Comment by ggwpez** [comment]
>Changes are being rolled into https://github.com/paritytech/polkadot/pull/6061, closing here.

Huh this change actually never made it in. Instead it now uses `MAX_POV_SIZE` which is set to 5 MiB…

**Comment by bkchr** [comment]
So let's reopen it?

**Review by gavofyork — APPROVED** [review]

**Comment by ggwpez** [comment]
Blocked until the CI error is resolved by https://github.com/paritytech/polkadot/pull/6500

**Pull request merged**
