### PR TITLE
[BACKPORT] backport changes for v0.9.13

### PR DESCRIPTION
**Pull request by drahnr**
Contains:

#4028
#4334
#4349
#4305
#4304
#4364

These changes assume #4254 is **not** present!

CC @Lldenaurois

skip check-dependent-cumulus

### CODE REVIEW

**Comment by ordian** [comment]
wrong target branch?

**Comment by drahnr** [comment]
> wrong target branch?

Fixed, thanks!

**Review by ordian — APPROVED** [review]
Does what it says on the tin.

**Comment by ordian** [comment]
Do we want https://github.com/paritytech/polkadot/pull/4172 as well once it's merged?

**Comment by ordian** [comment]
Waiting for results from testing on Rococo before merging.

**Pull request merged**
