### PR TITLE
Add a `last change` footer to the implementers guide

### PR DESCRIPTION
**Pull request by m-cat**
# PULL REQUEST

## Overview

Some of the newcomers were noticing outdated pages in the implementer's guide. This idea came up as a heuristic for how up-to-date an individual page is.

Credit: @alexgparity @eskimor 

## Visual Changes

Screen Shot 2022-10-30 at 15 21 22

### CODE REVIEW

**Review by eskimor — APPROVED** [review]

**Comment by eskimor** [comment]
Awwwesome, thank you!

**Review by alexgparity — APPROVED** [review]
:rocket:

**Comment by m-cat** [comment]
`mdbook-last-changed` has been published to crates.io (see https://github.com/badboy/mdbook-last-changed/issues/1), updated the installation step.

**Review by alvicsam — APPROVED** [review]

**Comment by eskimor** [comment]
Hei @sergejparity - could we have a review from you please? Thank you!

**Review by sergejparity — APPROVED** [review]

**Comment by eskimor** [comment]
Thank you!

**Pull request merged**
