### PR TITLE
Fix XCM encoding in HRMP pallet.

### LINKED ISSUE #2490: HRMP channel setup results 'xcmHandler.BadFormat' event in collators
Looks like collators cannot decode HRMP channel notifications message.

### PR DESCRIPTION
**Pull request by shaunxw**
Fixes #2490

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Review by bkchr — APPROVED** [review]
Could you add some test for this?

**Review by pepyakin — APPROVED** [review]
Oh right, this is better

I am not sure what kind of test we can have here: a test that checks what bytes these dispatchables enqueue doesn't seem super useful: it won't allow us to catch any issues.

**Comment by shaunxw** [comment]
We might need integration tests for this, and further more to cover HRMP/UMP/DMP sending and handling, between rococo and parachain.

If versioned XCM encode/decode is shared knowledge for all message passing modules (which I'm not sure if it's a protocol level thing), HRMP module could assume that these bytes must be at versioned encoded. Then adding versioned decoding works assertion in unit tests could help.

**Comment by shawntabrizi** [comment]
Yes integration tests are on the TODO list which does the end to end for a bunch of XCM+P scenarios

**Pull request merged**
