### PR TITLE
Companion for substrate#13335

### PR DESCRIPTION
**Pull request by dmitry-markin**
Companion for https://github.com/paritytech/substrate/pull/13335

Best-effort build fix.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2416676

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2416728

**Review by andresilva — APPROVED** [review]

**Review by skunert — APPROVED** [review]

**Comment by andresilva** [comment]
bot merge force

**Comment by andresilva** [comment]
Fixed in https://github.com/paritytech/polkadot/pull/6747.

**Pull request closed without merging**
