### PR TITLE
Companion for substrate/pull/8596

### PR DESCRIPTION
**Pull request by kianenigma**
Companion for https://github.com/paritytech/substrate/pull/8596

Note that I can't run the benchmark on this PR. For now let's use the `()` and once this is merged I make another PR (although, we run all benchmarks before each release anyhow)

### CODE REVIEW

**Review by thiolliere — APPROVED** [review]

**Review by shawntabrizi — APPROVED** [review]

**Comment by kianenigma** [comment]
The error 

```
0: �[91mOther: can only use subcommand with --chain [polkadot-dev, kusama-dev, westend-dev], got dev�[0m
```

Is related to my recent PR https://github.com/paritytech/polkadot/pull/2771. I have to prepare a patch for this and in the meantime we cannot run the benchmarks here apparently.

**Comment by kianenigma** [comment]
bot merge

**Comment by kianenigma** [comment]
Simnet job is failing, since I am certain the PR is unrelated will merge manually to keep master working.

**Pull request merged**
