### PR TITLE
Companion PR for substrate#6676

### PR DESCRIPTION
**Pull request by tomaka**
https://github.com/paritytech/substrate/pull/6676

### CODE REVIEW

**Comment by tomaka** [comment]
I've just closed this to prevent the bot from merging it, in order to not update Substrate right before 0.8.16.
If you update Substrate in Polkadot, the one change that is needed for it to compile is to also do `cargo update -p libp2p-core`.

**Comment by sjeohp** [comment]
You can also `bot merge cancel` FYI

**Comment by tomaka** [comment]
bot merge cancel

**Comment by tomaka** [comment]
As long as this PR isn't merge, all the Polkadot companion CI checks in Substrate fail.

But I've just realized that the Substrate bump that this PR does only brings two insubstantial commits: https://github.com/paritytech/substrate/commit/26a64d2332eb5f5313e16fd707b3e4ca90d64867 and https://github.com/paritytech/substrate/commit/5c43b2bebb331ebeaac5b6e21778203b1c73aa83.

Therefore it's probably ok to merge this.

**Comment by tomaka** [comment]
bot merge

**Pull request merged**
