### PR TITLE
Weights for new referenda/democracy extrinsics

### PR DESCRIPTION
**Pull request by muharem**
Weights copied from substrate

companion for https://github.com/paritytech/substrate/pull/12568

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2327588

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2327679

**Review by coderobe — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]

**Comment by muharem** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2358579

**Comment by muharem** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2364887

**Comment by muharem** [comment]
bot rebase

**Comment by muharem** [comment]
bot rebase

**Comment by muharem** [comment]
bot merge

**Pull request merged**
