### PR TITLE
Change pallet naming in test-runtime

### PR DESCRIPTION
**Pull request by bkchr**
This is required to make the `well_know_keys::ACTIVE_CONFIG` match the
`ActiveConfig` key.

### CODE REVIEW

**Comment by pepyakin** [comment]
Oh, I am not familiar with this `integrity_test`, I will look into the docs. But you are aware that there is a test for that in this module?

**Comment by bkchr** [comment]
Yeah I know and that didn't catch this :P 

We changed this to `FRAME V2` and this means the prefix of the storage item is derived from the name of the pallet in the runtime. So, the prefix isn't static anymore.

The `integrity_test` basically boils down to some `test` that is generated in the runtime to check for certain stuff.

**Comment by pepyakin** [comment]
Meaning that this replaces the test? If so, could you please remove it? Or is it still valuable?

**Comment by bkchr** [comment]
It still tests if the stuff decodes and contains the expected values. I would still see this somewhat useful.

**Comment by bkchr** [comment]
But I also can remove it.

**Comment by bkchr** [comment]
(It still ensures that the type of `ActiveConfig` doesn't change)

**Comment by shawntabrizi** [comment]
I talked to @pepyakin yesterday about this, and mentioned it would make sense to me for this to be a custom key from end to end, rather than a pallet storage item (which can be changed from frame version to frame version)

**Review by shawntabrizi — APPROVED** [review]

**Comment by bkchr** [comment]
> I talked to @pepyakin yesterday about this, and mentioned it would make sense to me for this to be a custom key from end to end, rather than a pallet storage item (which can be changed from frame version to frame version)

I'm clearly not happy with the status, but it is the easiest solution for now. In the future we really need to have some better utility for parachains to make use of this. As outlined here https://github.com/paritytech/cumulus/issues/320#issuecomment-775188888 by @pepyakin

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
