### PR TITLE
Fix `erasure_fetch_drop_also_drops_gossip_sender` test

### PR DESCRIPTION
**Pull request by bkchr**

### CODE REVIEW

**Comment by bkchr** [comment]
Okay no :( After running the tests for 5 minutes in a loop, it still get stuck.

**Comment by expenses** [comment]
:grimacing:

**Comment by bkchr** [comment]
Given this comment here: https://github.com/paritytech/polkadot/issues/1474#issuecomment-664414175

I just removed the test.

**Comment by expenses** [comment]
Seems reasonable :+1:

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
