### PR TITLE
Make `ParachainContext` take self as mutable

### PR DESCRIPTION
**Pull request by bkchr**
This replicates changes to `Environment`/`Proposer` that are used
internally at Cumulus.

### CODE REVIEW

**Comment by rphmeier** [comment]
what happened here?

**Comment by bkchr** [comment]
Realized that I don't need it :D Could still be done, but yeah, not sure.

**Comment by bkchr** [comment]
I thought again about it and think a good Rust interface should expose the mutability.

**Comment by rphmeier** [comment]
> I thought again about it and think a good Rust interface should expose the mutability.

Why is that? what sort of mutability is implicitly required for producing a candidate?

**Comment by bkchr** [comment]
The trait `Environment` (which should actually be called `ProposerFactory`), requires `&mut self` itself. That is the reason I discovered this, as before the factory was just an arc. Now, it is a `Arc<Mutex<dyn Environment>>`. So, I don't need really need the `&mut self` as I have the Mutex, but it is more clean to me.

**Comment by rphmeier** [comment]
OK, fair enough - i would expect that to disappear when we overhaul the block production pipeline to make more sense.

**Pull request merged**
