### PR TITLE
Change Auctions to Eight Lease Periods Per Slot

### PR DESCRIPTION
**Pull request by shawntabrizi**
This PR changes the Auctions and Crowdloan system to use a `SlotRange` which has 8 lease periods per slot.

Nothing philosophically changes in the behavior of these pallets, just more options.

### CODE REVIEW

**Review by rphmeier — APPROVED** [review]

**Comment by emostov** [comment]
Is there anyway I can either derive or query for `SlotRange::SLOT_RANGE_COUNT` offchain?  

I was thinking of using something like the equivalent of `Winning::<T>::get(offset).len()`, but if no bids have been made in the auction then it is `None`.

**Comment by jacogr** [comment]
I would suggest exposing the slot range as a constant - that way it is accessible externally (and even better, can be detected)

**Comment by shawntabrizi** [comment]
yup done :)

**Comment by rphmeier** [comment]
bot merge

**Review by jacogr — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
