### PR TITLE
Fix bin-substrate toml

### PR DESCRIPTION
**Pull request by liuchengxu**
Fix the complaint from the rust-analyzer.

```
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /home/xlc/src/github.com/paritytech/polkadot/bridges/relays/bin-sub
strate/Cargo.toml, cargo 1.55.0 (32da73ab1 2021-08-23): Failed to run `cargo metadata --manifest-path /home/xlc/src/github.com/paritytech/polkadot/bridges/relays/bin-substrate/ Cargo.toml` in `/home/xlc/src/github.com/paritytech/polkadot/bridges/relays/bin-substrate`: `cargo metadata` exited with an error: error: failed to parse manifest at `/home/xlc /src/github.com/paritytech/polkadot/bridges/relays/bin-substrate/Cargo.toml`

Caused by:
could not parse input as TOML

Caused by:
expected a table key, found a right brace at line 35 column 42
```

### CODE REVIEW

**Review by ordian — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@liuchengxu please merge master

**Comment by liuchengxu** [comment]
@bkchr It's already on top of the latest master :D.

**Comment by bkchr** [comment]
bot merge force

**Review by svyatonik — APPROVED** [review]

**Comment by svyatonik** [comment]
bot merge force

**Pull request merged**
