### PR TITLE
construct mmr leaf prior to session pallet hook

### PR DESCRIPTION
**Pull request by Lederstrumpf**
Addresses [substrate#11797](https://github.com/paritytech/substrate/issues/11797) by moving `pallet_mmr` ahead of `pallet_session`.
Effected change in the content of the leaf added by `block<N>`:
``` rust
MmrLeaf {
    version: <leaf-data-format-version>,
    (
        parent_num: <N-1>,
        parent_hash: <hash_of_<N-1>>,
    ),
    extra_data: <para_heads_of_<N-1>>,
-   next_auth_set: <next_auth_set_of<N>>,
+   next_auth_set: <next_auth_set_of<N-1>>,
}
```
Referring to `block<N-1>` in the leaf content consistently simplifies the interface for light client BEEFY consumers.
See https://hackmd.io/Ve-FPPAJSdeGNc3rc-FmrA for logs demonstrating the change.

### CODE REVIEW

**Review by acatangiu — APPROVED** [review]
:clap:

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2281859

**Review by serban300 — APPROVED** [review]

**Comment by acatangiu** [comment]
bot merge

**Comment by acatangiu** [comment]
I actually wanted to "bot rebase", then "bot merge", but muscle memory directly wrote "bot merge" and it went through 🙈

**Pull request merged**
