### PR TITLE
Companion for substrate#9711

### PR DESCRIPTION
**Pull request by koushiro**
Companion for paritytech/substrate#9711

migrate the `pallet-tips` storage prefix (Treasury ==> Tips).

### CODE REVIEW

**Review by thiolliere — APPROVED** [review]
looks good to me, I testest with try-runtime on polkadot and on kusama, and it was successful

**Comment by shawntabrizi** [comment]
This will need to be merged with the bounties migration PR

**Review by shawntabrizi — APPROVED** [review]

**Comment by thiolliere** [comment]
> This will need to be merged with the bounties migration PR

what do you mean ? I think both can be applied independently, I was thinking merging now

**Comment by shawntabrizi** [comment]
i just mean there will be merge conflicts

**Comment by shawntabrizi** [comment]
bot merge

**Comment by thiolliere** [comment]
bot merge

**Pull request merged**
