### PR TITLE
metrics: Increase the resolution of histogram metrics

### PR DESCRIPTION
**Pull request by alexggh**
These metrics are using the default histogram buckets:
```
pub const DEFAULT_BUCKETS: &[f64; 11] = &[
    0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0,
];

```

Which give us a resolution of 5ms, that's good, but there are some subsystems where we process hundreds or even a few thousands of messages per second like approval-voting or approval-distribution, so it makes sense to increse the resoution of the bucket to better understand if the procesisng is in the range of useconds.

The new bucket ranges will be:
```
[0.0001, 0.0004, 0.0016, 0.0064, 0.0256, 0.1024, 0.4096, 1.6384, 6.5536]
```

### CODE REVIEW

**Review by sandreim — APPROVED** [review]
Thanks @alexggh , this is indeed a good idea. Also it might also be worthy, but up to you, to have 2 additional buckets between the last 2:  `[0.0001, 0.0004, 0.0016, 0.0064, 0.0256, 0.1024, 0.4096, 1.6384, <here>, 6.5536,]`, just to give more granular info for any very high timings.

**Comment by alexggh** [comment]
> Thanks @alexggh , this is indeed a good idea. Also it might also be worthy, but up to you, to have 2 additional buckets between the last 2: `[0.0001, 0.0004, 0.0016, 0.0064, 0.0256, 0.1024, 0.4096, 1.6384, <here>, 6.5536,]`, just to give more granular info for any very high timings.

yes, makes sense, I won't be able to use the `exponential_buckets` helper function for that, so I'll define a static vec for that.

**Comment by alexggh** [comment]
> This happens when you aggregate metrics from nodes with different bucket configurations. I expect this to be fine. 
Yes, that's exactly what is happening .

> You should try to query the subset of nodes running your changes and select only the time period when only that bucket configuration is present. That should work.

Yes, that works.

**Review by bredamatt — APPROVED** [review]

**Comment by sandreim** [comment]
bot merge

**Review by vstakhov — APPROVED** [review]

**Comment by sandreim** [comment]
bot merge

**Pull request merged**
