### PR TITLE
Benchmarks for #6934

### PR DESCRIPTION
**Pull request by s0me0ne-unkn0wn**

### CODE REVIEW

**Comment by s0me0ne-unkn0wn** [comment]
/benchmark runtime polkadot runtime_parachains::configuration

**Comment by s0me0ne-unkn0wn** [comment]
bot bench $ runtime polkadot runtime_parachains::configuration

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2657157

**Comment by s0me0ne-unkn0wn** [comment]
bot bench $ runtime kusama runtime_parachains::configuration

**Comment by s0me0ne-unkn0wn** [comment]
bot bench $ runtime rococo runtime_parachains::configuration

**Comment by s0me0ne-unkn0wn** [comment]
bot bench $ runtime westend runtime_parachains::configuration

**Comment by s0me0ne-unkn0wn** [comment]
bot cancel

**Comment by s0me0ne-unkn0wn** [comment]
bot bench $ runtime kusama runtime_parachains::configuration

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2657654

**Comment by s0me0ne-unkn0wn** [comment]
bot bench $ runtime kusama runtime_parachains::configuration

**Comment by s0me0ne-unkn0wn** [comment]
bot bench $ runtime rococo runtime_parachains::configuration

**Comment by s0me0ne-unkn0wn** [comment]
bot bench $ runtime westend runtime_parachains::configuration

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2658009

**Pull request merged**
