### PR TITLE
[DNM] Try runtime testing release

### PR DESCRIPTION
**Pull request by ggwpez**
Manual try-runtime testing.

### CODE REVIEW

**Comment by ggwpez** [comment]
Works as expected.  
Polkadot: Green
Kusama: Green after deleting idempotent migrations
Westend: Red since already on 0.9.37

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2344942

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2346800

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2347012

**Pull request closed without merging**
