### PR TITLE
[DNM] try-runtime testing

### PR DESCRIPTION
**Pull request by ggwpez**
Testing https://github.com/paritytech/polkadot/pull/5729

### CODE REVIEW

**Comment by ggwpez** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=kusama-dev --execution=Wasm --no-spec-name-check on-runtime-upgrade live --uri wss://kusama-try-runtime-node.parity-chains.parity.io:443

**Comment by ggwpez** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=kusama-dev --execution=Wasm --no-spec-name-check on-runtime-upgrade live --uri wss://kusama-try-runtime-node.parity-chains.parity.io:443

**Comment by ggwpez** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=kusama-dev --execution=Wasm --no-spec-name-check on-runtime-upgrade live --uri wss://kusama-try-runtime-node.parity-chains.parity.io:443

**Comment by kianenigma** [comment]
does this not need to build against the companion? I recently learned the syntax for that: https://github.com/paritytech/pipeline-scripts/issues/63

**Comment by kianenigma** [comment]
ahh, I see that you are patching deps, no need to do that anymore, can just use the normal companion if you prefer :)

**Comment by ggwpez** [comment]
> ahh, I see that you are patching deps, no need to do that anymore, can just use the normal companion if you prefer :)

Yea I know that in general, thanks. Just in this case i dont want to mess up the companion branches and rather use a Dev branch to mess around.

**Comment by ggwpez** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=kusama-dev --execution=Wasm --no-spec-name-check on-runtime-upgrade live --uri wss://kusama-try-runtime-node.parity-chains.parity.io:443

**Comment by ggwpez** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=westend-dev --execution=Wasm --no-spec-name-check on-runtime-upgrade live --uri wss://kusama-try-runtime-node.parity-chains.parity.io:443

**Comment by ggwpez** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=westend-dev --execution=Wasm --no-spec-name-check on-runtime-upgrade live --uri wss://westend-try-runtime-node.parity-chains.parity.io:443

**Comment by ggwpez** [comment]
Continued in the MR itself.

**Comment by ggwpez** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=polkadot-dev --execution=Wasm --no-spec-name-check on-runtime-upgrade live --uri wss://polkadot-try-runtime-node.parity-chains.parity.io:443

**Comment by ggwpez** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=polkadot-dev --execution=Wasm --no-spec-check-panic on-runtime-upgrade live --uri wss://polkadot-try-runtime-node.parity-chains.parity.io:443

**Comment by jam206** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=polkadot-dev --execution=Wasm --no-spec-check-panic on-runtime-upgrade live --uri wss://polkadot-try-runtime-node.parity-chains.parity.io:443

**Comment by ggwpez** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=polkadot-dev --execution=Wasm --no-spec-check-panic on-runtime-upgrade live --uri wss://polkadot-try-runtime-node.parity-chains.parity.io:443

**Comment by kianenigma** [comment]
cc @niklasad1

**Comment by ggwpez** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=kusama-dev --execution=Wasm --no-spec-check-panic on-runtime-upgrade live --uri wss://kusama-try-runtime-node.parity-chains.parity.io:443

**Comment by ggwpez** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=polkadot-dev --execution=Wasm --no-spec-check-panic on-runtime-upgrade live --uri wss://polkadot-try-runtime-node.parity-chains.parity.io:443

**Comment by ggwpez** [comment]
Success :tada:

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2228486

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2228529

**Comment by ggwpez** [comment]
CI works again https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2228744

**Pull request closed without merging**
