### PR TITLE
Bump version, bump substrate & update benchmarks in preparation for v0.8.31

### PR DESCRIPTION
**Pull request by s3krit**

### CODE REVIEW

**Review by kianenigma — APPROVED** [review]
Had a quick look at polkadiff, def. need to see the new staking weights for 24 nominator situation, else all good.

**Comment by s3krit** [comment]
Cheers. @chevdor pointed out the extremely different benchmark for kill_identity ( https://github.com/paritytech/polkadot/pull/2938/files#diff-1dc46ada5024824f5c5f2c030fd6d081f6dc19f75dcd28fd424ec810a70aa11fL146 ), so I'm manually running it again.

**Review by chevdor — APPROVED** [review]
Beside spotting a few weight difference (which may not be an issue), I could build all fine locally and run `srtool` as well.

**Comment by s3krit** [comment]
> /benchmark runtime kusama pallet_staking

How do the results for this look? Good to go?

**Review by kianenigma — APPROVED** [review]
> @kianenigma
> How do the results for the staking benchmark look? Good to go?

all good.

**Pull request merged**
