### PR TITLE
Upgrade tokio to 1.22.0

### PR DESCRIPTION
**Pull request by dmitry-markin**
Companion for https://github.com/paritytech/substrate/pull/12646.

cumulus companion: https://github.com/paritytech/cumulus/pull/1917

## Follow-up issues

We still depend on async-std in the PVF subsystem. The issue to port it to tokio: https://github.com/paritytech/polkadot/issues/6353.

### CODE REVIEW

**Comment by ordian** [comment]
We have [some](https://github.com/search?q=repo%3Aparitytech%2Fpolkadot%20async_std&type=code) `async_std` usage mostly in PVF subsystem that we might want to replace as well @pepyakin ?

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2083290

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2091559

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2091600

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2091758

**Review by melekes — APPROVED** [review]
:+1:

**Review by altonen — APPROVED** [review]

**Comment by altonen** [comment]
I think you need to add cumulus companion to the PR description

**Review by acatangiu — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2113640

**Pull request merged**
