### PR TITLE
statement-distribution: do not use OurViewChange

### PR DESCRIPTION
**Pull request by ordian**
This would eliminate the data race between `OurViewChange` and `ActiveLeaves` signal and that's what most subsystem do to avoid this problem.

### CODE REVIEW

**Review by rphmeier — APPROVED** [review]

**Review by eskimor — COMMENTED** [review]
I think we have to fix this the other way round - getting rid of `ActiveLeavesUpdate`. The view updates are handled in the network bridge and we are sharing a peer set for precisely the purpose of keeping our view in sync with peers. @rphmeier  am I missing something?

**Comment by ordian** [comment]
> I think we have to fix this the other way round - getting rid of `ActiveLeavesUpdate`. The view updates are handled in the network bridge and we are sharing a peer set for precisely the purpose of keeping our view in sync with peers. @rphmeier am I missing something?

`OurViewChange` message should be based exactly on `ActiveLeavesUpdate` signal, and most subsystems are using it, also signals are handled before messages, so this will ensure some ordering. But I agree we could equally use one and get rid of another.

**Comment by eskimor** [comment]
Ok, if we assume signals are handled first, then this is probably fine for activated - but deactivated could remove us a head with still messages in flight - no?

**Comment by ordian** [comment]
> but deactivated could remove us a head with still messages in flight - no?

yes, but if a head is deactivated we don't want to handle these messages anyway
and this is also the case for `OurViewChange`, we use `retain` there, which is essentially the same

**Comment by rphmeier** [comment]
> but deactivated could remove us a head with still messages in flight - no?

Yes. What we could do is keep around old heads for a small amount of time

**Pull request merged**
