### PR TITLE
Remove Kusama Nomination Pools Init

### PR DESCRIPTION
**Pull request by joepetrowski**
Included in the runtime v9220 release, config setup is no longer needed.

I don't think `pallet_nomination_pools::migration::v1::MigrateToV1<Runtime>` is needed either but am not sure based on this thread https://github.com/paritytech/substrate/pull/11411/files#r872629403

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by shawntabrizi — APPROVED** [review]
lets also wait for kian

**Comment by kianenigma** [comment]
Migrating pools to V1 is already in the 9.23 release, "making pool roles optional". 

https://github.com/paritytech/polkadot/releases/tag/v0.9.23

**Review by kianenigma — APPROVED** [review]

**Comment by kianenigma** [comment]
would be nice if you clean the stale migrations from westend too.

**Comment by shawntabrizi** [comment]
bot rebase

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
