### PR TITLE
Companion PR for substrate#8625

### PR DESCRIPTION
**Pull request by tomaka**
https://github.com/paritytech/substrate/pull/8625

No change to the code, just stupid dependency things.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by tomaka** [comment]
CI fails because of https://github.com/paritytech/polkadot/pull/2895

**Comment by kianenigma** [comment]
> CI fails because of #2895

Will be merged soon.

**Review by kianenigma — APPROVED** [review]

**Comment by tomaka** [comment]
bot merge

**Comment by tomaka** [comment]
bot merge force

**Pull request merged**
