### PR TITLE
feat/jaeger: more spans, more stages

### LINKED ISSUE #2389: [metrics/jaeger] more candidate spans
We need more candidate spans to get a better ( statistical ) picture.

I would envision more candidate spans with child spans as needed, even scope based.

Rationale: This would allow us to get detailed data based on spans at which stage we lose candidates or they stall.

* [ ] we need additional candidate spans, possibly with children where anticipated
* [ ] additional tags for parentless/top-level candidate-spans to denote the stage in a numeric fashion `stage:0` to `stage:N` would be my suggestion to simplify life for tooling or pass an explicit mapping of candidate stages mapped from existing span names.

CC @coriolinus @insipx  @dvdplm

### PR DESCRIPTION
**Pull request by drahnr**
Additional spans and annotations for our internal candidate stage fallout tracking tooling

* [x] ~Stage numbers are still arbitrarily picked~
* [x] ~Figure out how to handle subsystems that participate in multiple stages~

Closes #2389 

CC @insipx @dvdplm

### CODE REVIEW

**Review by eskimor — APPROVED** [review]

**Comment by drahnr** [comment]
This also fixes bikeshedding debt. `JaegerSpan` becomes `jaeger::Span`.

**Review by ordian — APPROVED** [review]
:+1:

**Comment by drahnr** [comment]
bot merge

**Comment by drahnr** [comment]
bot merge

**Pull request merged**
