### PR TITLE
Tuning openGov parameters for Kusama (round 2)

### PR DESCRIPTION
**Pull request by adamsteeber**
This is in response to the changes requested in [PR 6398](https://github.com/paritytech/polkadot/pull/6398) (closed to resynchronize fork).

I'm actually quite glad Gavin requested an analysis of the changes since I found some major flaws in my initial configuration. After a good [risk analysis](https://docs.google.com/spreadsheets/d/1DHgjfaV0bvYVlsQswEM0EltuYnpYl7GJdg24H-sFpiM/edit?usp=sharing), I arrived at this configuration. I believe it's a good compromise for making things **faster** and **a bit more affordable** across the board. It also increases security by making enactment and confirmation periods longer in the more consequential tracks.

I hope these changes are found to be more robust, informed, and conscientious.

### CODE REVIEW

**Comment by adamsteeber** [comment]
Question: would the `maxQueued` constant need to be increase to the largest `max_deciding` parameter?

**Comment by adamsteeber** [comment]
Adherence to a lot of [PR 6416](https://github.com/paritytech/polkadot/pull/6416). Still think that:
- submission deposit should be at least 1 KSM
- spend limits need to be lower
- make the spending tracks' confirmation periods the same as treasurer.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2149844

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2156153

**Comment by adamsteeber** [comment]
Outdated PR

**Pull request closed without merging**
