### PR TITLE
Companion PR for ' Simplify a few chain components creation APIs related to the service'

### PR DESCRIPTION
**Pull request by expenses**
See https://github.com/paritytech/substrate/pull/6611

### CODE REVIEW

**Comment by tomaka** [comment]
If you modify the `Cargo.toml`s to point to your branch, then the bot will behave incorrectly when trying to merge it.

**Comment by expenses** [comment]
@tomaka I don't understand what you're saying. I'm going to revert the `Cargo.toml` changes after the substrate PR is merged.

**Comment by tomaka** [comment]
Substrate PRs are supposed to be merged by a bot now. If you ask the bot to merge a Substrate PR that has a companion PR, the bot then immediately and automatically does `cargo update -p sp-io` and merges the companion PR in question.

**Comment by expenses** [comment]
@tomaka Oh, okay.

**Comment by expenses** [comment]
I'm confused, these changes don't compile without the branch switch, so now the substrate `gitlab-check-polkadot-companion-build` is failing and I can't merge this.

**Comment by tomaka** [comment]
The CI didn't detect any companion PR: https://gitlab.parity.io/parity/substrate/-/jobs/586119/raw (search for "companion")
I think you have to indicate the companion in the PR description and not in a comment.

**Comment by expenses** [comment]
Just need an approval then ill merge

**Pull request merged**
