### PR TITLE
Companion for paritytech/substrate#12264

### PR DESCRIPTION
**Pull request by altonen**
Companion for paritytech/substrate#12264

cumulus companion: https://github.com/paritytech/cumulus/pull/1661

### CODE REVIEW

**Review by dmitry-markin — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]
Changes look good!

PR title and description still reference old PR instead of correct one: #12264

**Review by bkchr — APPROVED** [review]

**Comment by acatangiu** [comment]
bot rebase

**Review by alvicsam — APPROVED** [review]

**Review by sergejparity — APPROVED** [review]

**Comment by acatangiu** [comment]
bot merge

**Comment by acatangiu** [comment]
@altonen cumulus companion is not building properly: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/1882582

**Comment by altonen** [comment]
Is Cumulus not using the latest substrate automatically?

**Comment by altonen** [comment]
bot merge

**Pull request merged**
