### PR TITLE
polkadot companion: #13128 (Pools commission)

### PR DESCRIPTION
**Pull request by rossbulat**
This is a companion to introducing nomination pool commission: https://github.com/paritytech/substrate/pull/13128
- Adds additional weights for new calls
- Adds migration to the runtimes.
- Adds `InitialGlobalMaxCommission` const to `pallet_nomination_pools::Config`.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2129449

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2193633

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2194082

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2195578

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2197836

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2198259

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2199752

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2203215

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2204285

**Review by KiChjang — APPROVED** [review]

**Review by gpestana — APPROVED** [review]

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2205495

**Review by jsidorenko — APPROVED** [review]

**Comment by Ank4n** [comment]
@rossbulat Runtime-migration label was missing which meant it skips the migration jobs
https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2205490

**Review by ordian — APPROVED** [review]

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2212839

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2237469

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2254533

**Comment by rossbulat** [comment]
bot rebase

**Comment by rossbulat** [comment]
bot rebase

**Comment by rossbulat** [comment]
bot rebase && bot clean

**Comment by rossbulat** [comment]
bot rebase

**Comment by rossbulat** [comment]
bot clean

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2411374

**Comment by rossbulat** [comment]
bot rebase

**Comment by rossbulat** [comment]
bot fmt

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2442986

**Comment by rossbulat** [comment]
bot fmt

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2443428

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate= 13128 $ runtime polkadot-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime polkadot-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime polkadot-dev pallet_nomination_pools

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2447453

**Comment by rossbulat** [comment]
bot clean

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime polkadot-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime polkadot-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot rebase

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime polkadot-dev pallet_nomination_pools

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2448679

**Comment by rossbulat** [comment]
bot help

**Comment by rossbulat** [comment]
bot clean

**Comment by rossbulat** [comment]
bot rebase

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime polkadot-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime polkadot-dev pallet_nomination_pools

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2452343

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime kusama-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime westend-dev pallet_nomination_pools

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2452916

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2453327

**Comment by rossbulat** [comment]
bot clean

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2459235

**Comment by rossbulat** [comment]
bot rebase

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2465718

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime kusama-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime polkadot-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime westend-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime polkadot-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime kusama-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime westend-dev pallet_nomination_pools

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2465932

**Comment by rossbulat** [comment]
bot clean

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime polkadot-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2482978

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2486022

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime polkadot-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime kusama-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime westend-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot clean

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2486581

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime westend-dev pallet_nomination_pools

**Comment by rossbulat** [comment]
bot bench -v PATCH_substrate=13128 $ runtime kusama-dev pallet_nomination_pools

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2486881

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2487122

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2487444

**Comment by rossbulat** [comment]
bot fmt

**Comment by rossbulat** [comment]
bot clean

**Review by shawntabrizi — APPROVED** [review]

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2497573

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2501022

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2510336

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2512482

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2512591

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2515217

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2516885

**Comment by rossbulat** [comment]
bot clean

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2517772

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2518205

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2520337

**Comment by rossbulat** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2523702

**Comment by ggwpez** [comment]
bot rebase

**Comment by ggwpez** [comment]
bot rebase

**Comment by ggwpez** [comment]
bot clean  
bot merge

**Review by kianenigma — APPROVED** [review]

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
