### PR TITLE
Benchmark Disputes `force_unfreeze` extrinsic

### PR DESCRIPTION
**Pull request by emostov**
target pr: #3906
target branch: rh-unfreeze

### CODE REVIEW

**Comment by emostov** [comment]
/benchmark runtime custom --chain=rococo-dev --steps=50 --repeat=20 --pallet=runtime_parachains::disputes --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./runtime/parachains/src/disputes/weights.rs --header=./file_header.txt

**Comment by emostov** [comment]
/benchmark runtime custom --chain=rococo-dev --steps=50 --repeat=20 --pallet=runtime_parachains::disputes --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./runtime/parachains/src/disputes/weights.rs --header=./file_header.txt

**Comment by shawntabrizi** [comment]
Why are we using a custom output path here?

**Pull request merged**
