### PR TITLE
runtime/polkadot: enable disputes rewards and slashing

### PR DESCRIPTION
**Pull request by ordian**
Same as #5974, but for polkadot.

Slashing is only for "ForInvalid" disputes, which we haven't seen yet.

### CODE REVIEW

**Comment by ordian** [comment]
bot bench $ runtime polkadot runtime_parachains::disputes::slashing

**Comment by ordian** [comment]
bot bench $ runtime polkadot runtime_parachains::disputes::slashing

**Review by BradleyOlson64 — APPROVED** [review]
I see nothing amiss 👍

**Review by eskimor — APPROVED** [review]

**Review by tdimitrov — APPROVED** [review]

**Review by coderobe — APPROVED** [review]

**Comment by ordian** [comment]
bot merge

**Pull request merged**
