### PR TITLE
Companion for update `wasm-opt`

### PR DESCRIPTION
**Pull request by athei**
https://github.com/paritytech/substrate/pull/12280

### CODE REVIEW

**Review by koute — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]

**Comment by athei** [comment]
Can't reproduce the test failure locally. Seems pretty random. Probably related to the minor/fix version bumps of `thiserror` and `anyhow`?

**Comment by koute** [comment]
Maybe. Or maybe it's a bog standard random failure, which sometimes happens. Let's try to restart it and see if it fails again.

**Comment by ordian** [comment]
If this is about zombienet failure, #6215 should help.

**Comment by athei** [comment]
I force merged because it  is a circular fail with https://github.com/paritytech/polkadot/pull/6215

**Pull request merged**
