### PR TITLE
companion for substrate#14423

### PR DESCRIPTION
**Pull request by andresilva**

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3158465

**Review by bkchr — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3205198

**Review by ggwpez — APPROVED** [review]
Marking this as companion to resolve merge dead-lock: https://github.com/paritytech/cumulus/pull/2876

**Review by ggwpez — APPROVED** [review]
Marking this as companion to resolve merge dead-lock: https://github.com/paritytech/cumulus/pull/2876

**Comment by andresilva** [comment]
I could replicate the failure locally. Seems related to this: https://github.com/paritytech/substrate/pull/14575

**Comment by ggwpez** [comment]
> I could replicate the failure locally. Seems related to this: [paritytech/substrate#14575](https://github.com/paritytech/substrate/pull/14575)

Damn, yes it failed three times in CI now as well https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3206771 @atenjin

**Comment by bkchr** [comment]
bot merge force

**Pull request merged**
