### PR TITLE
Companion for Weight v1.5 Follow Up

### PR DESCRIPTION
**Pull request by shawntabrizi**
Substrate: https://github.com/paritytech/substrate/pull/12155

cumulus companion: https://github.com/paritytech/cumulus/pull/1584

### CODE REVIEW

**Comment by ruseinov** [comment]
The benchmark template is still old, that will break build when regenerated.

**Comment by ruseinov** [comment]
@shawntabrizi you can get the updated template here: https://github.com/paritytech/cumulus/pull/1454/commits/0eab44119dbee9d84a23a4330810a5288952319c

**Review by kianenigma — APPROVED** [review]

**Review by muharem — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
