### PR TITLE
Make debug builds more useful & testing faster.

### PR DESCRIPTION
**Pull request by eskimor**
Stolen from substrate.

cargo test -p polkadot-node-core-dispute-coordinator on master:

real    0m14.035s
user    1m49.101s
sys     0m0.235s

cargo test -p polkadot-node-core-dispute-coordinator on this branch:

real    0m7.644s
user    0m55.235s
sys     0m0.213s

Ran it a few times, values vary quite a bit, but a significant speedup is evident.

### CODE REVIEW

**Comment by ordian** [comment]
I'd suggest including a few more deps like in https://github.com/paritytech/polkadot/pull/3344/files.

**Review by gilescope — APPROVED** [review]

**Comment by eskimor** [comment]
@ordian Why did we close it back then?

**Comment by ordian** [comment]
> @ordian Why did we close it back then?

https://github.com/paritytech/polkadot/pull/3344#issuecomment-866780012
It was meant as an attempt to improve CI speeds, but it turned out that compiling release + running in release is roughly the same as compiling in debug + running in debug (with this patch).

**Comment by eskimor** [comment]
Ok, I haven't measured compilation speed - that might still be true. But we do cache compilation results these days - right?

**Comment by ordian** [comment]
> But we do cache compilation results these days - right?

We also did it back then. However, I don't know how effective our sccache-based caching is.
I believe there're larger gains to be made by restructuring the code and relying less on generics.

**Comment by bkchr** [comment]
> But we do cache compilation results these days - right?

We don't do.

**Comment by eskimor** [comment]
Still, number of tests are only ever getting more, while the number of dependencies that are compiled with optimizations is more or less stable. So I would vote for merging this, it should be net beneficial.

**Comment by eskimor** [comment]
@drahnr I'd suggest: Let's merge this?

**Comment by drahnr** [comment]
No strong opinion here, if it's a net zero for compile and run in CI but improves the local dev workflow, let's merge it.

If there are any additional dependencies that we want to have the optimized versions instead of the regular, we can iterate on those later on

**Review by drahnr — APPROVED** [review]

**Pull request merged**
