### PR TITLE
release v0.9.10 pr set1

### PR DESCRIPTION
**Pull request by chevdor**
| Done | PR    |    ref    |  Author  | Merge Date      | Notes|
| ---- | ----- | :-------: | :------: | --------------- |- |
| ✅   | #2815 |  8f0a57a  |   Gav    | 6.8.2021        ||
| ✅   | #3586 | 659911f69 |  shawn   | 7.8.2021 21:29  ||
| ✅   | #3591 | 292ba8a77 |   Gav    | 7.8.2021 22:19  ||
| ✅   | #3597 | 739b882f2 |  shawn   | 9.8.2021 12:28 | |
| ✅   | #3602 |  adfc160  |   Gav    | 9.8.2021 13:09  ||
| ✅   | #3404 | 0f5e37ce4 | KiChjang | 9.8.2021 20:55  ||
| ✅   | #3617 |  b61f4ff  |   Gav    | 11.8.2021   14:40:10    ||
| ✅   | #3594 |  a8ae70a9d |   kian   | 11.8.2021 20:24:13     | |
| ✅   | #3621 |  686e318  |   kian   | 12.8.2021 01:08:16     | |
| ✅   | #3640 |  5dd368a  |   Gav    | 16.8.2021    |   |
| ✅   | #3628 |  39f7be4  |   kian   | 16.8.2021      | |
| ✅   | #3537 |3a71a0780 | apopiak | 2021-08-18 01:39:47 | |
| ✅   | #3601 | f3f83e3 | shaunxw | 18.08.21 2:02 ||
| ✅   | #3657 |  7d80dbf3b | G. Thiolliere | 2021-08-18 16:30:32 | |
| ✅   | #3635  | a2a4cba | KiChjang | 19.8.2021 11:24  ||
| ✅   | #3661 |  f0acee3  | eskimor  | 19.8.2021   17:03  |  |
| ✅   | #3690 | c954bfc70 | KiChjang | 23.8.2021 12:37 ||
| ✅   | #3693 |  30a6c7f  |   Gav    | 23.8.2021 19:53 ||
| ✅   | #3681 |  eba8d2c  | eskimor  | 24.8.2021       ||
| ⃕       | ~#3711~ | ~8fab1d8~  | ~eskimor~ | ~27.8.2021~   |    |
| ⃕       | ~#3730~ |  ~54d1cb9~  | ~KiChjang~ |  ~28.8.2021~  |    |
| ✅   | #3766 |  direct PR  | Gav |  n/a      ||
| ✅   | #3624 | 117466aa8 | Eskimor | n/a | checked with @eskimor ✅ |
| ✅  | #3731  |  99c52e4a6  | thiolliere |  2021-09-07 12:19+2:00 ||
| ✅  | #3784 | c0a3e56b5 | Gav | 2021-09-08 19:57:26+02:00 ||
| ✅  | #3575 | f33ecdb | pepyakin | 2021-09-15 11:13:44+02:00 | May require #3543 |

### CODE REVIEW

**Comment by xlc** [comment]
Can we please have #3601 included. This is blocking issue preventing para-to-para token transfer.

**Comment by chevdor** [comment]
@xlc I take it in the list to test, it will make it into this version depending on how well it merges within the context of this release.

**Comment by GopherJ** [comment]
Does this mean #3629 will land in v0.9.11 instead?

**Comment by eskimor** [comment]
We can skip #3711 on this one - it is not super urgent and it merged master, so cherry-picking it does not work as anticipated.

**Comment by chevdor** [comment]
Waiting for [this PR](https://github.com/paritytech/grandpa-bridge-gadget/pull/289) to update the deps.

**Comment by chevdor** [comment]
https://github.com/paritytech/substrate/pull/9442 is required by https://github.com/paritytech/polkadot/pull/3628

See https://github.com/paritytech/substrate/pull/9767

**Pull request merged**
