### PR TITLE
Companion for better way to resolve `Phase::Emergency` via governance #10663

### PR DESCRIPTION
**Pull request by georgesdib**
Companion to paritytech/substrate#10663

Adding `GovernanceFallback` after changes in substrate in the accompanying PR.

### CODE REVIEW

**Review by kianenigma — APPROVED** [review]

**Review by bkchr — APPROVED** [review]
Approving it for @kianenigma 

But I still find it weird that we set the `GovernanceFallback` to what it should be set for test nets :D

**Comment by kianenigma** [comment]
yeah, sorry, I should've known that this companion model would fail :(

**Comment by kianenigma** [comment]
@georgesdib can you give me and Basti access to your fork so either of us can update and merge this?

**Comment by georgesdib** [comment]
> @georgesdib can you give me and Basti access to your fork so either of us can update and merge this? 

Done, sorry about this, what is the error though?

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
