### PR TITLE
Companion for substrate#13771

### PR DESCRIPTION
**Pull request by muharem**
cumulus companion: https://github.com/paritytech/cumulus/pull/2410

companion for https://github.com/paritytech/substrate/pull/13771

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2622045

**Review by bkchr — APPROVED** [review]

**Comment by muharem** [comment]
@ordian @kianenigma can you please support with review here?

**Review by eskimor — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]

**Review by sam0x17 — APPROVED** [review]

**Comment by muharem** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2700020

**Comment by muharem** [comment]
bot merge

**Pull request merged**
