### PR TITLE
Companion for  #10356: Preimage registrar and Scheduler integration

### PR DESCRIPTION
**Pull request by gavofyork**
Just adds the new Preimage pallet into the 4 runtimes and includes a migration for Scheduler pallet.

TODO:

- [x] Enable runtime migration

### CODE REVIEW

**Comment by gavofyork** [comment]
/benchmark runtime pallet kusama pallet_xcm_benchmarks::generic

**Review by shawntabrizi — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Pull request merged**
