### PR TITLE
Companion for Substrate#14373

### PR DESCRIPTION
**Pull request by drskalman**
Companion for https://github.com/paritytech/substrate/pull/14373

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3295461

**Comment by davxy** [comment]
Please see https://github.com/w3f/polkadot-1/pull/1

**Review by davxy — CHANGES_REQUESTED** [review]
Please see https://github.com/w3f/polkadot-1/pull/1

**Review by davxy — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3304560

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3307998

**Comment by drskalman** [comment]
Closing because was replaced by #7572 due to github permission issue

**Pull request closed without merging**
