### PR TITLE
Add more granularity to prometheus histogram buckets

### PR DESCRIPTION
**Pull request by bredamatt**
Adjusts histogram bucket ranges for the following prometheus metrics:

* polkadot_parachain_av_store_get_chunk (majority falls within 0-5ms bucket)
* polkadot_parachain_time_unify_with_peer (majority falls within 0-5ms bucket)
* polkadot_parachain_bitfield_signing_run (majority falls within 0-5ms bucket)

As seen here for example:

Screenshot 2022-11-25 at 16 51 02

By adding a few more buckets, we can become a bit more aware of the distribution of values.

### CODE REVIEW

**Review by m-cat — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2088000

**Comment by vstakhov** [comment]
Maybe it is better to move these and (this)[https://github.com/paritytech/polkadot/blob/master/node/network/statement-distribution/src/metrics.rs#L20] constants somewhere to access them uniformly?

**Review by eskimor — APPROVED** [review]

**Comment by bredamatt** [comment]
bot merge

**Comment by bredamatt** [comment]
> Maybe it is better to move these and [this](https://github.com/paritytech/polkadot/blob/master/node/network/statement-distribution/src/metrics.rs#L20) constants somewhere to access them uniformly?

Agreed. Probably best to do so in a new PR that evaluates more thoroughly what those constants should look like as we get more insights with this (and other, similar) change(s).

**Comment by sandreim** [comment]
I would also consider reducing the number of buckets depending on their relevance as we observe them. These are not free and increasing the label cardinality leads to higher usage on the backend.

**Pull request merged**
