### PR TITLE
Update BEEFY+MMR integration.

### PR DESCRIPTION
**Pull request by tomusdrw**
This PR changes the way we construct merkle trees for parachains and BEEFY validator set.

Note that the pallet code that previously was part of `common/src/mmr.rs` is now part of BEEFY repository (https://github.com/paritytech/grandpa-bridge-gadget/pull/236)

### CODE REVIEW

**Comment by ordian** [comment]
@drahnr could please help fixing spellcheck https://gitlab.parity.io/parity/polkadot/-/jobs/1016684?

**Comment by drahnr** [comment]
> @drahnr could please help fixing spellcheck https://gitlab.parity.io/parity/polkadot/-/jobs/1016684?

Working on a spellcheck fixing manifest, WIP.

For the particular CI failures:

````
error: spellcheck(Hunspell)
    --> /builds/parity/polkadot/runtime/rococo/src/lib.rs:858
     |
[2021-07-15T15:11:30Z WARN  cargo_spellcheck::suggestion] Unable to get terminal size. Using default: 80
 858 |  See [MmrLeafVersion] type documentation for more details.
     |       ^^^^^^^^^^^^^^
     |   Possible spelling mistake found.
error: spellcheck(Hunspell)
    --> /builds/parity/polkadot/runtime/rococo/src/lib.rs:858
     |
[2021-07-15T15:11:30Z INFO  cargo_spellcheck::action] ❌ /builds/parity/polkadot/runtime/rococo/src/lib.rs : 2
 858 |  See [MmrLeafVersion] type documentation for more details.
     |       ^^^^^^^^^^^^^^
     |   Possible spelling mistake found.
     ```
     
     should become
     
     ```
     [`MmrLeafVersion`]
     ```

**Comment by tomusdrw** [comment]
CC @musnit @philipstanislaus

**Review by svyatonik — APPROVED** [review]

**Review by philipstanislaus — APPROVED** [review]
Nice, thanks 🙏

**Review by adoerr — APPROVED** [review]
LGTM. I did a smoke test with `rococo-local`.

**Pull request merged**
