### PR TITLE
companion substrate#13305

### PR DESCRIPTION
**Pull request by kianenigma**
[#13305](https://github.com/paritytech/substrate/pull/13305)

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2360552

**Review by bkchr — APPROVED** [review]

**Review by ordian — APPROVED** [review]

**Comment by kianenigma** [comment]
/cmd queue -c bench -v PATCH_substrate=13305 $ runtime polkadot-dev pallet-elections-phragmen

**Comment by kianenigma** [comment]
/cmd queue -c bench -v PATCH_substrate=13305 $ runtime kusama-dev pallet-elections-phragmen

**Review by ggwpez — APPROVED** [review]

**Comment by kianenigma** [comment]
bot rebase

**Comment by kianenigma** [comment]
/cmd queue -c bench -v PATCH_substrate=13305 $ runtime kusama-dev pallet-elections-phragmen

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2366703

**Pull request merged**
