### PR TITLE
Actually connect to new validators at session boundary.

### PR DESCRIPTION
**Pull request by eskimor**

### CODE REVIEW

**Review by andresilva — APPROVED** [review]

**Review by ordian — APPROVED** [review]
Uh, good catch!

**Comment by andresilva** [comment]
bot merge

**Comment by ordian** [comment]
bot merge

**Comment by andresilva** [comment]
Can we add tracing [here](https://github.com/paritytech/polkadot/blob/master/node/network/availability-distribution/src/pov_requester/mod.rs#L197) as well? Unless it's totally not relevant.

**Comment by ordian** [comment]
> Can we add tracing [here](https://github.com/paritytech/polkadot/blob/master/node/network/availability-distribution/src/pov_requester/mod.rs#L197) as well? Unless it's totally not relevant.

that's going to be removed in #3052, because it's a subset of what we're requesting in gossip-support, so it doesn't really provide a value

**Comment by andresilva** [comment]
Yeah, it's only the validators from our group.

**Pull request merged**
