### PR TITLE
Add benchmarks for XCM pallet version migration

### PR DESCRIPTION
**Pull request by KiChjang**

### CODE REVIEW

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime westend-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime kusama-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime rococo-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime polkadot-dev pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2165603

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime westend-dev pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2165694

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime westend-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime westend-dev pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2165785

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime westend-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime kusama-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime kusama-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime polkadot-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime westend-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime westend-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime westend-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime westend-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime westend-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime kusama-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime rococo-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime kusama-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime rococo-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime polkadot-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime polkadot-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime polkadot-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime polkadot-dev pallet_xcm

**Comment by KiChjang** [comment]
/cmd queue -c bench-bot $ runtime polkadot-dev pallet_xcm

**Pull request merged**
