### PR TITLE
[DNM] Feature/merge no gossip of approvals with assignments v2

### PR DESCRIPTION
**Pull request by alexggh**
## Ignore, not intended for review.

This is just a merge implementation of https://github.com/paritytech/polkadot/pull/6782 with https://github.com/paritytech/polkadot/pull/7482 to generate a docker image for testing in versi.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3223028

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3223477

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3228596

**Comment by alexggh** [comment]
On hold in favor of: https://github.com/paritytech/polkadot/issues/6831#issuecomment-1649649600

**Pull request closed without merging**
