### PR TITLE
Fix matrix rooms

### PR DESCRIPTION
**Pull request by chevdor**
This PR switches rooms/accounts from the legacy matrix server to the new one.
This PR introduces also matrices to allow sending notifications to several rooms as required.

## Todo
- [x] Switch to the new token(s)
~- [ ] ensure `POLKADOT_DEVOPS_MATRIX_ACCESS_TOKEN` is set and correct~ 
~- [ ] ensure the bot behind `POLKADOT_DEVOPS_MATRIX_ACCESS_TOKEN` is in the [Help Desk: Infrastructure (DevOps)](!IQAaaFnRIrFutzzaql:parity.io) room~
- [x] ensure `RELEASENOTES_MATRIX_V2_ACCESS_TOKEN` is set
- [x] find bot name behind `RELEASENOTES_MATRIX_V2_ACCESS_TOKEN`
- [x] ensure the bot behind `RELEASENOTES_MATRIX_V2_ACCESS_TOKEN` in the following rooms:
    - [x] [`RelEng: Polkadot Release Coordination`](!cqAmzdIcbOFwrdrubV:parity.io)
    - [x] `#KusamaValidatorLounge:polkadot.builders`
    - [x] `#kusama-announcements:matrix.parity.io`\
    - [x] `#polkadotvalidatorlounge:web3.foundation`
    - [x] `#polkadot-announcements:matrix.parity.io`
    - [x] `Ledger <> Polkadot Coordination`
- [x] rename `MATRIX_V2_ACCESS_TOKEN` into `RELEASENOTES_MATRIX_V2_ACCESS_TOKEN`
- [x] cleanup WHERE we send notifications
- [x] add notif to General: Rust, Polkadot, Substrate ([#engineering-general:parity.io](https://matrix.to/#/#engineering-general:parity.io))

## After merge

- [ ] delete any remaining secret such as `MATRIX_ACCESS_TOKEN`

cc @wpank @lazam @jam206

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2745112

**Review by coderobe — APPROVED** [review]

**Comment by chevdor** [comment]
Notification have failed since last month starting withe 0.9.41:
https://github.com/paritytech/polkadot/actions/workflows/release-99_bot.yml

**Review by lazam — APPROVED** [review]

**Comment by chevdor** [comment]
bot rebase

**Comment by chevdor** [comment]
bot merge

**Pull request merged**
