### PR TITLE
Fix fast-runtime

### PR DESCRIPTION
**Pull request by zjb0807**
There have `prod_or_fast` and `fast-runtime` feature, so revert #2167

### CODE REVIEW

**Comment by bkchr** [comment]
I don't see any reason why this should be done. This changes the behavior in quite some way.

**Comment by zjb0807** [comment]
> I don't see any reason why this should be done. This changes the behavior in quite some way.

https://github.com/paritytech/polkadot/blob/a13f0b96fa1838d5ef12e1b4f68b6ba911692281/runtime/rococo/constants/src/lib.rs#L40-L43

`prod_or_fast` was used here, but the `EpochDurationInBlocks` was modified in `chain_spec.rs`. It's going to be a little confusing

**Comment by zjb0807** [comment]
I need a stable rococo-local network to test para chain, `EPOCH_DURATION` is 1min and will cause `UnexpectedEpochChange`.

**Comment by bkchr** [comment]
> I need a stable rococo-local network to test para chain, `EPOCH_DURATION` is 1min and will cause `UnexpectedEpochChange`.

I never had problems with 1 minute epochs. However, your change here would also just lead to 1 minute epochs when you use fast. You clearly don't want to wait 1 hour until your Parachain is onboarded. With the current code, you can also change the epoch/session length in the chain spec.

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
