### PR TITLE
Add some metrics to dispute-coordinator.

### PR DESCRIPTION
**Pull request by eskimor**
It is still quite slow apparently. For now to be deployed on Versi - not sure we want to keep them yet.

### CODE REVIEW

**Review by sandreim — COMMENTED** [review]
We have quite a lot of metrics, and most of them are not really used when debugging. What do you think if we take a similar approach to logs, such that we can group them in sets, say debug metrics and prod metrics that we can enable via CLI ?

**Comment by eskimor** [comment]
Not sure it is worth the trouble, but an interesting idea!

**Comment by sandreim** [comment]
The main benefit would be lower scraping time and reducing the prometheus load which is a problem for large deployments.

**Comment by eskimor** [comment]
Ok requests are not costly nor frequent - I really cannot make any sense of those ToF values. Also when looking at logs: Everything is blazingly fast now - together with requests that trickle in once every few seconds. I am getting the feeling that something is off with that ToF metric, I am also not seeing any consequences: With an occasional ToF >0.5 seconds, the provisioner should actually time out - never happens as far as I can see.

**Comment by eskimor** [comment]
Screenshot from 2022-08-16 15-57-33
Screenshot from 2022-08-16 15-56-26
Screenshot from 2022-08-16 15-52-09
Screenshot from 2022-08-16 15-51-50

What does add up a little bit is importing those backing votes.

**Pull request closed without merging**
