### PR TITLE
Fix priority thresholds (backport #5375)

### PR DESCRIPTION
**Pull request by chevdor**
backport #5375 for v0.9.20

### CODE REVIEW

**Comment by coderobe** [comment]
Does this even require a backport? I think the github action uses the template off `master` anyway, no?

**Comment by chevdor** [comment]
@coderobe I have had issues in the past thinking that too. If we don't backport, be aware of the risk that we need a manual check.

**Review by coderobe — COMMENTED** [review]
We can see if the drafts change after the PR targeting master is merged (there will be another RC anyway due to migration woes) and then decide to merge or not to merge this one into the release branch

**Review by coderobe — APPROVED** [review]

**Comment by coderobe** [comment]
seems like master wasn't enough

**Pull request merged**
