### PR TITLE
Companion for upgrade of `pallet-mmr` to pallet macro

### PR DESCRIPTION
**Pull request by koushiro**
Companion for paritytech/substrate#9181

### CODE REVIEW

**Review by thiolliere — APPROVED** [review]

**Comment by thiolliere** [comment]
we can merge before the companion because this is just removing the mmr call variant, which was an empty enum.
after the companion such a change is mandatory, but right now the change also makes sense

**Comment by thiolliere** [comment]
bot merge

**Comment by thiolliere** [comment]
bot merge

**Review by KiChjang — APPROVED** [review]

**Comment by KiChjang** [comment]
bot merge

**Pull request merged**
