### PR TITLE
companion for #10231

### PR DESCRIPTION
**Pull request by thiolliere**
just apply the renames for https://github.com/paritytech/substrate/pull/10231
skip check-dependent-cumulus

### CODE REVIEW

**Review by kianenigma — APPROVED** [review]

**Review by emostov — APPROVED** [review]

**Comment by thiolliere** [comment]
bot merge

**Comment by thiolliere** [comment]
The change shouldn't change the runtime. As it only remove a feature which wasn't used. But I bump the spec version anyway to be safer.

**Comment by thiolliere** [comment]
bot merge

**Comment by thiolliere** [comment]
bot merge

**Pull request merged**
