### PR TITLE
add Encointer as TrustedTeleporter to Kusama

### PR DESCRIPTION
**Pull request by brenzi**
This PR prepares for the case where Encointer's proposal to be onboarded as a common good parachain will pass.

### CODE REVIEW

**Comment by brenzi** [comment]
@joepetrowski May I request your review? It's copy-paste from our previous PR #4213 for testnets

**Review by joepetrowski — APPROVED** [review]
Looks OK to me. Question is whether we:

1. Merge now and put it in the runtime before Encointer would onboard. If the referendum to add Encointer as a common good chain failed, we could remove it from the runtime later.
2. Only merge after Encointer gets accepted by Kusama referendum as a common good chain.

Will let others chime in on the two options.

**Comment by brenzi** [comment]
not sure what that CI error is about. Seems unrelated to this PR

**Comment by rrtti** [comment]
I would suggest to wait until the chain is registered in order to merge this. The team has requested for the common good slot motion to kick off from lease period 18.

**Comment by brenzi** [comment]
Now that Encointer has been ratified to become a common good parachain on Kusama, can we merge this for the next runtime upgrade?

**Review by joepetrowski — COMMENTED** [review]
LGTM. @KiChjang ?

**Review by KiChjang — APPROVED** [review]
Double-checked the ParaId for Encointer just now; everything checks out.

**Pull request merged**
