### PR TITLE
*: Update authority discovery and remove WorkerConfig

### PR DESCRIPTION
**Pull request by mxinden**
With https://github.com/paritytech/substrate/pull/7545 the authority
discovery module queries and publishes addresses on an exponentially
increasing interval. Doing so should make custom configurations
obsolete, as operations are retried in a timely fashion in the first
minutes.

This is a companion for https://github.com/paritytech/substrate/pull/7545.

### CODE REVIEW

**Comment by mxinden** [comment]
When reviewing, please ignore 0785943a1e377454f088814ef20f4432de09da7a which needs to be reverted before merging.

**Comment by mxinden** [comment]
@bkchr @ordian would you mind giving this pull request a review?

**Review by ordian — APPROVED** [review]
This looks good as a companion. And I don't have a strong opinion whether the `WorkerConfig` should be exposed or not as @bkchr.

**Comment by mxinden** [comment]
> And I don't have a strong opinion whether the WorkerConfig should be exposed or not as @bkchr.

Am I correctly interpreting your silence as approval @bkchr?

**Comment by ordian** [comment]
@mxinden could you please resolve merge conflicts?

**Comment by mxinden** [comment]
I reverted the commit pushed by the bot (https://github.com/paritytech/polkadot/pull/1953/commits/377b221e1853b2c383f0c416d686535b545796cb), merged `master` and ran `cargo update -p sp-io`.

@ordian is that the right approach here?

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
