### PR TITLE
Update Rococo chainspec to v2_2

### PR DESCRIPTION
**Pull request by PierreBesson**
Current Rococo chainspec is always available for download at: https://paritytech.github.io/chainspecs/rococo/relaychain/chainspec.json

This PR updates the version shipped with the polkadot binary.

### CODE REVIEW

**Review by coderobe — APPROVED** [review]

**Review by chevdor — APPROVED** [review]

**Review by bkchr — DISMISSED** [review]
This is wrong. You need to replace `node/service/res/rococo.json`.

**Review by riusricardo — COMMENTED** [review]
Just tested and it works well. As Basti pointed out, the name should be **rococo.json**

**Comment by PierreBesson** [comment]
> This is wrong. You need to replace `node/service/res/rococo.json`.

You are right. Sorry for the bad name. I just pushed a fix

**Review by riusricardo — APPROVED** [review]

**Comment by riusricardo** [comment]
bot merge

**Review by bkchr — APPROVED** [review]

**Pull request merged**
