### PR TITLE
[Companion] Allow StakingAdmin to set min_commission

### PR DESCRIPTION
**Pull request by Ank4n**
Related to https://github.com/paritytech/substrate/issues/12930.
Companion to https://github.com/paritytech/substrate/pull/13018.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2163285

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2163794

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2170985

**Comment by Ank4n** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2196848

**Comment by Ank4n** [comment]
/cmd queue -v PATCH_substrate=13018 -c bench-bot $ runtime westend-dev pallet_staking
/cmd queue -v PATCH_substrate=13018 -c bench-bot $ runtime kusama-dev pallet_staking
/cmd queue -v PATCH_substrate=13018 -c bench-bot $ runtime polkadot-dev pallet_staking

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2196892

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2196939

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2196986

**Comment by Ank4n** [comment]
/cmd queue -v PATCH_substrate=13018 -c bench-bot $ runtime kusama-dev pallet_staking

**Comment by Ank4n** [comment]
/cmd queue -v PATCH_substrate=13018 -c bench-bot $ runtime kusama-dev pallet_staking

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2197078

**Review by kianenigma — APPROVED** [review]

**Review by rossbulat — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot rebase

**Comment by bkchr** [comment]
@Ank4n we can probably still merge, ignoring the CI.

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-37/1736/1

**Pull request merged**
