### PR TITLE
paras: add log target

### PR DESCRIPTION
**Pull request by pepyakin**
Simply extract hardcoded log target into a const.

skip check-dependent-cumulus

### CODE REVIEW

**Comment by pepyakin** [comment]
Current dependencies on/for this PR:
* master
  * **PR #4408** 
    * **PR #4420** 
      * **PR #4457** 
        * **PR #4478**  (this PR)
        * **PR #4459** 

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh) and will continue to be automatically updated while this PR remains open.

**Review by bkchr — APPROVED** [review]

**Review by drahnr — APPROVED** [review]
It's a bit confusing that there is one additional commit in here, the log tag refactor lgtm.

**Comment by pepyakin** [comment]
yeah, that's because this PR/diff depends on the pep-pvf-paras. I did not update it so to avoid the endless:
Screenshot 2021-12-16 at 13 04 27

**Comment by drahnr** [comment]
bot merge

**Pull request merged**
