### PR TITLE
Companion of Substrate PR 12837

### PR DESCRIPTION
**Pull request by joao-paulo-parity**
https://github.com/paritytech/substrate/pull/12837

cumulus companion: https://github.com/paritytech/cumulus/pull/1944

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2115163

**Comment by joao-paulo-parity** [comment]
Note: no lockfile updates at the moment because the changed import declarations reference packages on Substrate's `master`, but they don't exist yet because https://github.com/paritytech/substrate/pull/12837 hasn't been merged yet. The lockfiles should be updated correctly here after https://github.com/paritytech/substrate/pull/12837 is merged via `bot merge`.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2116531

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2117218

**Review by acatangiu — APPROVED** [review]

**Review by coderobe — APPROVED** [review]

**Review by EgorPopelyaev — APPROVED** [review]

**Comment by joao-paulo-parity** [comment]
bot merge

**Pull request merged**
