### PR TITLE
Supercede 'Propagate Substrate#4284 to Polkadot'

### PR DESCRIPTION
**Pull request by expenses**
@tomaka is away, so I'm finishing off #680.

### CODE REVIEW

**Comment by rphmeier** [comment]
There are some small CI errors

**Comment by expenses** [comment]
> There are some small CI errors.

Yep, polkadot doesn't current compile with substrate master. Working on a different PR for that.

**Comment by expenses** [comment]
FYI I moved the changes from #698 into here.

**Comment by gavofyork** [comment]
Seems harmless enough but I would like to double-check that the child-trie changes are not going to break Kusama because they make use of a new API that older nodes don't have. @bkchr ?

**Comment by bkchr** [comment]
I will check the substrate pr and report back.

**Pull request merged**
