### PR TITLE
CI: bot allows simnet failure

### PR DESCRIPTION
**Pull request by ordian**
See https://github.com/paritytech/polkadot/pull/2958#issuecomment-833841942 for context.
This is a workaround until simnet job is proven to be stable.

### CODE REVIEW

**Review by joao-paulo-parity — APPROVED** [review]

**Comment by TriplEight** [comment]
I'm literally about to return it in the stable status, hence make it required.

**Comment by ordian** [comment]
@TriplEight as you can see from this PR it's not stable

**Comment by TriplEight** [comment]
Yeah, simnet still needs some love

**Review by TriplEight — APPROVED** [review]

**Comment by TriplEight** [comment]
bot merge

**Pull request merged**
