### PR TITLE
Convert SignedAvailabilityBitfields from newtype to typedef

### LINKED ISSUE #1339: SignedAvailabilityBitfields should be a typedef, not a newtype
https://github.com/paritytech/polkadot/blob/90d5dbe564ae795d68aff1c936cbdd1f98c9d536/primitives/src/parachain.rs#L727-L728

Rationale: 
- We pass around binary encoded bitfields. A newtype may not encode to the same representation as its wrapped type; a typedef always will.
- The wrapped type is public and we do not implement any interesting traits on the newtype; we aren't gaining any advantage in type safety or ease-of-use. 

I suspect this was simply an oversight, but we may as well fix it.

### PR DESCRIPTION
**Pull request by coriolinus**
Closes #1339. ~~Includes #1320.~~

~~The only commit in this PR which is not also in #1320 is 37546e0.~~

### CODE REVIEW

**Comment by rphmeier** [comment]
The single commit mentioned looks good

**Comment by rphmeier** [comment]
Needs a rebase / cherry-pick (see https://github.com/paritytech/polkadot/pull/1320#issuecomment-653653955 )

Also, I will tag this as "on ice" because it depends on a PR which is not yet merged.

**Comment by coriolinus** [comment]
With #1320 merged and this PR rebased, I'm removing the "on ice" tag.

**Comment by coriolinus** [comment]
Note that CI failures appear to be due to files unchanged by this PR.

**Pull request merged**
