### PR TITLE
More remote tests for bags-list pallet

### PR DESCRIPTION
**Pull request by kianenigma**
Now that bags list is in westend, and soon will launch on kusama, this PR adds a remote-test for it to make sure it has been migrated correctly and stays correct.

### CODE REVIEW

**Review by thiolliere — APPROVED** [review]

**Comment by azerella** [comment]
> build is failing

From process' bots perspective, the build is failing as the `Cargo.lock` _appears_ to be misconfigured, might need an actual Rust dev to correct me here but, just like the error message above we have multiple dep references in the lock file, for example:

```sh
# Cargo.lock

[[package]]
name = "sp-inherents"
version = "4.0.0-dev"
source = "git+https://github.com/paritytech/substrate?branch=kiz-make-things-pub#9a46ffd71ee27b69ea700d16e9b2e7e46a7fb297"
dependencies = [
 "async-trait",
 "impl-trait-for-tuples",
 "parity-scale-codec",
 "sp-core 4.0.0-dev (git+https://github.com/paritytech/substrate?branch=kiz-make-things-pub)",
 "sp-runtime 4.0.0-dev (git+https://github.com/paritytech/substrate?branch=kiz-make-things-pub)",
 "sp-std 4.0.0-dev (git+https://github.com/paritytech/substrate?branch=kiz-make-things-pub)",
 "thiserror",
]

[[package]]
name = "sp-inherents"
version = "4.0.0-dev"
source = "git+https://github.com/paritytech/substrate?branch=master#1d818f38a3198f21b4ae68bac3dc98219fccc669"
dependencies = [
 "async-trait",
 "impl-trait-for-tuples",
 "parity-scale-codec",
 "sp-core 4.0.0-dev (git+https://github.com/paritytech/substrate?branch=master)",
 "sp-runtime 4.0.0-dev (git+https://github.com/paritytech/substrate?branch=master)",
 "sp-std 4.0.0-dev (git+https://github.com/paritytech/substrate?branch=master)",
 "thiserror",
]
```

The difference being the branch references i.e

`source = "git+https://github.com/paritytech/substrate?branch=kiz-make-things-pub#9a46ffd71ee27b69ea700d16e9b2e7e46a7fb297"` **and** `source = "git+https://github.com/paritytech/substrate?branch=master#1d818f38a3198f21b4ae68bac3dc98219fccc669"`

@kianenigma Can you confirm how you upgraded the `Cargo.lock` ?

**Comment by kianenigma** [comment]
@azerella I've reverted the changes to the lock file, can you re-trigger the "update cargo and merge" process again?

**Comment by azerella** [comment]
bot merge

**Comment by azerella** [comment]
> @azerella I've reverted the changes to the lock file, can you re-trigger the "update cargo and merge" process again?

For sure, seems like it's playing nicer now once we get the workflow checks to pass :)

**Comment by kianenigma** [comment]
i think now it should be finally okay :)

**Comment by kianenigma** [comment]
bot merge

**Pull request merged**
