### PR TITLE
Increase recusive limits for macro expansions

### PR DESCRIPTION
**Pull request by lexnv**
Companion of https://github.com/paritytech/substrate/pull/14143

@paritytech/subxt-team

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by lexnv** [comment]
bot rebase

**Comment by lexnv** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3085129

**Comment by lexnv** [comment]
Have cherry-picked the patches from https://github.com/paritytech/polkadot/pull/7433, this will hopefully pass the CI and unblock further work. 

Soon these merge conflict races will be solved by the mono-repo work

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3085382

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
Included in: https://github.com/paritytech/polkadot/pull/7433

**Pull request closed without merging**
