### PR TITLE
CI: add rococo to the runtime check

### PR DESCRIPTION
**Pull request by ordian**
and bump the spec version to match other relay chains.

### CODE REVIEW

**Comment by SBalaguer** [comment]
Thanks @ordian for this 🙏 

Maybe a DQ, but is the `spec_version` 9180 to match the next release? Also, I don' think [this changes](https://github.com/paritytech/polkadot/pull/4761) where merged to master back then, but they did make it to 0.9.16. Should we account for those here as well?

**Comment by ordian** [comment]
> Maybe a DQ, but is the `spec_version` 9180 to match the next release? Also, I don' think [this changes](https://github.com/paritytech/polkadot/pull/4761) where merged to master back then, but they did make it to 0.9.16. Should we account for those here as well?

Yeah, it should be 9180, but it can be bumped as part of the release process (as it needs to be done for other networks anyway). So I've changed it to 9170 for consistency.
Also cherry-picked your PR. Are you aware of any other changes that didn't go to master?

**Review by coderobe — APPROVED** [review]

**Comment by ordian** [comment]
> I also don't know if the changes of 0.9.17 that went to Polkadot/Kusama/Westend made it to Rococo or not.

I don't think so:
```
system.lastRuntimeUpgrade: Option<FrameSystemLastRuntimeUpgradeInfo>
{
  specVersion: 9,142
  specName: rococo
}
```

**Comment by ordian** [comment]
bot merge

**Comment by coderobe** [comment]
bot merge

**Pull request merged**
