### PR TITLE
fix: runtime benchmark feature 

### PR DESCRIPTION
**Pull request by muharem**
these changes were included into master here https://github.com/paritytech/polkadot/pull/6663

### CODE REVIEW

**Comment by coderobe** [comment]
is this critical to go into the current release?

**Comment by muharem** [comment]
> is this critical to go into the current release?

Probably the benchmarks won't run without this.
Only for it.

**Comment by muharem** [comment]
Might work for Polkadot, but will fail for cumulus.

**Comment by muharem** [comment]
PR to fix similar issue in cumulus https://github.com/paritytech/cumulus/pull/2173

**Review by bkchr — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]

**Review by coderobe — APPROVED** [review]

**Pull request merged**
