### PR TITLE
feat(docker): refined Dockerfile

### PR DESCRIPTION
**Pull request by Akagi201**
Refined the Dockerfile scripts.

### CODE REVIEW

**Comment by rphmeier** [comment]
cc @chevdor

**Comment by chevdor** [comment]
Thanks for the PR @Akagi201. 
I wanted to have the dockerfile as independant as possible but your change will likely make it more maintainable.

**Comment by chevdor** [comment]
Not sure we need the `./init.sh` (nor its content) at all actually. So please hold on before merging until I am done with a few tests.

**Comment by Akagi201** [comment]
@chevdor I post this PR to let the docker build process is the same as the manual build process. I think it is important.

When build manually, just run

```
./init.sh
./build.sh
cargo build
```
so the Dockerfile should be the same process.

I have tested it and you may check it twice.

**Comment by chevdor** [comment]
What I am trying to say is that `./init.sh` and `./build.sh` are not required in the build process.
You can have a look at #463 where I removed them entirely. It makes the image smaller and faster to build while having also less moving parts.

**Comment by Akagi201** [comment]
I agree with two stage docker build. It is also good for isolating the source code and binary. And I wrote one for my own use. https://github.com/Akagi201/dockerfile/blob/master/polkadot/Dockerfile

I am not sure the need for the `init.sh` and `build.sh` script. If they are not required, you may close this PR.

**Comment by chevdor** [comment]
What is the size of the image you get in the end with your 2 stages image?

**Comment by chevdor** [comment]
@Akagi201 Thanks again for this PR, I will close it as agreed since the scripts are definitely not required.

**Pull request closed without merging**
