### PR TITLE
companion slash chilling update

### PR DESCRIPTION
**Pull request by kianenigma**
https://github.com/paritytech/substrate/pull/12420

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2147908

**Review by ordian — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2148438

**Comment by kianenigma** [comment]
Both tests are flaky and unimportant. Sorry, but force-merging this..

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-35/1509/1

**Pull request merged**
