### PR TITLE
Bump version, specs & substrate in prep for v0.9.8

### PR DESCRIPTION
**Pull request by s3krit**

### CODE REVIEW

**Review by bkchr — APPROVED** [review]
No migrations to delete?

**Comment by chevdor** [comment]
You caught already a lot of versions that were "left" behind.
I saw that `parity-util-mem` is on 0.9.0 but it is not part of the source and it is the latest (https://github.com/paritytech/parity-common/tree/master/parity-util-mem).

I see a bunch of crates on `0.1.0` (78 of them), do we want to:
- bump ALL crates no matter what
- bump only what changed
- option C

**Comment by bkchr** [comment]
> I saw that `parity-util-mem` is on `0.9.0` but it is not part of the source and it is the latest (https://github.com/paritytech/parity-common/tree/master/parity-util-mem).

What you mean by this? This is an extra crate?

**Comment by ordian** [comment]
@chevdor not sure what you mean, but parity-common crates have their own release schedule and they are published on crates.io, we update them as any other crates.io dependency here

**Comment by chevdor** [comment]
All good, just checking what version was not bumped.

**Comment by chevdor** [comment]
So after checking the history, I think most (if not all) 0.1.0 should be bumped.
I prepared a branch to see which ones and the diff can be seen here: https://github.com/paritytech/polkadot/compare/master...chevdor:wk-v0.9.8-prep?expand=1

**Comment by s3krit** [comment]
> No migrations to delete?

Nope, they got removed when https://github.com/paritytech/polkadot/pull/3347 was added

**Comment by chevdor** [comment]
@bkchr @pepyakin 
Do you have any objection bumping the `0.1.0` under `node` to `0.9.8` as well ? See diff [here](https://github.com/paritytech/polkadot/compare/mp-v0.9.8-prep...chevdor:wk-v0.9.8-prep?expand=1)

**Comment by ordian** [comment]
BTW, what's the point of bumping versions (besides in the root Cargo.toml) if none of the crates are published to crates.io?

**Review by meffi89 — CHANGES_REQUESTED** [review]
Nice

**Review by chevdor — APPROVED** [review]
I guess the 0.1.0 topic can wait one more release

**Pull request merged**
