### PR TITLE
Companion for paritytech/substrate#14080

### PR DESCRIPTION
**Pull request by altonen**
cumulus companion: https://github.com/paritytech/cumulus/pull/2526

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2786782

**Review by skunert — APPROVED** [review]

**Review by dmitry-markin — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2804979

**Review by melekes — APPROVED** [review]
👍

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2818759

**Comment by altonen** [comment]
bot merge

**Pull request merged**
