### PR TITLE
[ci] Adjust check-runtime-migration job

### PR DESCRIPTION
**Pull request by alvicsam**
PR splits jobs for 3 networks
cc https://github.com/paritytech/ci_cd/issues/573

### CODE REVIEW

**Comment by alvicsam** [comment]
bot rebase

**Comment by alvicsam** [comment]
bot rebase

**Comment by alvicsam** [comment]
bot rebase

**Comment by ggwpez** [comment]
bot rebase

**Review by altaua — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]

**Review by oleg-plakida — APPROVED** [review]

**Review by kianenigma — APPROVED** [review]
Thanks!

**Pull request merged**
