### PR TITLE
ignore fast-unstake remote test

### PR DESCRIPTION
**Pull request by kianenigma**

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by ggwpez — COMMENTED** [review]
Please also for the `run_migrations` test above.

**Comment by kianenigma** [comment]
> run_migrations

But actually we want `run_migration` to be executed on every PR that has the env-variable, no?

**Review by ggwpez — APPROVED** [review]
> But actually we want `run_migration` to be executed on every PR that has the env-variable, no?

The CI does not use them but try-runtime-cli instead. But we could think about it :man_shrugging:   
So probably fine either way.

**Review by stefan-sopic — APPROVED** [review]

**Comment by kianenigma** [comment]
bot merge

**Pull request merged**
