### PR TITLE
Guide: add a diagram for Inclusion Pipeline & Approval Subsystem

### PR DESCRIPTION
**Pull request by ordian**
The Availability Distribution step (6) is somewhat hard to display, it was omitted for brevity. Suggestions on how to improve this are welcome!

Also it only shows the happy path as there are too many ways where a failure can happen.

image

### CODE REVIEW

**Comment by coriolinus** [comment]
👍 for including a render! 

- Are `Validator 1` and `Validator 3` in the Approval Subsystem the same as in the Parachain Validators section? I suspect not, but I'm not sure.
- Maybe explicitly forward step 6 to a different diagram?

**Comment by ordian** [comment]
> Are Validator 1 and Validator 3 in the Approval Subsystem the same as in the Parachain Validators section? I suspect not, but I'm not sure.

They are the same if my undestanding is correct. I've tried to reuse the vertices, but the generated graph looked really complex. So I resorted to duplicated them and the diagram's y-axis is time.

**Comment by ordian** [comment]
> > Are Validator 1 and Validator 3 in the Approval Subsystem the same as in the Parachain Validators section? I suspect not, but I'm not sure.
> 
> They are the same if my undestanding is correct. I've tried to reuse the vertices, but the generated graph looked really complex. So I resorted to duplicating them and the diagram's vertical axis is time.

Actually I was wrong, let me know what you think about the latest version.

**Comment by coriolinus** [comment]
LGTM; I'm only not approving because I'm not confident that I have the knowledge to spot an error in the actual flow.

**Comment by rphmeier** [comment]
Yeah, the validators at every stage are drawn from the same set. We take care not to mix validator sets from different sessions.

**Comment by rphmeier** [comment]
bot merge

**Comment by burdges** [comment]
It looks fine.  I'd note when using that this gives only the happy path of course.

I'd maybe replace "subset of all" with "preassigned subset" for the backing phase and "unpredictable subset" for the approvals phase, but that's really the security reasoning, so..  

Just fyi, I attempted to make backing, availability, and approvals all fit the same mold in my tikz diagram in https://github.com/w3f/research/tree/master/docs/papers/AnV/slides not that you need to do that here..

**Pull request merged**
