### PR TITLE
Update `wasmtime` and related dependencies (companion for Substrate#10149)

### PR DESCRIPTION
**Pull request by koute**
Companion for https://github.com/paritytech/substrate/pull/10149

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
When there are no code changes on the Polkadot side, you actually don't need any companion :)

**Comment by koute** [comment]
> When there are no code changes on the Polkadot side, you actually don't need any companion :)

Alas, in this case the update broke Polkadot's compilation due to Cargo's dependency resolver not being able to resolve the dependency tree, so I had to add a companion. (:

**Comment by bkchr** [comment]
Ahh okay! :)

**Review by ordian — APPROVED** [review]

**Comment by ordian** [comment]
@koute looks like you need to do manual `cargo update -p sp-io` and resolve conflicts if any

**Comment by koute** [comment]
> @koute looks like you need to do manual `cargo update -p sp-io` and resolve conflicts if any

I'm on it.

**Comment by ordian** [comment]
bot merge

**Pull request merged**
