### PR TITLE
Companion PR for warp sync support.

### PR DESCRIPTION
**Pull request by arkpar**
Companion for https://github.com/paritytech/substrate/pull/9227

### CODE REVIEW

**Review by cheme — APPROVED** [review]
LGTM

**Review by bkchr — APPROVED** [review]

**Comment by arkpar** [comment]
bot merge

**Comment by arkpar** [comment]
Blocked by https://github.com/paritytech/polkadot/pull/3549

**Comment by bkchr** [comment]
@arkpar merged

**Comment by arkpar** [comment]
bot merge

**Pull request merged**
