### PR TITLE
Companion for substrate #13215 - Add new BEEFY api to runtimes

### PR DESCRIPTION
**Pull request by acatangiu**
Add new `beefy_primitives::BeefyApi::beefy_genesis()` api to runtimes.

Companion for: https://github.com/paritytech/substrate/pull/13215

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2310073

**Review by svyatonik — APPROVED** [review]

**Review by andresilva — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2319712

**Comment by acatangiu** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2332081

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2339326

**Comment by acatangiu** [comment]
bot rebase

**Review by sandreim — APPROVED** [review]

**Pull request merged**
