### PR TITLE
Changed README.adoc including clang in deps

### PR DESCRIPTION
**Pull request by mrmikardo**
Add clang as a build dependency to README.adoc

### CODE REVIEW

**Comment by mrmikardo** [comment]
[clabot:check].

**Comment by rphmeier** [comment]
out of curiosity, what is `clang` needed for?

**Comment by mrmikardo** [comment]
When building polkadot on my machine (Debian stretch), I ran into an error `failed to run custom build command for 'librocksdb-sys v5.14.3 ... thread 'main' panicked at 'Unable to find libclang ...` . Installing `clang` fixed this issue (unsurprisingly!).

I was following the build instructions under section 3.1 of the README i.e. building from source.

**Comment by gnunicorn** [comment]
> out of curiosity, what is `clang` needed for?

Since we switched (in Substrate) to the latest upstream `rocksdb` crate, `rocksdb-sys` isn't including a precompiled version anymore but actually builds `rocksdb`. And `rocksdb` needs clang.

**Comment by rphmeier** [comment]
I see, thanks for the explanations

**Pull request merged**
