### PR TITLE
Remove `HypotheticalDepthRequest` in favor of `HypotheticalFrontierRequest`

### PR DESCRIPTION
**Pull request by mrcnski**
Resolves a `TODO` in the code.

### CODE REVIEW

**Comment by mrcnski** [comment]
@slumber No problem! Do you want me to merge `rh-async-backing-feature` into the target branch, or are you on top of that, too?

**Comment by slumber** [comment]
Soo.. there were a lot of conflicts since the statement distribution branch is outdated.

But most had 0-impact on the logic. @mrcnski  you can take a look specifically at backing to review initial task related changes.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2287534

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2311047

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2313161

**Review by rphmeier — APPROVED** [review]
Looks correct, esp. the use of `HypotheticalCandidate::Incomplete` in the `can_second_request`.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2316263

**Pull request merged**
