### PR TITLE
Add proxy type for Kappa Sigma Mu

### PR DESCRIPTION
**Pull request by kianenigma**
This could be useful for allowing other to vote for you in the society, perhaps if you know you are going to be going offline for an extended period of time.

### CODE REVIEW

**Comment by shawntabrizi** [comment]
I mean, this seems fine, but could we just put this under governance instead? Or does it need to be so specific

**Comment by kianenigma** [comment]
> I mean, this seems fine, but could we just put this under governance instead? Or does it need to be so specific

High think a governance proxy is more important than the society. I am in favour of keeping it separate, adding a new variant is non-breaking.

**Review by shawntabrizi — APPROVED** [review]

**Review by gavofyork — APPROVED** [review]

**Comment by kianenigma** [comment]
bot merge

**Comment by kianenigma** [comment]
bot merge

**Comment by kianenigma** [comment]
bot merge

**Pull request merged**
