### PR TITLE
runtime: remove random_seed from BlockBuilder API

### PR DESCRIPTION
**Pull request by andresilva**
Companion for https://github.com/paritytech/substrate/pull/8718.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge cancel

**Comment by andresilva** [comment]
bot merge

**Review by ordian — APPROVED** [review]

**Comment by ordian** [comment]
bot merge

**Pull request merged**
