### PR TITLE
support swapping the para type

### PR DESCRIPTION
**Pull request by drahnr**
Impl of swapping the para type from thread to chain and vice versa while keeping all modalities.

Ref #1509

### CODE REVIEW

**Comment by rphmeier** [comment]
The old behavior was something like this:

Two paras agree to swap. This can be chain<>chain, thread<>thread, or chain<>thread. Practically, we only really need to support the chain<>thread case. Then the swap is carried out: the chains' IDs stay the same, but their kind (thread/chain) are swapped, as well as their deposits.

**Comment by drahnr** [comment]
No it doesn't, it was only the very beginning of swapping `thread <> chain` since, but since that #1559 + assumptions got falsified.

**Comment by burdges** [comment]
I'd assume the swap only takes effect two epochs later or whatever?

**Comment by rphmeier** [comment]
@burdges At the end of the current session (epoch) was what I was thinking

**Comment by burdges** [comment]
It's fine I think.   I worried about something that looks not really too problematic anyways.

**Pull request closed without merging**
