### PR TITLE
Companion for substrate#11148

### PR DESCRIPTION
**Pull request by jasl**
Companion for https://github.com/paritytech/substrate/pull/11148

cumulus companion: https://github.com/paritytech/cumulus/pull/1236

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by shawntabrizi — APPROVED** [review]

**Review by ggwpez — CHANGES_REQUESTED** [review]
Where do these values come from?  
Not from the bot obviously

**Comment by jasl** [comment]
> Where do these values come from? Not from the bot obviously

just copy paste `batch_all` I don't know how to trigger the bot

**Comment by ggwpez** [comment]
/bench runtime polkadot pallet pallet_utility

Not sure if the bot will be able to push to your branch.  
You currently still have the diener patch in your `Cargo.toml`, that needs to be removed for the CI since it contains file paths relative for your machine.

**Comment by jasl** [comment]
> /bench runtime polkadot pallet pallet_utility
> 
> Not sure if the bot will be able to push to your branch. You currently still have the diener patch in your `Cargo.toml`, that needs to be removed for the CI since it contains file paths relative for your machine.

Since the original PR merged, I think I can switch to current Substrate master and retry,
this is my first PR about companion, I'm not familiar the process, I'm sorry.

**Comment by ggwpez** [comment]
No problem @jasl, thanks for your help!  
I think the processbot does something like this to update the lockfiles `cargo update -p polkadot-primitives`.

**Comment by shawntabrizi** [comment]
@jasl bot cannot push to forks of the repo unfortunately.

We should just let this merge as is.

**Comment by jasl** [comment]
> @jasl bot cannot push to forks of the repo unfortunately.
> 
> We should just let this merge as is.

Okay... just rebased master

**Comment by shawntabrizi** [comment]
bot merge

**Comment by jasl** [comment]
lol, I'll make a companion for Cumulus

**Comment by shawntabrizi** [comment]
> lol, I'll make a companion for Cumulus

I made one for you. See the link i posted in your PR description.

**Review by ggwpez — APPROVED** [review]
I just ran it on ref hardware and your values are close enough :tada:

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
