### PR TITLE
update weights

### PR DESCRIPTION
**Pull request by coderobe**
https://github.com/paritytech/polkadot/pull/5910 on master

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]
Reviewed in https://github.com/paritytech/polkadot/pull/5910

**Review by EgorPopelyaev — APPROVED** [review]

**Comment by coderobe** [comment]
bot merge

**Comment by coderobe** [comment]
> panicked at 'infinite length input; no invalid inputs for type; qed: Error', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/00cc5f1/frame/benchmarking/src/utils.rs:352:5

h

**Comment by ggwpez** [comment]
bot rebase

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
