### PR TITLE
13110 Companion: Add WeightToFee and LengthToFee Runtime API

### PR DESCRIPTION
**Pull request by notlesh**
Companion for https://github.com/paritytech/substrate/pull/13110.

This adds `query_weight_to_fee` and `query_length_to_fee` to each runtime API impl.  

cumulus companion: https://github.com/paritytech/cumulus/pull/2073

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2247729

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2264664

**Review by bkchr — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2321031

**Comment by bkchr** [comment]
bot merge

**Comment by ggwpez** [comment]
bot merge

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-38/2122/1

**Pull request merged**
