### PR TITLE
Enable staking on Rococo/Versi

### PR DESCRIPTION
**Pull request by tdimitrov**
Enable staking on Rococo by adding `pallet_staking` and all its dependencies to Rococo chain spec. Westend chainspec is used as a reference.

### CODE REVIEW

**Comment by rphmeier** [comment]
Why? This is anti to the goal of Rococo as a product.

**Comment by tdimitrov** [comment]
> Why? This is anti to the goal of Rococo as a product.

We want to test slashing on versi. It uses the same chainspec as rococo so I did it there.
Should I create completely separate chainspec for Versi or you are against the idea altogether?

**Comment by tdimitrov** [comment]
I'll open a new PR which separates the chainspec of Versi from Rococo and then I'll apply the changes made here on top of it.

**Comment by rphmeier** [comment]
> I'll open a new PR which separates the chainspec of Versi from Rococo and then I'll apply the changes made here on top of it.

Thanks, I think it's a good time to do this.

**Pull request closed without merging**
