### PR TITLE
PVF: instantiate runtime from bytes

### PR DESCRIPTION
**Pull request by mrcnski**
# PULL REQUEST

## Overview

Summary of rationale:

1. Removes filesystem access from the PVF thread so we can lock it down.
2. Removes a potential race where we were checking file existence before passing the file path to `create_runtime_from_artifact`.

## Related

Closes https://github.com/paritytech/polkadot/issues/7266
https://github.com/paritytech/substrate/issues/13861

### CODE REVIEW

**Review by s0me0ne-unkn0wn — APPROVED** [review]
Looks very good! The only nit is naming: although the transition from `artifact_path` to `artifact_bytes` seems natural, we're usually using another naming for binary blobs, such as `code`, `blob`, `code_blob`, and similar. I'd use something like `native_blob` or I don't know. `artifact_bytes` says nothing about what's inside, I mean, that's a native executable code, not just bytes. So consider improving naming here, but that's not a blocker at all.

**Review by eskimor — APPROVED** [review]

**Comment by mrcnski** [comment]
@s0me0ne-unkn0wn `artifact_blob`?

**Comment by s0me0ne-unkn0wn** [comment]
> `artifact_blob`?

Maybe :thinking: Or `compiled_blob`. Or `prepared_blob`. Or `executable_blob`. Sometimes it's easier to roll the dice :grin:

**Comment by mrcnski** [comment]
bot merge

**Pull request merged**
