### PR TITLE
Companion PR for https://github.com/paritytech/substrate/pull/7463

### PR DESCRIPTION
**Pull request by cecton**

### CODE REVIEW

**Review by dvdplm — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by cecton** [comment]
bot merge

**Comment by cecton** [comment]
bot merge force

**Comment by cecton** [comment]
bot merge

**Comment by cecton** [comment]
bot merge

**Comment by cecton** [comment]
bot merge

**Pull request merged**
