### PR TITLE
Bump runtime version, update substrate.

### PR DESCRIPTION
**Pull request by gavofyork**
Includes #523

### CODE REVIEW

**Comment by gavofyork** [comment]
Runtime version is 1011 - that's one more than current network, no?

**Comment by bkchr** [comment]
@gavofyork aren't the changes of #524 missing?

**Comment by gavofyork** [comment]
i'm sure i merged it in before, but anyway i did it again...

**Comment by gavofyork** [comment]
yeah - i only merged up to 523 actually. the #524 isn't ready yet.

**Pull request merged**
