### PR TITLE
Fix priority thresholds

### PR DESCRIPTION
**Pull request by chevdor**
This PR fix the threshold for Medium prio.

### CODE REVIEW

**Review by dvdplm — APPROVED** [review]
Would be good to have a test for these perhaps?

**Review by coderobe — APPROVED** [review]

**Comment by chevdor** [comment]
@dvdplm how do you imagine such as test ?

**Comment by dvdplm** [comment]
> @dvdplm how do you imagine such as test ?

Yeah good question. Would it be possible to use past releases (whose PRs likely don't change labels) and assert that the priorities assigned are what we expect?

**Comment by chevdor** [comment]
I would not assume that the past was correct :)
What could be done is to create one or more synthetic `context.json`(this is where the data about the priorities and labels is located) then generated the release notes and compare with our expectations.

The templates are rather split so we could check each part individually.

**Pull request merged**
