### PR TITLE
Docker image: switch to alpine

### PR DESCRIPTION
**Pull request by chevdor**
kudo @azban
Same than https://github.com/paritytech/substrate/pull/1047

### CODE REVIEW

**Comment by azban** [comment]
only thought is that the apk package requirements may be different

**Comment by chevdor** [comment]
> only thought is that the apk package requirements may be different

I am building now to test. It should be pretty similar. Let´s see.

**Comment by chevdor** [comment]
It works but I realise this PR will be only useful later. For now, the polkadot image is built from the substrate repo.

**Comment by azban** [comment]
> It works but I realise this PR will be only useful later. For now, the polkadot image is built from the substrate repo.

how does that work? doesn't polkadot have additional functionality on top of substrate?

**Comment by chevdor** [comment]
The PR for the current polkadot (v0.2) is https://github.com/paritytech/substrate/pull/1053

**Comment by chevdor** [comment]
> > It works but I realise this PR will be only useful later. For now, the polkadot image is built from the substrate repo.
> 
> how does that work? doesn't polkadot have additional functionality on top of substrate?

In the future, Polkadot should be a rather simple project inheriting many elements from Substrate. But it did not start like that :)

The project has been started in the Polkadot repo then moved to Substrate. Currently, the Polkadot repo is kinda lagging behind.

The current code is all in the Substrate repo, either in the branch v0.2 (polkadot) or master (substrate).

**Comment by rphmeier** [comment]
@chevdor you could probably do this now, we've returned to the Polkadot repo a lot more now.

**Comment by chevdor** [comment]
Closing as going with alpine has shown being problematic from time to time.
It might become a good idea later when everything stabilises.

**Pull request closed without merging**
