### PR TITLE
bitfield-dist: check signatures once

### PR DESCRIPTION
**Pull request by ordian**
per relay_parent per validator_index as suggested by @rphmeier

### CODE REVIEW

**Review by rphmeier — APPROVED** [review]

**Comment by rphmeier** [comment]
bot merge

**Comment by ordian** [comment]
cc @joao-paulo-parity ^^^

**Comment by joao-paulo-parity** [comment]
> cc @joao-paulo-parity ^^^

@rphmeier @ordian fix should be applied. Please try `bot merge` again.

**Comment by ordian** [comment]
bot merge

**Pull request merged**
