### PR TITLE
Companion PR for #6564

### PR DESCRIPTION
**Pull request by pscott**
paritytech/substrate#6564

### CODE REVIEW

**Comment by tomaka** [comment]
Please add links
https://github.com/paritytech/substrate/pull/6564

**Comment by pscott** [comment]
> Please add links between the PRs
> [paritytech/substrate#6564](https://github.com/paritytech/substrate/pull/6564)

Erf, sorry, this has changed [recently](https://github.com/paritytech/substrate/pull/6568/files) I believe. This used to be `[..] OR use the same name for your Polkadot branch as the substrate branch`. My bad! :)

**Comment by tomaka** [comment]
It's not only for the bot to work properly, but also for the sanity of the people looking at PRs.

**Comment by tomaka** [comment]
There seems to be a legitimate test failure.

https://gitlab.parity.io/parity/polkadot/-/jobs/584397#L364

> thread 'main' panicked at 'Non-unique argument name: log-directory is already in use', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.1/src/app/parser.rs:181:9

**Comment by pscott** [comment]
> There seems to be a legitimate test failure.
> 
> https://gitlab.parity.io/parity/polkadot/-/jobs/584397#L364
> 
> > thread 'main' panicked at 'Non-unique argument name: log-directory is already in use', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.1/src/app/parser.rs:181:9

Yup working on it! :)

**Pull request merged**
