### PR TITLE
Companion for substrate #13159

### PR DESCRIPTION
**Pull request by girazoki**
Companion for substrate #13159: https://github.com/paritytech/substrate/pull/13159

Companion for cumulus: https://github.com/paritytech/cumulus/pull/2136

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2307948

**Review by ggwpez — APPROVED** [review]
This also needs the `cumulus companion: https://github.com/paritytech/cumulus/pull/2136` in the description.

**Review by sam0x17 — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Review by gavofyork — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2381518

**Pull request merged**
