### PR TITLE
Offences Migration v1: Removes `ReportsByKindIndex`

### PR DESCRIPTION
**Pull request by gupnik**
Companion for https://github.com/paritytech/substrate/pull/13936

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2716218

**Review by bkchr — APPROVED** [review]

**Review by andresilva — DISMISSED** [review]
Missing kusama migration

**Comment by gupnik** [comment]
> Missing kusama migration

Added it @andresilva

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2727966

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2728998

**Comment by gupnik** [comment]
bot merge

**Comment by ggwpez** [comment]
try-runtime will not go green.

**Review by oleg-plakida — APPROVED** [review]

**Review by altaua — APPROVED** [review]

**Review by sam0x17 — APPROVED** [review]

**Comment by ggwpez** [comment]
bot merge

**Comment by ggwpez** [comment]
bot merge

**Comment by ggwpez** [comment]
bot merge force

**Comment by gupnik** [comment]
bot merge force

**Comment by sam0x17** [comment]
bot merge force

**Pull request merged**
