### PR TITLE
Co #11976: Enable rust features

### PR DESCRIPTION
**Pull request by ggwpez**
Enable the `runtime-benchmarks` feature where required by the compiler in `--workspace` mode.  
This is a minimal change and could be extended to match the scope of the Substrate MR, but for now I dont want to blow it up.

Context: Feature gates are currently not working correctly since some features are enabled per default. One example: `runtime-benchmarks`. The Substrate MR fixes this and disables such features per default. Now this MR uses the enforced feature gates.

Substrate MR: https://github.com/paritytech/substrate/pull/11976  
Cumulus companion: https://github.com/paritytech/cumulus/pull/1607

### CODE REVIEW

**Review by acatangiu — APPROVED** [review]
LGTM!

**Review by shawntabrizi — APPROVED** [review]

**Comment by ggwpez** [comment]
bot rebase

**Comment by ggwpez** [comment]
bot merge

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
