### PR TITLE
chore: add cargo spellcheck configuration and custom topic specifc dictionary

### PR DESCRIPTION
**Pull request by drahnr**
Initial commit to contain `cargo-spellcheck` relevant configuration files and an initial set of dictionary items.

### CODE REVIEW

**Comment by drahnr** [comment]
Ping https://github.com/paritytech/parity-bridges-common/issues/333 - this is the ref on how to do it :)

**Comment by ordian** [comment]
I just tried it, seems like we need to add additional words to the dictionary:
```
CLI
https
repo
Kusama
debian
GiB
KSM
WND
DOTs
js
GPL
crypto
annualised
XCMP
decodable
merkle
trie
Merkle
blake2
pov-block
```
and probably others.

**Comment by ordian** [comment]
Still seeing a lot of false positives, mainly with camel case and snake_case struct names like `AllMessages` and `pallet_session`, but also some words could be added as well
```
customizable
Ethereum
XCM
BTC
u128
inherents
BFT
KYC
v0
v1
bool
vec
initializer
sr25519
ed25519
```

**Review by ordian — APPROVED** [review]
Looks like a good start, although it could be improved as mentioned in the comment.

**Comment by drahnr** [comment]
But those are essentially types, which should be enclosed in `TypeName` which are then not being checked.

**Pull request merged**
