### PR TITLE
Update system event variants

### PR DESCRIPTION
**Pull request by ECJ222**
This is a Companion PR to [paritytech/substrate#10296](https://github.com/paritytech/substrate/pull/10296)

skip check-dependent-cumulus

### CODE REVIEW

**Comment by ECJ222** [comment]
please could you review this pr @athei and @kianenigma.

**Review by bkchr — APPROVED** [review]

**Review by athei — APPROVED** [review]

**Comment by ECJ222** [comment]
Hi @athei, The CI keeps failing, please is there a way I can fix this?

**Comment by athei** [comment]
The companion CI will always fail because it builds against the current substrate `master` which does not include your changes. Don't look at it.

You need to concentrate on making your substrate PR's CI green.  The **continuous-integration/gitlab-check-dependent-polkadot** job there builds the polkadot companion against your PR. This is the one failing. This means that your companion (this PR) has build failures. So fix them and your substrates PR will get green. I can trigger the CI there once you made the changes here.

**Comment by ECJ222** [comment]
Thank you @athei, I made a few changes to the initial pr I sent.

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
