### PR TITLE
Ideas about candidate selection

### PR DESCRIPTION
**Pull request by JoshOrndorff**
I've been thinking about candidate selection recently and had a few ideas I thought worth sharing. Feedback welcome!

cc @girazoki

### CODE REVIEW

**Comment by JoshOrndorff** [comment]
Well, I guess the runtime API idea wouldn't be so straightforward. Validators don't know the parachain state, so they wouldn't be able to execute the runtime api (except in the case that it's a pure function). I guess that could be solved with some additional state proof, but that's adding more machinery than I initially thought.

**Comment by burdges** [comment]
Yes, bridge candidates necessarily prove target chain finality.

**Comment by bkchr** [comment]
This is nothing that the relay chain should care about. You can do whatever block author verification that you want.

**Comment by girazoki** [comment]
The runtime API in cases like BABE might not be able to provide the set of approved authors right? I mean collator eligibility depends on each collator's private key.

**Comment by girazoki** [comment]
I like the GRANDPA-style game but I think it might only work for a small and bounded set of collators (in the end validators most likely will need to verify a candidate was backed by 2/3 of the total collators).

**Comment by burdges** [comment]
There are two basically unrelated questions here: 

There exist parachains with pre-collation finality like bridges, consortiums, or even faster payment chains, since polkadot trades finality speed for throughput.  You might place some finality proofs into block headers, but actually validating them proceeds like any other parachain logic, not our problem.

Avoid spam by too many parachain collators all opening connections with parachain backing checker groups and the approval checkers who hold their incoming XCMP messages.  We've discussed various solutions and now the conversation lives in https://github.com/paritytech/polkadot/issues/2203  

We're obviously limited in what block production strategies we'll support, initially aura and later sassafras, but we're only hostile to strategies without pre-authorization proofs, like proof-of-work and [fantomette](https://arxiv.org/pdf/1805.06786.pdf), and likely something works even there.

**Comment by JoshOrndorff** [comment]
Thanks for the discussion and the links!

I wasn't aware that there may be some special treatment for engines that work similarly to Babe or Aura. That approach makes sense, and I'll follow the issue.

Thanks also for the observation that my grandpa-before-sending-to-validators idea can be conceived of as a bridge. I hadn't realized that.

**Comment by burdges** [comment]
Yes, if a parchain has enough validators for grandpa then they can achieve 6ish second finality before even submitting their block to polkadot, which maybe they desire.  I've not thought about how this could interact with backing, but maybe doing something there avoids adding 6 seconds before polkadot submission.  If so, that's slightly different than a bridge.

**Pull request closed without merging**
