### PR TITLE
Fix fuzzing builds xcm-fuzz and erasure-coding fuzzer

### PR DESCRIPTION
**Pull request by code-terror**
include polkadot-primitives in erasure-coding to build fuzzer..
Change honggfuzz to 0.5.55 from 0.5.54 for a straightforward build and include honggfuzz in fuzz.rs

### CODE REVIEW

**Comment by code-terror** [comment]
@eskimor @sandreim @rphmeier @pepoviola

**Review by ordian — APPROVED** [review]
Thanks!

You need to update the `Cargo.lock`(s) as well.

**Comment by code-terror** [comment]
@ordian @sandreim changed cargo.lock

**Comment by ordian** [comment]
The compilation fails:
```
error: unused import: `honggfuzz::fuzz`
  --> xcm/xcm-simulator/fuzzer/src/fuzz.rs:30:5
   |
30 | use honggfuzz::fuzz;
```
Because fuzz! macro is only used when `fuzzing` feature is enabled. 
I'd suggest to remove the `use` statement and replace `fuzz!` with fully qualified path `honggfuzz::fuzz!`.

**Comment by ordian** [comment]
There is also `erasure-coding/fuzzer/Cargo.lock` checked in, but any modifications are ignored by default by `erasure-coding/fuzzer/.gitignore`. I'd suggest just to remove that `Cargo.lock`.

**Comment by code-terror** [comment]
@ordian changed use statement

**Comment by ordian** [comment]
bot merge

**Pull request merged**
