### PR TITLE
Fix flaky availability-recovery test

### LINKED ISSUE #3798: Flakey Test in Availability Recovery
This test is failing in a unrelated Substrate PR: https://github.com/paritytech/substrate/pull/9699#issuecomment-913848242

```
test tests::task_canceled_when_receivers_dropped ... ok
failures:
---- tests::availability_is_recovered_from_chunks_if_no_group_provided stdout ----
SENDING NONE
thread 'tests::availability_is_recovered_from_chunks_if_no_group_provided' panicked at 'assertion failed: `NetworkBridge(SendRequests([ChunkFetching(OutgoingRequest { peer: Authority(Public(306721211d5404bd9da88e0204360a1a9ab8b87c66c1bc2fcdd37f3c2222cc20 (5DAAnrj7...))), payload: ChunkFetchingRequest { candidate_hash: 0x80a8f9a74b72848481709fbfc389c14e8b1e468294e025ae4b548cbfc299faf6, index: ValidatorIndex(4) }, pending_response: Sender { complete: true } }), ChunkFetching(OutgoingRequest { peer: Authority(Public(d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...))), payload: ChunkFetchingRequest { candidate_hash: 0x80a8f9a74b72848481709fbfc389c14e8b1e468294e025ae4b548cbfc299faf6, index: ValidatorIndex(1) }, pending_response: Sender { complete: true } })], TryConnect))` does not match `AllMessages::RuntimeApi(RuntimeApiMessage::Request(relay_parent,
                                                   RuntimeApiRequest::SessionInfo(session_index,
                                                                                  tx)))`', node/network/availability-recovery/src/tests.rs:198:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   3: polkadot_availability_recovery::tests::test_harness_fast_path::{{closure}}
   4: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
   5: <futures_util::future::join::Join<Fut1,Fut2> as core::future::future::Future>::poll
   6: std::thread::local::LocalKey<T>::with
   7: futures_executor::local_pool::block_on
   8: polkadot_availability_recovery::tests::availability_is_recovered_from_chunks_if_no_group_provided
   9: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
---- tests::availability_is_recovered_from_chunks_even_if_backing_group_supplied_if_chunks_only stdout ----
SENDING NONE
thread 'tests::availability_is_recovered_from_chunks_even_if_backing_group_supplied_if_chunks_only' panicked at 'assertion failed: `NetworkBridge(SendRequests([ChunkFetching(OutgoingRequest { peer: Authority(Public(1cbd2d43530a44705ad088af313e18f80b53ef16b36177cd4b77b846f2a5f07c (5CiPPseX...))), payload: ChunkFetchingRequest { candidate_hash: 0x80a8f9a74b72848481709fbfc389c14e8b1e468294e025ae4b548cbfc299faf6, index: ValidatorIndex(0) }, pending_response: Sender { complete: true } }), ChunkFetching(OutgoingRequest { peer: Authority(Public(8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48 (5FHneW46...))), payload: ChunkFetchingRequest { candidate_hash: 0x80a8f9a74b72848481709fbfc389c14e8b1e468294e025ae4b548cbfc299faf6, index: ValidatorIndex(2) }, pending_response: Sender { complete: true } })], TryConnect))` does not match `AllMessages::RuntimeApi(RuntimeApiMessage::Request(relay_parent,
                                                   RuntimeApiRequest::SessionInfo(session_index,
                                                                                  tx)))`', node/network/availability-recovery/src/tests.rs:198:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   3: polkadot_availability_recovery::tests::test_harness_chunks_only::{{closure}}
   4: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
   5: <futures_util::future::join::Join<Fut1,Fut2> as core::future::future::Future>::poll
   6: std::thread::local::LocalKey<T>::with
   7: futures_executor::local_pool::block_on
   8: polkadot_availability_recovery::tests::availability_is_recovered_from_chunks_even_if_backing_group_supplied_if_chunks_only
   9: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
failures:
    tests::availability_is_recovered_from_chunks_even_if_backing_group_supplied_if_chunks_only
    tests::availability_is_recovered_from_chunks_if_no_group_provided
test result: FAILED. 16 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.26s
error: test failed, to rerun pass '-p polkadot-availability-recovery --lib'
Command exited with non-zero status 101
6906.14user 273.21system 12:52.92elapsed 928%CPU (0avgtext+0avgdata 16194684maxresident)k
752inputs+14941384outputs (13594major+58405340minor)pagefaults 0swaps

### PR DESCRIPTION
**Pull request by eskimor**
Fixes #3798

### CODE REVIEW

**Review by ordian — APPROVED** [review]
"Fixes" :smile:

**Comment by eskimor** [comment]
What's wrong with the test suite?

**Comment by ordian** [comment]
> What's wrong with the test suite?

It's flaky as well :P The compilation process was SIGKILLed, so the usual redis cache OOM or something like that.

**Comment by ordian** [comment]
bot merge

**Pull request merged**
