### PR TITLE
Switch types to use `RuntimeDebug` instead of gated `Debug`

### PR DESCRIPTION
**Pull request by bkchr**
This is useful for when you want to debug in wasm and enable the
`force-debug` feature of `sp-debug-derive`.

Fixes: https://github.com/paritytech/polkadot/issues/4651

### CODE REVIEW

**Review by kianenigma — APPROVED** [review]
This should have a small, but non-zero impact on the code size if I am not mistaking. The `RuntimeDebug` will generate a `impl` block for this type in wasm that's not really printing anything, whereas the std-gated `Debug` is literally non-existent in wasm. Can you confirm which one is the case here? Maybe the `RuntimeDebug`'s implementation is also stripped away by the compiler? 

Either way, PR is fine to me.

**Comment by bkchr** [comment]
> The `RuntimeDebug` will generate a `impl` block for this type in wasm that's not really printing anything, whereas the std-gated `Debug` is literally non-existent in wasm.

This is correct. `RuntimeDebug` will print `<wasm:stripped>`

**Comment by hirschenberger** [comment]
Can we please land this quickly, as I need it for debugging my code? Merci.

**Comment by bkchr** [comment]
> I'm running a benchmark with `--execution=native`, so it should not be stripped, right?

Benchmarks are only running in wasm.


> I want to debug a `frame_system::pallet::Config::Event`, which is still `Debug`, `RuntimeDebug` needs to be introduced to substrate as well?

If it is just `Debug`, there is no problem.

**Comment by hirschenberger** [comment]
> > I'm running a benchmark with `--execution=native`, so it should not be stripped, right?
> 
> Benchmarks are only running in wasm.
> 
> > I want to debug a `frame_system::pallet::Config::Event`, which is still `Debug`, `RuntimeDebug` needs to be introduced to substrate as well?
> 
> If it is just `Debug`, there is no problem.

So how can I debug my event then without being stripped away?

**Comment by bkchr** [comment]
This is using this code: https://github.com/paritytech/substrate/blob/master/frame/support/procedural/src/lib.rs#L448-L476

**Pull request merged**
