### PR TITLE
Make some fixes to logging in PVF subsystem

### LINKED ISSUE #3599: Log status code a prepare or execute worker exited with
This should give us a clue what is the reason for the worker to be terminated.

### LINKED ISSUE #4216: Log spam when enable parachain::pvf=trace
`parachain::pvf=trace` is required to diagnostic para block validation issue. However this log prints the entire head data, which is a ridiculously large binary blob and make debugging very hard. We start observing this issue since 0.9.12.

`2021-11-04 01:06:18.631 DEBUG tokio-runtime-worker parachain::pvf: job finished. validation_code_hash=0x9fe0c149def566a0326e2443f4a73232e5fb2e46ea5337fd3aedbd79f11d7c6f worker_rip=false result=Ok(ValidationResult { head_data: HeadData([18`

https://github.com/paritytech/polkadot/blob/8962e04029658ab467a3a102cc1a4295a7e7255d/node/core/pvf/src/execute/queue.rs#L247-L253

At very minimal, make it a trace log.

ping @pepyakin

### PR DESCRIPTION
**Pull request by m-cat**
# PULL REQUEST

## Overview

Tackled some simpler issues relating to logging in the PVF subsystem.

I made the trace log for execute worker conclusion match the one for prepare worker conclusion. Trace log for conclusion of prepare job:

```rs
gum::debug!(
	target: LOG_TARGET,
	validation_code_hash = ?artifact_id.code_hash,
	?worker,
	?rip,
	"prepare worker concluded",
);
```

## Issues Closed

Closes #3599
Closes #4216

### CODE REVIEW

**Review by pepyakin — APPROVED** [review]

**Review by sandreim — APPROVED** [review]

**Comment by sandreim** [comment]
bot merge

**Comment by sandreim** [comment]
bot rebase

**Comment by m-cat** [comment]
Thanks @eskimor. 👍

**Comment by eskimor** [comment]
Thank you Marcin!!

**Pull request merged**
