### PR TITLE
Companion PR for #7138 (WeightInfo for Scheduler)

### PR DESCRIPTION
**Pull request by shawntabrizi**
This PR adds the WeigtInfo struct and a new associated type `MaxScheduledPerBlock` which introduces a soft warning when too many items are in the scheduler queue.

https://github.com/paritytech/substrate/pull/7138

### CODE REVIEW

**Review by thiolliere — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Comment by shawntabrizi** [comment]
bot merge

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Review by andresilva — APPROVED** [review]

**Comment by andresilva** [comment]
bot merge

**Pull request merged**
