### PR TITLE
[DNM] Prepopulate storage with disputes for paras_inherent benchmark

### PR DESCRIPTION
**Pull request by tdimitrov**
Test PR

### CODE REVIEW

**Comment by tdimitrov** [comment]
bot bench $ runtime rococo runtime_parachains::paras_inherent

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2543890

**Comment by tdimitrov** [comment]
bot bench $ runtime polkadot runtime_parachains::paras_inherent

**Comment by tdimitrov** [comment]
bot bench $ runtime polkadot runtime_parachains::paras_inherent

**Comment by tdimitrov** [comment]
bot bench $ runtime rococo runtime_parachains::paras_inherent

**Pull request closed without merging**
