### PR TITLE
create newtype for ValidationCodeHash

### PR DESCRIPTION
**Pull request by andresilva**
As suggested here: https://github.com/paritytech/polkadot/pull/3210#discussion_r650074090.

### CODE REVIEW

**Review by ordian — APPROVED** [review]
obrigado

**Review by bkchr — APPROVED** [review]

**Comment by andresilva** [comment]
bot merge

**Comment by bkchr** [comment]
@jacogr new type `ValidationCodeHash` in here.

**Comment by andresilva** [comment]
bot merge

**Pull request merged**
