### PR TITLE
configuration: drop `pvf_checking_enabled` parameter

### PR DESCRIPTION
**Pull request by slumber**
Follow-up for https://github.com/paritytech/polkadot/pull/7138, simply removes unused value from the config.

Part of #3211

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3023617

**Review by antonva — APPROVED** [review]

**Review by s0me0ne-unkn0wn — APPROVED** [review]

**Comment by eskimor** [comment]
Another config migration - let's merge this with the other ones.

**Review by ordian — APPROVED** [review]

**Review by rphmeier — APPROVED** [review]

**Comment by slumber** [comment]
bot merge

**Comment by slumber** [comment]
bot merge

**Comment by slumber** [comment]
CI for migrations actually fails with "corrupted state" error at active config key. However, it shows host config **without** `pvf_checking_enabled` value before the migration is applied, as if it was done several times. Looks confusing.

**Comment by eskimor** [comment]
> Another config migration - let's merge this with the [other ones](https://github.com/paritytech/polkadot/pull/7452).

Hmm, this comment apparently did not make it through. @antonva @tdimitrov  the other migrations now have to be adjusted again (bumped one version). Also @tdimitrov doesn't the storage migration issue we had (which was blocking the other PR) not also affect this one? @slumber

**Comment by slumber** [comment]
> > Another config migration - let's merge this with the [other ones](https://github.com/paritytech/polkadot/pull/7452).
> 
> Hmm, this comment apparently did not make it through. @antonva @tdimitrov the other migrations now have to be adjusted again (bumped one version). Also @tdimitrov doesn't the storage migration issue we had (which was blocking the other PR) not also affect this one? @slumber

My bad, got sidetracked several times and was busy debugging the CI issue. The summary is here https://github.com/paritytech/polkadot/pull/7489#issuecomment-1630976076

**Comment by tdimitrov** [comment]
> Also @tdimitrov doesn't the storage migration issue we had (which was blocking the other PR) not also affect this one? @slumber

As far as I understand from the conversation in https://github.com/paritytech/polkadot/pull/7489 - it should be safe now because the UMP migration is already released (but not yet applied) for Polkadot.

But generally speaking you are right - UMP migration will fail if it is executed together with host config v7 AND before it.

**Comment by tdimitrov** [comment]
The comment above is not correct. The UMP migration doesn't fail, the HostConfig V7 one fails. https://github.com/paritytech/polkadot/pull/7265 was supposed to introduce HostConfig V7 so I hadn't got the same problem back then.

**Pull request merged**
