### PR TITLE
Cleanup light client leftovers

### PR DESCRIPTION
**Pull request by dmitry-markin**
This PR completely deprecates light client mode. Companion to https://github.com/paritytech/substrate/pull/11865

cumulus companion: https://github.com/paritytech/cumulus/pull/1456

### CODE REVIEW

**Comment by dmitry-markin** [comment]
@sandreim, thanks, missed `test-parachains`, fixed.

As for https://github.com/paritytech/polkadot/blob/4c1dcfd3fa800dddaa4550cd7c68123a445cbd72/node/network/protocol/src/lib.rs, doesn't `ObservedRole` represent a self-reported role of the remote node, not us? Which can be reported, i.e., by `smoldot` Or am I missing something?

**Comment by dmitry-markin** [comment]
```
| wasm source files changed or the spec version in the substrate reference in
| the Cargo.lock but not the spec/impl version. If changes made do not alter
| logic, just bump 'impl_version'. If they do change logic, bump
| 'spec_version'.
| 
| source file directories:
| - runtime
| 
| version files: kusama polkadot westend rococo
```
Could somebody help with this check? No files in `runtime` directory were changed by the PR, nor the version of `substarte` in `Cargo.lock`

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
> ```
> | wasm source files changed or the spec version in the substrate reference in
> | the Cargo.lock but not the spec/impl version. If changes made do not alter
> | logic, just bump 'impl_version'. If they do change logic, bump
> | 'spec_version'.
> | 
> | source file directories:
> | - runtime
> | 
> | version files: kusama polkadot westend rococo
> ```
> 
> Could somebody help with this check? No files in `runtime` directory were changed by the PR, nor the version of `substrate` in `Cargo.lock`

You can ignore  this

**Comment by sandreim** [comment]
> @sandreim, thanks, missed `test-parachains`, fixed.
> 
> As for [node/network/protocol/src/lib.rs](https://github.com/paritytech/polkadot/blob/4c1dcfd3fa800dddaa4550cd7c68123a445cbd72/node/network/protocol/src/lib.rs), doesn't `ObservedRole` represent a self-reported role of the remote node, not us? Which can be reported, i.e., by `smoldot` Or am I missing something?

I think you are correct.

**Review by sandreim — APPROVED** [review]

**Pull request merged**
