### PR TITLE
implementers-guide: in TOC move collators before backing, to match protocol pipeline

### PR DESCRIPTION
**Pull request by infinity0**

### CODE REVIEW

**Comment by infinity0** [comment]
CC @rphmeier

**Comment by infinity0** [comment]
The failing CI tests say "[!] Release notes label not detected. Please add one of: B0-silent B1-releasenotes B7-runtimenoteworthy".

I'm not sure how to deal with this, but I guess someone else more familiar with this repo does?

**Comment by coriolinus** [comment]
That's CI enforcing that every PR in the repo has a label from each of the A, B, and C categories. I took care of it for you.

**Comment by infinity0** [comment]
@coriolinus Thanks. I don't see the option to add/remove labels here from my end, maybe I don't have the permissions to do so?

**Comment by ordian** [comment]
bot merge

**Comment by coriolinus** [comment]
@infinity0 I can't say whether or not you have the permissions. What I can say is that, on the right-hand sidebar, if there is a gear icon by the labels row, then you can click that to edit the labels. If not, then you don't have the permissions.

**Pull request merged**
