### PR TITLE
Move documentation from Asciidoc to Markdown.

### PR DESCRIPTION
**Pull request by XAMPPRocky**
### [Rendered](https://github.com/XAMPPRocky/polkadot/tree/adoc-to-md)

Currently the documentation is using Asciidoc for the format, however some of the documentation was written in markdown. Thus it is currently rendered incorrectly on GitHub, this PR moves the documentation over to markdown since that is a more common for GitHub and Rust projects.

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
[clabot:check]

**Comment by gavofyork** [comment]
Wasn't there some reason we moved it from MD to ADOC in the first place? Anyone?

**Comment by XAMPPRocky** [comment]
I've updated the top post with a link so people can see how it's[rendered.](https://github.com/XAMPPRocky/polkadot/tree/adoc-to-md)

**Comment by shawntabrizi** [comment]
@gavofyork this is the historical reason for asciidoc:
https://github.com/paritytech/substrate/pull/407

Although, I personally think markdown is much better here for the simple fact that it is more "standard".

**Comment by XAMPPRocky** [comment]
Is there a place where the benefits mentioned in the PR are used? E.g. is there a place where the documentation in the repo is turned into a single PDF? If there was a desire to continue using Asciidoc over markdown, I think it would be helpful to document those places, and document in the CONTRIBUTING to use Asciidoc, as I noted above some contributors have assumed it was using and lead to the documentation not being rendered properly. One example of this is the Attribution section in the [CODE_OF_CONDUCT](https://github.com/paritytech/polkadot/blob/master/CODE_OF_CONDUCT.adoc#attribution)

**Comment by chevdor** [comment]
Too bad I see that only now!

There was a good reason to move from md to asciidoc!

Asciidoc is just like md but it supports includes so you can, without any extra tooling:
- include other adoc files
- include code snippets coming from the code
- build table of contents
- use variables and macros (no must but often useful)
- building several docs for different audiences by simply making high level adoc files including different sets of files

**Comment by XAMPPRocky** [comment]
@chevdor Sure, however none of the documentation used those features, and in fact the documentation contained incorrect markup because people assumed that it was markdown. While those features can certainly be helpful, if people aren't making use of them then the point becomes moot. It's also important to think about where people are reading this documentation, which I would be willing to bet for most it's GitHub's UI, which uses a reduced set of features.

**Comment by chevdor** [comment]
Hi @XAMPPRocky, I am just trying to answer the question that was raised. 

The substrate adoc version of the doc heavily uses that or at least used to. That would for instance allow the polkadot to include some bits of information coming from substrate which would totally make sense since the software also works this way.

I agree that Github makes it hard with the includes. Instead of doing it, they add a link... There is an issue opened for Github on that for a long time. Since Gitlab managed, I am sure GH will eventually fix it.

IMO, while - as you mention - asciidoc requires a little adaptation, this is well worth. The issue with md, especially with a project with lots of packages and sub projects is that it is very hard to find the doc unless browsing around, which people end up not doing.

Asciidoc addresses that we you can have one single entry point and point users to that knowing that everything is in there.

The fact that 'many people' use md should not be much of an argument. What counts is what is best. The differences are so small that people can learn and if they don't the issue are trivial to fix. Many of the syntax is actually much easier with asciidoc, a good examples are links.

I am not trying to make you guys revert if you like the md option but at least you now know what the benefits of asciidoc are and the reason for by earlier PR for both the Polkadot and Substrate repos.

**Comment by shawntabrizi** [comment]
> What counts is what is best.

I disagree here. I think what counts for an open source project like this, is whatever makes it easier for new people to contribute. It is pretty clear that Markdown is the more well known and commonly used flavor of markup, and as such I think it makes sense to stick with it.

**Comment by chevdor** [comment]
Up to you guys, just trying to bring the missing facts.

As far as the popularity argument is concerned, PHP is more popular than Rust...
https://trends.google.com/trends/explore?q=rust,php&hl=en-US

But I hope you stick with what is best here.

**Pull request merged**
