### PR TITLE
Companion for substrate #14036

### PR DESCRIPTION
**Pull request by davxy**
Companion for https://github.com/paritytech/substrate/pull/14036

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2745705

**Comment by burdges** [comment]
I disagree with renaming VrfTranscript to VrfInput because transcripts are used for thing other than the input.

**Comment by davxy** [comment]
> I disagree with renaming VrfTranscript to VrfInput because transcripts are used for thing other than the input.
> 
> It's fine to rename some of the variables since they are inputs, but that's not the general situation for the type.

The `VrfInput` name maybe is not the most technicalky accurate but has been choosen because wants to represent some kind of input to the `vrf_sign` method.

From an abstract POV this input can contain (as you mentioned in the substrate PR) other stuff and is specific to the particular vrf.

Indeed in this case `VrfInput` contains transcript but also extra data. I don't think that the end user should be interested or be aware of the very technical details (i don't even think that users know the meaning of a "transcript" to be used in Fiat-Shamir proof and probably - at this level - they should not).

IMHO they should just have an abstraction to construct "something" to be given to a method to sign and they should be informed which part of this "input type" contributes to the vrf output and which instead just to the proof.

BTW, I'm also open to other names, but I still think that Transcript is not the most appropriate.
- is not just the transcript
- the user doesn't care
- doesn't fit well with the generic vrf trait where other vrfs may not use transcripts

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2753149

**Review by michalkucharczyk — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Review by melekes — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2774544

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2778544

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2781243

**Pull request merged**
