### PR TITLE
Bump transaction_version for polkadot, kusama, & westend (backport of #4831)

### PR DESCRIPTION
**Pull request by coderobe**
See https://github.com/paritytech/polkadot/pull/4831

### CODE REVIEW

**Review by chevdor — APPROVED** [review]

**Review by EgorPopelyaev — COMMENTED** [review]
looks good

**Review by bkchr — APPROVED** [review]

**Review by chevdor — APPROVED** [review]

**Comment by alvicsam** [comment]
It's better to pull entire `.gitlab-ci.yml` from master, because there were other changes in CI apart from https://github.com/paritytech/polkadot/pull/4826

**Comment by chevdor** [comment]
bot merge

**Review by chevdor — APPROVED** [review]

**Review by EgorPopelyaev — APPROVED** [review]

**Comment by chevdor** [comment]
Closed in favor of #4836

**Pull request closed without merging**
