### PR TITLE
Remove BEEFY repo dependency

### PR DESCRIPTION
**Pull request by adoerr**
Remove dependencies on the standalone `BEEFY` repository and use the Substrate integrate version of `BEEFY` instead.

### CODE REVIEW

**Review by ordian — APPROVED** [review]
It'd good to deduplicate `libsecp256k1`, but that might require upgrading libp2p

**Comment by adoerr** [comment]
Merging [Bump libsecp256k1 from 0.6.0 to 0.7.0](https://github.com/paritytech/polkadot/pull/3909) would accomplish this, I gues.

**Comment by ordian** [comment]
libp2p still on 0.5: https://github.com/paritytech/polkadot/blob/8938a0dc6d6b98c01e20d0033df45d4967f080fb/Cargo.lock#L3389

**Comment by adoerr** [comment]
Yeah, just discovered that as well :see_no_evil:

**Comment by adoerr** [comment]
bot merge

**Pull request merged**
