### PR TITLE
Refactored the build steps for building with cargo

### PR DESCRIPTION
**Pull request by saki-osive**
Hi, the steps for `Install via Cargo` at **https://github.com/paritytech/polkadot#install-via-cargo** are incomplete in the regard that they miss important pre-requisites for getting the project up and running with cargo.

This PR addresses this.

### CODE REVIEW

**Comment by bkchr** [comment]
These steps are documented below your changes. So, this change isn't required.

**Comment by saki-osive** [comment]
@bkchr So, shouldn't they be earlier so that the user knows that they're needed. I'm talking specifically about the Cargo install.

**Comment by bkchr** [comment]
You could add a comment that the prerequisites from below need to be installed.

**Comment by saki-osive** [comment]
Yes, for the `build-essential` package, it can be added, but some dependencies lie in the scripts of the code which need to be manually installed in the **Cargo build** method. So they have to be explicitly added, further, it's better the Cargo build method is self-sufficient in itself and can be followed from the get-go.

**Pull request closed without merging**
