### PR TITLE
Companion for Substrate#11107

### PR DESCRIPTION
**Pull request by koute**
Companion for https://github.com/paritytech/substrate/pull/11107

Fixes https://github.com/paritytech/polkadot/issues/5190
Closes #4862

cumulus companion: https://github.com/paritytech/cumulus/pull/1089

### CODE REVIEW

**Review by wigy-opensource-developer — APPROVED** [review]

**Comment by KiChjang** [comment]
bot merge

**Comment by KiChjang** [comment]
@davxy The best way is to roll every companion into one PR and have it merged, as what @bkchr suggested, because your companion is still going to fail without this PR merged.

**Comment by KiChjang** [comment]
bot merge

**Comment by KiChjang** [comment]
@davxy In that case, we'll just put it in the description of this PR.

**Comment by KiChjang** [comment]
bot merge

**Comment by shawntabrizi** [comment]
Gonna handle the rest of the errors manually

**Pull request merged**
