### PR TITLE
impl guide: Collator Generation

### PR DESCRIPTION
**Pull request by mrcnski**
Some notes I started taking on this subsystem.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2573819

**Review by BradleyOlson64 — COMMENTED** [review]
An interesting read! Found a couple nits that would make things more clear to me.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2624048

**Comment by mrcnski** [comment]
Closing, will raise a new PR without the "With Async Backing" section.

**Pull request closed without merging**
