### PR TITLE
Switch to edition 2021

### PR DESCRIPTION
**Pull request by bkchr**
Switch to rust edition 2021.

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Review by KiChjang — APPROVED** [review]
Not entirely understanding the switch to `V1` in `messages_benchmarking`, but everything else luks gud.

**Comment by drahnr** [comment]
> Not entirely understanding the switch to `V1` in `messages_benchmarking`, but everything else luks gud.

It's the bridges dir, which is a subtree and didn't build before.

**Comment by drahnr** [comment]
bot merge

**Comment by bkchr** [comment]
> Not entirely understanding the switch to `V1` in `messages_benchmarking`, but everything else luks gud.

The same change was done in bridges repo also already.

**Comment by drahnr** [comment]
bot merge

**Pull request merged**
