### PR TITLE
some tests to avoid regressions in xcm ancestry inversion

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
1. ported some tests from conversion to multilocation
2. added tests which proves that transferring to and from leads to same location 
3. may be useful to test before merge of https://github.com/paritytech/polkadot/pull/6301

### CODE REVIEW

**Comment by bkchr** [comment]
Could you point them against the gav-xcmv3 branch?

**Comment by dzmitry-lahoda** [comment]
really nice. interiorml fixed undefined states :) great

**Comment by KiChjang** [comment]
Should probably go in after we merge XCM v3, otherwise I don't see how this helps with #6301.

**Comment by dzmitry-lahoda** [comment]
Sorry for the confusion.

Initially, I was reading ancestry code and found that there are 2 very similar methods for some cases, so different impl. So I ported some cases from one to other. Also added fixed point test (converting back and forth leads to same input).

I PRed to `master` , same as #6301.  So it could be reasonable to run more tests then less on such refactoring to avoid some parachains setup regression.

But. With v3 branch, it seems that v3 has better job to do type safety and code clarity. It is ok to make behaviour change in it, so IMHO #6301 should be rebased on v3 to be more useful. 

So these are just tests. And at least one test is readable by ordinary parachain devs (fixed point one).

**Pull request closed without merging**
