### PR TITLE
Relaunch Rococo

### PR DESCRIPTION
**Pull request by bkchr**
Session length: 1h

Thanks for @SBalaguer for the initial commits.

### CODE REVIEW

**Review by al3mart — APPROVED** [review]
Looks good, works well

**Comment by ordian** [comment]
Does it make Versi's sessions 1h as well? We probably want to keep 10mins, but not building yet another runtime.

**Comment by bkchr** [comment]
> Does it make Versi's sessions 1h as well? We probably want to keep 10mins, but not building yet another runtime.

This doesn't change any other chain spec. However, rococo supports to change the session length dynamically. As rococo local also still runs with 1 minute session length.

**Comment by PierreBesson** [comment]
> Does it make Versi's sessions 1h as well? We probably want to keep 10mins, but not building yet another runtime.

I think it does as Versi is configured to use the Rococo chainspec definition. New configuration code might have to be written specifically for Versi chainspec.

**Comment by bkchr** [comment]
> > Does it make Versi's sessions 1h as well? We probably want to keep 10mins, but not building yet another runtime.
> 
> I think it does as Versi is configured to use the Rococo chainspec definition. New configuration code might have to be written specifically for Versi chainspec.

Exported chain specs are different. However, we would need to set some value on Versi before a runtime upgrade is done.

**Review by drahnr — APPROVED** [review]

**Pull request merged**
