### PR TITLE
Inherent filtering follow up

### PR DESCRIPTION
**Pull request by emostov**
Follow up to #4028 

cc @drahnr 

skip check-dependent-cumulus

### CODE REVIEW

**Comment by emostov** [comment]
/benchmark runtime polkadot runtime_parachains::paras_inherent

**Comment by emostov** [comment]
To benchmark rococo I think we will need to do: 

"/benchmark runtime custom --chain=rococo-dev --steps=50 --repeat=20 --pallet=runtime_parachains::paras_inherent --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --header=./file_header.txt --output=./runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs"

**Comment by emostov** [comment]
/benchmark runtime custom --chain=rococo-dev --steps=50 --repeat=20 --pallet=runtime_parachains::paras_inherent --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --header=./file_header.txt --output=./runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs

**Comment by emostov** [comment]
After rococo completes we just need to run "/benchmark runtime westend runtime_parachains::paras_inherent" and then we should have our bases covered for weights

**Comment by emostov** [comment]
/benchmark runtime custom --chain=rococo-dev --steps=50 --repeat=20 --pallet=runtime_parachains::paras_inherent --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --header=./file_header.txt --output=./runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs

**Comment by emostov** [comment]
/benchmark runtime custom --chain=rococo-dev --steps=50 --repeat=20 --pallet=runtime_parachains::paras_inherent  --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs --header=./file_header.txt

**Comment by emostov** [comment]
> Benchmark **Runtime Custom** for branch "zeke-inherent-filtering-follow-up" with command cargo run --quiet --release --features runtime-benchmarks -- benchmark --chain=rococo-dev --steps=50 --repeat=20 --pallet=runtime_parachains::paras_inherent --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs --header=./file_header.txt
> 
> Results
> ERROR: Unable to commit file ./runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs

Not sure whats going on here - don't see errors in the logs and works locally so I am guessing some issue just on writing the file

**Comment by emostov** [comment]
> > Benchmark **Runtime Custom** for branch "zeke-inherent-filtering-follow-up" with command cargo run --quiet --release --features runtime-benchmarks -- benchmark --chain=rococo-dev --steps=50 --repeat=20 --pallet=runtime_parachains::paras_inherent --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs --header=./file_header.txt
> > Results
> > ERROR: Unable to commit file ./runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs
> 
> Not sure whats going on here - don't see errors in the logs and works locally so I am guessing some issue just on writing the file. Any common mistakes I should look for @shawntabrizi

Note that for now (8a814ab) I have just copy and pasted the kusama weights in for rococo

**Comment by emostov** [comment]
/benchmark runtime westend runtime_parachains::paras_inherent

**Comment by emostov** [comment]
/benchmark runtime custom --chain=rococo-dev --steps=50 --repeat=20 --pallet=runtime_parachains::paras_inherent --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs --header=./file_header.txt

**Comment by emostov** [comment]
/benchmark runtime westend runtime_parachains::paras_inherent

**Review by drahnr — APPROVED** [review]

**Comment by emostov** [comment]
/benchmark runtime custom --chain=rococo-dev --steps=50 --repeat=20 --pallet=runtime_parachains::paras_inherent --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs --header=./file_header.txt

**Comment by emostov** [comment]
/benchmark runtime custom --chain=rococo-dev --steps=50 --repeat=20 --pallet=runtime_parachains::paras_inherent --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs --header=./file_header.txt

**Comment by emostov** [comment]
/benchmark runtime custom --chain=rococo-dev --steps=50 --repeat=20 --pallet=runtime_parachains::paras_inherent --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs --header=./file_header.txt

**Comment by emostov** [comment]
bot merge

**Pull request merged**
