### PR TITLE
bump zombienet version, support new weights

### PR DESCRIPTION
**Pull request by pepoviola**
Add support for weights changes (https://github.com/paritytech/substrate/pull/12138).

### CODE REVIEW

**Review by ordian — APPROVED** [review]

**Comment by ordian** [comment]
The new table output looks very nice :)

The `gitlab-zombienet-test-parachains-upgrade-smoke-test` is failing though.

**Comment by ordian** [comment]
Probably has to do with https://github.com/paritytech/substrate/pull/12157 and https://github.com/paritytech/polkadot/pull/5964.

**Review by bkchr — APPROVED** [review]

**Review by sandreim — APPROVED** [review]

**Comment by pepoviola** [comment]
> Probably has to do with [paritytech/substrate#12157](https://github.com/paritytech/substrate/pull/12157) and #5964.

Thanks @ordian!  Yes, make sense. I will revert to adjust the `js` script to fix that.

**Comment by pepoviola** [comment]
Closing here, since the weight change was removed in https://github.com/paritytech/substrate/pull/12157.

**Pull request closed without merging**
