### PR TITLE
flatten dispute-coordinator 'real' module.

### LINKED ISSUE #5184: Remove dummy dispute-coordinator implementation
After #5182 this is dead code. The `dummy` implementation should be removed and the `real` subdirectory flattened.

### PR DESCRIPTION
**Pull request by rphmeier**
Closes #5184. This is mostly just moving code out of the `real` folder, with some small tweaks to imports and the lib.rs file.

### CODE REVIEW

**Review by eskimor — CHANGES_REQUESTED** [review]
Just requesting changes, so we don't accidentally merge this yet.

**Comment by rphmeier** [comment]
@eskimor Which PR do you mean? I wasn't aware of any that would conflict.

**Comment by eskimor** [comment]
yeah, sorry - it is not up yet. I still have to fix a few tests.

**Comment by rphmeier** [comment]
Ok. Ball's in your court for merging this one

**Review by eskimor — APPROVED** [review]

**Comment by eskimor** [comment]
bot merge

**Review by ordian — APPROVED** [review]

**Comment by ordian** [comment]
bot merge

**Pull request merged**
