### PR TITLE
Migrate Staking pallet to v13

### PR DESCRIPTION
**Pull request by Ank4n**
~~Companion~~ Related to https://github.com/paritytech/substrate/pull/12728.
Changes how staking pallet maintains versioning to the new standard way.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2097484

**Review by kianenigma — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2174388

**Comment by Ank4n** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2206092

**Review by ggwpez — APPROVED** [review]
This is not a companion, so you can already merge the Substrate without linking this as companion.  
The CI will probably fail until https://github.com/paritytech/polkadot/pull/6491 works.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2218436

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2218615

**Review by bkchr — APPROVED** [review]

**Pull request merged**
