### PR TITLE
Companion PR to Substrate #5680

### PR DESCRIPTION
**Pull request by apopiak**
https://github.com/paritytech/substrate/pull/5680

### CODE REVIEW

**Comment by apopiak** [comment]
This branch builds fine locally (with `cargo build`) except for this diff:
```
diff --git a/parachain/src/wasm_executor/mod.rs b/parachain/src/wasm_executor/mod.rs
index 64c27278..a7fd92c4 100644
--- a/parachain/src/wasm_executor/mod.rs
+++ b/parachain/src/wasm_executor/mod.rs
@@ -183,7 +183,6 @@ pub fn validate_candidate_internal<E: Externalities + 'static>(
 		// TODO: Make sure we don't use more than 1GB: https://github.com/paritytech/polkadot/issues/699
 		Some(1024),
 		HostFunctions::host_functions(),
-		false,
 		8
 	);
 	let res = executor.call_in_wasm(
@@ -192,6 +191,7 @@ pub fn validate_candidate_internal<E: Externalities + 'static>(
 		"validate_block",
 		encoded_call_data,
 		&mut ext,
+		sp_core::traits::MissingHostFunctions::Allow
 	)?;
 
 	ValidationResult::decode(&mut &res[..]).map_err(|_| Error::BadReturn.into())
```
which seems unrelated to my changes.

**Comment by andresilva** [comment]
Merge master into your branch once #1026 is merged and it should be fixed.

**Comment by andresilva** [comment]
Added this to #1012 as there was a cyclic dependency here.

**Comment by apopiak** [comment]
sure

**Pull request closed without merging**
