### PR TITLE
Re-enable metadata compare CI check

### PR DESCRIPTION
**Pull request by jacogr**
Adds removed CI check in https://github.com/paritytech/polkadot/pull/3336/commits/f512c860b1fcd906575f13479177c95c0b0cfb29

Possible after https://github.com/polkadot-js/tools/releases/tag/v0.46.1

Closes https://github.com/paritytech/polkadot/issues/3854

### CODE REVIEW

**Review by ordian — APPROVED** [review]

**Comment by ordian** [comment]
https://gitlab.parity.io/parity/polkadot/-/jobs/1128287
> Error: PortableRegistry: Unable to find type with lookupId 298
    at assert (/usr/local/lib/node_modules/@polkadot/metadata-cmp/node_modules/@polkadot/util/assert.cjs:34:11)
    at Map.getSiType (/usr/local/lib/node_modules/@polkadot/metadata-cmp/node_modules/@polkadot/types/generic/PortableRegistry.cjs:291:22)
    at /usr/local/lib/node_modules/@polkadot/metadata-cmp/compare.cjs:168:86
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@polkadot/metadata-cmp/compare.cjs:149:36
    at Array.forEach (<anonymous>)
    at main (/usr/local/lib/node_modules/@polkadot/metadata-cmp/compare.cjs:97:34)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at runNextTicks (node:internal/process/task_queues:63:3)
    at processImmediate (node:internal/timers:437:9)

**Comment by jacogr** [comment]
The above is worrying .... need to have a look, replicate (have not been able to do so when testing) and fix before this goes in.

**Comment by jacogr** [comment]
Sorry for the run-about, it should be fixed after https://github.com/polkadot-js/tools/releases/tag/v0.46.2 (at least could replicate a similar issue isn _some_ cases, this is not fixed in the latest package release)

**Comment by ordian** [comment]
https://gitlab.parity.io/parity/polkadot/-/jobs/1129384
other than
> API/INIT: RPC methods not decorated: childstate_getStorageEntries

it looks good now :+1:

**Comment by jacogr** [comment]
Yes, the above is logged at https://github.com/polkadot-js/api/issues/3978 - it seems I missed that PR in substrate. (The warning it there as a reminder that it _should_ be done, rather than it is _broken_ because it doesn't have it)

**Pull request merged**
