### PR TITLE
Set polkadot version in one place

### PR DESCRIPTION
**Pull request by gilescope**
Rust 1.64 enables workspace properties ( https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table ).

No need to bump version numbers by script any more ( https://github.com/paritytech/release-engineering/blob/master/scripts/release-lib.sh#L644 ),  we can just set it in one place.

I'm sure there are other ways we can make use of the new capabilities in 1.64, but this seems like a sensible first step.

### CODE REVIEW

**Comment by gilescope** [comment]
Hmm CI only has rust 1.62.

**Review by bkchr — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]

**Review by kianenigma — APPROVED** [review]

**Comment by gilescope** [comment]
Please wait till Chevor gives the nod before we merge this.

**Comment by ordian** [comment]
Can we reuse `authors`, `edition` and set `repository` to `https://github.com/paritytech/polkadot`?

**Comment by chevdor** [comment]
Let me line up a PR for the release scripts.

I see you did not include:
- orchestra-proc-macro
- orchestra
- prioritized-metered-channel

to the list of crates following the workspace version which is a **good** thing. cc @drahnr

**Review by coderobe — APPROVED** [review]

**Review by chevdor — APPROVED** [review]
There is a fix lined up for the release scripts.

**Comment by chevdor** [comment]
FYI: I published a new binary for `toml-cli` to support the new format: https://github.com/chevdor/toml-cli/releases/tag/v0.2.2

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2075087

**Comment by gilescope** [comment]
FYI cargo-spellcheck is getting updated to support this: https://github.com/drahnr/cargo-spellcheck/pull/284

**Comment by gilescope** [comment]
Going to wait to merge this till after barcamp/sub0 as there's bound to be at least another tool that wasn't expecting this change.

**Comment by joao-paulo-parity** [comment]
This was brought to my attention by @chevdor (thanks for pinging me on this).

In lieu of https://github.com/paritytech/release-engineering/issues/120 I'm wondering about how this is supposed to interact with **individual** crate releases. While that ticket is about Substrate and this is about Polkadot, I'm wondering if we'll be interested in releasing Polkadot crates in the future as well.

First an aside on why it's relevant to maintain per-package `version`. Before releasing a crate we bump its version **individually** (and that is unrelated to the workspace's version). Logically, in order to perform the bump we need to know what's the crate's highest published version, which is commonly tracked by the source code (see https://github.com/dtolnay/syn/commit/78fa618e96e26856d108089cd849e69d25ff3181 for example). It's not _necessary_, however, to imprint the crate's highest published version in the source code because that can be figured out by querying `https://crates.io/api/v1/crates/$CRATE/versions`; the [upcoming publishing automation](https://github.com/paritytech/release-engineering/issues/122) makes use of that endpoint, thus it can figure out the highest published version by itself and therefore we wouldn't need to [manually track the version through the source code](https://github.com/paritytech/substrate/pull/12599), nor need to maintain per-package `version`.

By the PR's description I infer that this change is catered to the release processes we have currently, not the "individual crate releases" use-case. We should consider if it obstructs the latter. I think it doesn't because, as explained, the automation can figure out how to bump a crate's version by querying `https://crates.io/api/v1/crates/$CRATE/versions` even if the crate doesn't have a `version` field in its `Cargo.toml`; i.e. the automation would disregard `workspace.package.version` and set the crate's `version` field, based on `https://crates.io/api/v1/crates/$CRATE/versions`, before publishing. Not having per-package `version` might even be beneficial to the "individual crate releases" use-case because we wouldn't have to submit a PR for updating the `Cargo.toml`s after crates are published (https://github.com/paritytech/release-engineering/issues/124).

My conclusion is that it's worthwhile to give this a shot because I don't see how it would obstruct the crate releases automation, although the process would become more contrived and unintuitive. Even if we run into some broken/unintended interaction resulting from this change, the automation could remove the new features and normalize the `Cargo.toml`s before publishing, which would effectively work around the problem.

**Comment by gilescope** [comment]
bot merge

**Pull request merged**
