### PR TITLE
[CI] Move check_labels to github actions

### PR DESCRIPTION
**Pull request by s3krit**
As per @bkchr 's request, this allows us to run the job when editing labels, meaning the dev doesn't have to re-run the job in gitlab after applying labels.

@TriplEight  Could you please remove `continuous-integration/gitlab-check-labels` as a required status check in the `master` branch protection rules please, and add this new Github actions in its place? Cheers

### CODE REVIEW

**Comment by TriplEight** [comment]
Changed the required status in branch protection.

**Review by TriplEight — COMMENTED** [review]
Why didn't you remove the gitlab job then?

**Comment by s3krit** [comment]
Because I'm dumb :P done

**Review by TriplEight — APPROVED** [review]
Ahh I see

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
