### PR TITLE
[companion] Fix request-response protocols backpressure mechanism

### PR DESCRIPTION
**Pull request by dmitry-markin**
Companion for https://github.com/paritytech/substrate/pull/14199.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2881517

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2881562

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2882127

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2882455

**Review by altonen — APPROVED** [review]

**Comment by lexnv** [comment]
This patch has raced with the companion: https://github.com/paritytech/polkadot/pull/7268.

I believe we should merge them in order to unblock the companion's CI. 

I've cherry-picked your commits on my branch, let's see if the CI passes then

**Comment by dmitry-markin** [comment]
> This patch has raced with the companion: #7268.
> 
> I believe we should merge them in order to unblock the companion's CI.
> 
> I've cherry-picked your commits on my branch, let's see if the CI passes then

Thanks!

**Pull request merged**
