### PR TITLE
Companion for substrate#11469

### PR DESCRIPTION
**Pull request by koushiro**
cumulus companion: https://github.com/paritytech/cumulus/pull/1281

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by niklasad1 — APPROVED** [review]

**Review by shawntabrizi — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge force

**Comment by bkchr** [comment]
bot force merge

**Comment by niklasad1** [comment]
bot merge

**Pull request merged**
