### PR TITLE
availability recovery: measure re-encoding time

### PR DESCRIPTION
**Pull request by sandreim**
`reconstructed_data_matches_root` is expensive and mandatory to be called.  Even when fetching from backers, recovery time seems to be rather high for 2.5MB PoVs (testing in context of https://github.com/paritytech/polkadot/issues/7324).

Screenshot 2023-06-21 at 14 54 32

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3041495

**Comment by sandreim** [comment]
Burned this in on Versi, and can already say it looks like a neat CPU burner task, and considering this doesn't run in a blocking task it actually blocks the async scheduler.

Screenshot 2023-06-21 at 15 46 26

**Review by eskimor — APPROVED** [review]

**Review by bredamatt — APPROVED** [review]

**Review by vstakhov — APPROVED** [review]

**Comment by sandreim** [comment]
bot merge

**Comment by burdges** [comment]
We could definitely run this in a separate thread since it simply returns valid or invalid.

We never figured out the optimal extension field tower for the erasure coding, but this work could be done.  I've no idea how much it'd save, maybe only like 10% though.

**Pull request merged**
