### PR TITLE
Update substrate to master

### PR DESCRIPTION
**Pull request by DemiMarie-parity**
The tests fail.  This needs fixing.

### CODE REVIEW

**Comment by andresilva** [comment]
Branch `v0.3` is also updated to latest master, there's some stuff in there we might want to pull to master.

**Comment by andresilva** [comment]
Relevant PRs: #188 #183 #177 #175

**Comment by andresilva** [comment]
Another one #190.

**Comment by bkchr** [comment]
I'm working on this and hopefully will finish it soon.

**Comment by bkchr** [comment]
Superseded by https://github.com/paritytech/polkadot/pull/195

**Pull request closed without merging**
