### PR TITLE
update weights (0.9.37)

### PR DESCRIPTION
**Pull request by coderobe**

### CODE REVIEW

**Comment by coderobe** [comment]
oop, wrong branch

**Review by ggwpez — COMMENTED** [review]
The diff looks familiar, especially because of the -100% bounty benches.  
Did we not merge it last time?

**Comment by coderobe** [comment]
> The diff looks familiar, especially because of the -100% bounty benches. Did we not merge it last time?

It didn't make its way back to master i think, so you'd have to diff against the previous release branch to get the effective real diff

**Comment by coderobe** [comment]
I'll sync master with this release branch once this is in

**Comment by coderobe** [comment]
lgtm compared to .36

**Review by EgorPopelyaev — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
>It didn't make its way back to master i think, so you'd have to diff against the previous release branch to get the effective real diff

:+1:

**Review by chevdor — APPROVED** [review]
Very similar to .36 besides a jump of `system.remark` for rococo. LGTM.

**Pull request merged**
