### PR TITLE
Add xcm context to weight trader

### PR DESCRIPTION
**Pull request by gilescope**
(This is needed for paying xcm fees via asset conversion)

Cumulus companion: https://github.com/paritytech/cumulus/pull/2954

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3291872

**Comment by gilescope** [comment]
Should be an optional context as there's not always an xcm context.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3292059

**Comment by bkontur** [comment]
I have this also on my TODO list :),
I discussed this few weeks ago with Gav here: https://github.com/paritytech/cumulus/pull/2601#issuecomment-1561346944
so traits used by XcmExecutor should have XcmContext (not optional)

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3296888

**Comment by bkontur** [comment]
@gilescope 
there is no reason to make it `Optional` for trader: https://github.com/paritytech/polkadot/pull/7563,
and I think we should better do it required like here https://github.com/paritytech/polkadot/pull/7563
and create a clean companion to Cumulus master directly

**Comment by bkontur** [comment]
there is only one case with `&Option<XcmContext>` [here](https://github.com/paritytech/polkadot/blob/master/xcm/xcm-executor/src/traits/transact_asset.rs#L88-L96),
but `Trader` is not that case and XcmContext is always there

**Comment by gilescope** [comment]
Superseded by https://github.com/paritytech/polkadot/pull/7563 - apparently we don't need to make it optional

**Pull request closed without merging**
