### PR TITLE
New Rococo genesis

### PR DESCRIPTION
**Pull request by bkchr**

### CODE REVIEW

**Review by andresilva — APPROVED** [review]

**Comment by andresilva** [comment]
Should we maybe update `protocolId` as well?

**Comment by bkchr** [comment]
Why?

**Comment by andresilva** [comment]
To avoid having peers from the existing rococo network try to connect to us. It doesn't make much of a difference since genesis hash won't match, but I think the DHT will also be merged.

**Comment by bkchr** [comment]
We never have done this before, so I think it is fine do ignore it here as well :D

**Comment by andresilva** [comment]
bot merge

**Pull request merged**
