### PR TITLE
kusama: enable dispute slashes

### PR DESCRIPTION
**Pull request by ordian**
This PR enables initial slashing for disputes on Kusama.
See #6249 for its current limitations.

### CODE REVIEW

**Comment by ordian** [comment]
/cmd queue -c bench-bot $ runtime kusama-dev runtime_parachains::disputes::slashing

**Comment by ordian** [comment]
/cmd queue -c bench-bot $ runtime kusama-dev runtime_parachains::disputes::slashing

**Review by eskimor — APPROVED** [review]

**Comment by ordian** [comment]
/cmd queue -c bench $ pallet kusama-dev runtime_parachains::disputes::slashing

**Comment by ordian** [comment]
/cmd queue -c bench $ runtime kusama-dev runtime_parachains::disputes::slashing

**Comment by ordian** [comment]
bot rebase

**Review by tdimitrov — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Review by BradleyOlson64 — APPROVED** [review]
Looks good 👍

**Comment by ordian** [comment]
bot help

**Comment by ordian** [comment]
bot bench $ runtime kusama runtime_parachains::disputes::slashing

**Pull request merged**
