### PR TITLE
[don't merge] try-runtime testing

### PR DESCRIPTION
**Pull request by coderobe**

### CODE REVIEW

**Comment by coderobe** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=polkadot-dev --execution=Wasm on-runtime-upgrade live --uri wss://polkadot-try-runtime-node.parity-chains.parity.io:443

**Comment by coderobe** [comment]
/cmd queue -v RUST_LOG=remote-ext=debug,runtime=trace -c try-runtime $ --chain=kusama-dev --execution=Wasm on-runtime-upgrade live --uri wss://kusama-try-runtime-node.parity-chains.parity.io:443

**Comment by ggwpez** [comment]
It reports `spec version mismatch (local 9230 != remote 9200). This could cause some issues`, but when I query the version of that node, it prints `0.9.22-17c7b9594ae`.  
Something does not add up here. 

Context from that:  
The hex encoded key is `74dd702da46f77d7acf77f5a48d4af7d62556a85fcb7c61b2c6c750924846b15fff521c596a7dfc12278719c553e765370a1d3d8cf5c245b06bd8ac8fc0491f18270f2c1a51d5876`. Longest prefix for that is `74dd702da46f77d7acf77f5a48d4af7d62556a85fcb7c61b2c6c750924846b15` with key `voterList listNodes`.

**Comment by dvdplm** [comment]
@ggwpez Seems like the last run finished successfully?

```
2022-05-31 12:11:49.308  INFO main try-runtime::cli: TryRuntime_on_runtime_upgrade executed without errors. Consumed weight = 18446744073709551615, total weight = 2000000000000 (9223372.036854776) 
```

**Comment by ggwpez** [comment]
k> @ggwpez Seems like the last run finished successfully?

It still errors with a decode error. But now at-least the spec version is right. I assume the last Kusama rutime was not live as @coderobe ran the last migration.  
It therefore skipped one runtime and printed a version different from now, so I could not reproduce it.  

Now I can locally reproduce it. Maybe has something to do with this https://github.com/paritytech/substrate/pull/11357/files#r885585728

**Comment by ggwpez** [comment]
Okay I think the error can be ignored. The bags-list migration `AddScore` tries to decode the list elements with the old format and then migrates all of the ones where it succeeds to the new format.  
But in this case it prints all the decode errors since it already migrated them successfully in the past.  
I think the errors come from decoding [here](https://github.com/paritytech/substrate/blob/54d6f2cbae12fa314f2bcaf6d57fba585162438f/frame/bags-list/src/migrations.rs#L98) which we could probably change to look less scary.

**Comment by shawntabrizi** [comment]
Yes I agree. As long as the try-runtime migration itself is completing successfully, then you dont need to worry about some random logged errors, which are coming from other places like SP-IO

**Comment by coderobe** [comment]
Ok, so we can continue with the release?

**Comment by ggwpez** [comment]
> Ok, so we can continue with the release?

The migration works fine so I think so.

**Pull request closed without merging**
