### PR TITLE
upgrade libp2p to 0.50.0

### PR DESCRIPTION
**Pull request by melekes**
Bump asyncronous-codec, rustls, ipnet, once_cell and futures (+dependent crates) crate versions (companion to https://github.com/paritytech/substrate/pull/12734).

cumulus companion: https://github.com/paritytech/cumulus/pull/2056

### CODE REVIEW

**Review by bkchr — CHANGES_REQUESTED** [review]
No `cargo update` please. Please revert

**Comment by melekes** [comment]
> No `cargo update` please. Please revert

at all? can I still update individual crates?

**Comment by bkchr** [comment]
> > No `cargo update` please. Please revert
> 
> at all? can I still update individual crates?

Yes for sure you can update individual crates. Just the bare "cargo update" run.

**Review by bkchr — APPROVED** [review]

**Review by mrcnski — CHANGES_REQUESTED** [review]
Looks like `libp2p` has not been upgraded?

```toml
[[package]]
name = "libp2p"
version = "0.49.0"
```

**Comment by melekes** [comment]
`continuous-integration/gitlab-check-transaction-versions` job failed with "fatal: Invalid object name 'origin/release'."

**Comment by bkchr** [comment]
> `continuous-integration/gitlab-check-transaction-versions` job failed with "fatal: Invalid object name 'origin/release'."

Ignore it ;)

**Review by mrcnski — APPROVED** [review]

**Comment by ggwpez** [comment]
I linked your Cumulus comp in the description, otherwise the CI will not pick it up.

**Comment by ggwpez** [comment]
Unsure if this could be a legit test failure due to changed libp2p - asking in chat.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2229697

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
