### PR TITLE
av-store: skip processing finalized blocks while major syncing

### PR DESCRIPTION
**Pull request by ordian**
Might help with #6656.

### CODE REVIEW

**Review by sandreim — APPROVED** [review]

**Review by bkchr — APPROVED** [review]
Maybe the overseer itself should not send the signal when major sync is active? Or there could be some extra field in the signal telling you if the signal was generated while doing a major sync.

**Comment by sandreim** [comment]
> Maybe the overseer itself should not send the signal when major sync is active? Or there could be some extra field in the signal telling you if the signal was generated while doing a major sync.

Adding the major sync flag to the signal makes sense to me.

**Comment by ordian** [comment]
submitted https://github.com/paritytech/polkadot/issues/6694 as a follow-up

**Comment by ordian** [comment]
bot merge

**Pull request merged**
