### PR TITLE
companion for #13555

### PR DESCRIPTION
**Pull request by niklasad1**

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2498809

**Review by lexnv — APPROVED** [review]

**Review by ordian — APPROVED** [review]

**Review by kianenigma — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2523210

**Comment by niklasad1** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2524444

**Comment by niklasad1** [comment]
bot merge

**Comment by ggwpez** [comment]
```pre
 error[E0046]: not all trait items implemented, missing: `set_commission`, `set_commission_max`, `set_commission_change_rate`, `claim_commission`
    --> /builds/parity/mirrors/polkadot/runtime/polkadot/src/weights/pallet_nomination_pools.rs:47:1
     |
  47 | impl<T: frame_system::Config> pallet_nomination_pools::WeightInfo for WeightInfo<T> {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `set_commission`, `set_commission_max`, `set_commission_change_rate`, `claim_commission` in implementation
     |
```
should be fixed here https://github.com/paritytech/polkadot/pull/6264 so lets merge.

**Pull request merged**
