### PR TITLE
Backports #5306 #5404 #5405 #5407 for 0.9.20

### PR DESCRIPTION
**Pull request by coderobe**
Bringing https://github.com/paritytech/polkadot/pull/5404, https://github.com/paritytech/polkadot/pull/5405, and https://github.com/paritytech/polkadot/pull/5407 to 0.9.20

### CODE REVIEW

**Comment by coderobe** [comment]
looks like #5405 requires https://github.com/paritytech/substrate/commit/9e41e40c4016deff3a1babccbf7ce3419e966a79 backported in substrate too

**Comment by chevdor** [comment]
The PR adds https://github.com/paritytech/polkadot/pull/5306 as well

**Comment by coderobe** [comment]
(that was pulled in because https://github.com/paritytech/substrate/pull/11318 required the substrate companion to build)

**Review by chevdor — APPROVED** [review]
LGTM
This PR should be rebased and not squashed
image

**Review by EgorPopelyaev — APPROVED** [review]

**Review by dvdplm — APPROVED** [review]

**Review by drahnr — APPROVED** [review]

**Comment by chevdor** [comment]
PLEASE DON'T SQUASH THIS PR

**Pull request merged**
