### PR TITLE
Update Block- and Extrinsic base weights

### PR DESCRIPTION
**Pull request by ggwpez**
Updates the Block / Extrinsic weights from 5ms / 125ms to [ms]:
- Polkadot 4.5 / 82.9
- Kusama 4.17 / 80
- Westend 3.6 / 72.7
- Rococo 3.1 / 74.1

These things are important to verify:
- Uses production profile
- Uses compiled WASM executor
- Uses the correct runtime each time
- Was run on ref hardware (that one is on me :smiley:)

@coderobe we could update this in each release pipeline after #5137 and https://github.com/paritytech/substrate/pull/11091 are done.  
The script will be trivial:  
```sh
for runtime in "polkadot" "kusama" "westend" "rococo"; do
    ./target/production/polkadot benchmark-overhead --chain=$runtime-dev --execution=wasm --wasm-execution=compiled --weight-path=runtime/$runtime/constants/src/weights/ --warmup=10 --repeat=100
done
```

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]
awesome. getting some extra tx per block now :)

**Comment by ggwpez** [comment]
[Some tests](https://github.com/paritytech/polkadot/blob/69971692340de7f4e4a47caadb6ed77231079a0c/runtime/kusama/constants/src/lib.rs#L108) fail that assert that the Block and Ext weight have hard-coded values. Not sure if it still makes sense to have those?   
We have the sanity check in the template now.  @shawntabrizi

**Review by coderobe — APPROVED** [review]
Sounds good, i'll look into integrating this into the release pipeline

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
