### PR TITLE
Properly use weights for the new election pallet

### PR DESCRIPTION
**Pull request by kianenigma**
Follow up to https://github.com/paritytech/polkadot/pull/2476/files

### CODE REVIEW

**Comment by kianenigma** [comment]
/benchmark runtime polkadot pallet_election_provider_multi_phase

**Comment by kianenigma** [comment]
/benchmark runtime polkadot pallet_election_provider_multi_phase

**Comment by kianenigma** [comment]
/benchmark runtime kusama pallet_election_provider_multi_phase

**Comment by kianenigma** [comment]
/benchmark runtime westend pallet_election_provider_multi_phase

**Comment by kianenigma** [comment]
/benchmark runtime polkadot pallet_election_provider_multi_phase

**Comment by kianenigma** [comment]
/benchmark runtime polkadot pallet_election_provider_multi_phase

**Comment by kianenigma** [comment]
blocked on https://github.com/paritytech/substrate/pull/8192

**Comment by kianenigma** [comment]
Unblocked.

**Review by thiolliere — APPROVED** [review]

**Pull request merged**
