### PR TITLE
Upgrade merlin from 2.0.1 to 3.0.0.

### PR DESCRIPTION
**Pull request by sioanis**
Merlin versions: (https://github.com/ocaml/merlin/releases?page=1)

### CODE REVIEW

**Comment by drahnr** [comment]
Given that merlin went through a major version, what does that entail? What's the state of compatibility i.e. proof data layout? CC @burdges

**Comment by burdges** [comment]
Ain't too many changes between the Isis vs HdV forks:
- https://github.com/zkcrypto/merlin/compare/main...dalek-cryptography:master
- https://github.com/dalek-cryptography/merlin/compare/master...zkcrypto:main

I believe the 3.0.0 upgrade resulted from rand's minor version upgrade, which breaks trait compatibility and thus requires a major version upgrade for merlin.

What version of rand does substrate want to be using?  We can choose the merlin version based upon that.

**Comment by sioanis** [comment]
Rand [changelog](https://github.com/rust-random/rand/blob/master/CHANGELOG.md).

**Comment by burdges** [comment]
It's still two minor versions behind?  lol  We can do whatever then I guess.

**Pull request closed without merging**
