### PR TITLE
Update Rococo chainspec to present running netowrk (2.1)

### PR DESCRIPTION
**Pull request by NukeManDan**
Updates `res` folder to present `master` @ da5b6b69
Followup to #5113 

Backport to 0.9.18, as teams are confused what to use now to connect.

### CODE REVIEW

**Comment by rphmeier** [comment]
0.9.18 is already released, so adding the commit to that branch won't do anything. And 0.9.19 will go out tomorrow (hopefully). I think it already includes the right chain spec but if it doesn't we'll have to wait for 0.9.20.

**Comment by NukeManDan** [comment]
OK - 19 includes this, but some teams may still reference and use 18 for collator development, correct? So it still may be a blocker for teams connecting perhaps? There is no harm in doing this, is there?

**Comment by dvdplm** [comment]
Backports are meant to be released so in this case it’d be a `0.9.18.1` or something funny like that. Given we’re not planning anything of that kind I agree with Rob here. If teams really really need to stay on 0.9.18 for some reason they can obviously use a branch with this fix in it until they can switch to later versions.

**Review by coderobe — CHANGES_REQUESTED** [review]
❌  0.9.18 is already released. This should not be merged.

**Comment by rphmeier** [comment]
@NukeManDan i see the perspective of teams being based on the 0.9.18 git commit and that creating issues for Rococo. But they'd have to `cargo update -p polkadot-primitives` to get this change anyway, and after tomorrow that should be about as easy as just updating the git commit ref to 0.9.19.

**Pull request closed without merging**
