### PR TITLE
Use updated bags list: Companion to #10997

### PR DESCRIPTION
**Pull request by emostov**
substrate companion https://github.com/paritytech/substrate/pull/10997

skip check-dependent-cumulus

### CODE REVIEW

**Review by kianenigma — APPROVED** [review]

**Comment by emostov** [comment]
bot merge

**Comment by kianenigma** [comment]
bot merge

**Comment by emostov** [comment]
bot merge

**Comment by ggwpez** [comment]
Error comes from this companion not being merged afaik https://github.com/paritytech/cumulus/pull/1071

**Comment by emostov** [comment]
bot merge

**Pull request merged**
