### PR TITLE
Disable validation/collation protocols for normal full nodes

### PR DESCRIPTION
**Pull request by altonen**
If authority discovery is not enabled, `Overseer` is not enabled, meaning `NetworkBridge` is not started. Validation/collation protocols are, however, enabled even if the `NetworkBridge` is not started.

Currently this results in normal Polkadot full nodes advertising these protocols, accepting inbound substreams and even establishing outbound substreams for the validation protocol. Since the `NetworkBridge` is not started and no protocol in Substrate is interested in these protocol events, the events are relayed to all protocol handlers but are getting discarded because no installed protocol is interested in them.

---
I discussed these changes with @sandreim  and @vstakhov and the conclusion was that it's OK to disable these for Polkadot nodes that don't start the `Overseer` but if there is a reason why these protocols are enabled even if `Overseer` is not, this PR can be closed.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3366641

**Review by eskimor — APPROVED** [review]
Yep, makes sense. Thank you!

**Review by vstakhov — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3374047

**Comment by altonen** [comment]
bot rebase

**Pull request merged**
