### PR TITLE
Dont send approval vote

### PR DESCRIPTION
**Pull request by eskimor**
dont merge, just an experiment

### CODE REVIEW

**Comment by eskimor** [comment]
Not importing approval-votes reduces dispute-coordinator load on Versi from 87%
to 9.4%.

**Comment by eskimor** [comment]
When also disabling imports of backing votes, CPU usage drops even more to 1.8%.

**Comment by sandreim** [comment]
> Not importing approval-votes reduces dispute-coordinator load on Versi from 87% to 9.4%.

Recently, IIRC we were discussing about the possibility of storing only our own votes and requesting/importing them JIT when there is a dispute going on (which is an unlikely event as we've seen, or largely an annoyance in the case of slow validators). This sounds really promising wrt imporving overall performance. Are there other datapoints that could change  this ?

**Comment by eskimor** [comment]
Yes! @rphmeier reminded me of the issue with that approach: In order to raise a dispute you need to be able to provide two opposing votes. If nodes only store their own votes, they might not be able to do that. The solution I have in mind is to only keep backing votes from other nodes as that is cheap, especially when relying on chain scraping (Only 1.8% CPU usage). 

For now, I will continue work on batching though as it should not have any security implications and will also benefit performance of dispute resolutions, which is also important. With that alone we should be able to get CPU usage below 10%, with the only own votes change we should be able to get it to those 1.8%. Which would already be pretty decent and very likely good enough, even long term.

**Comment by sandreim** [comment]
@eskimor do you still need this, or should we close it ?

**Pull request closed without merging**
