### PR TITLE
Companion for Substrate#14373

### PR DESCRIPTION
**Pull request by drskalman**
Companion for https://github.com/paritytech/substrate/pull/14373

cumulus companion: https://github.com/paritytech/cumulus/pull/2739

### CODE REVIEW

**Review by davxy — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3316192

**Review by davxy — APPROVED** [review]

**Review by andresilva — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Review by Lederstrumpf — APPROVED** [review]

**Comment by dmitry-markin** [comment]
This PR is currently blocking cumulus CI, trying restarting `gitlab-check-dependent-cumulus`.

**Comment by dmitry-markin** [comment]
bot merge

**Comment by dmitry-markin** [comment]
Set https://github.com/paritytech/cumulus/pull/2739 as this PR companion, otherwise we are stuck.

**Comment by dmitry-markin** [comment]
bot merge

**Comment by dmitry-markin** [comment]
bot merge

**Comment by drskalman** [comment]
Merging certainly seems harder than the developing the feature itself :-) For one, it is a highly non-deterministic time-sensitive process :-)

**Pull request merged**
