### PR TITLE
Add para pallets to polkadot benchmarks

### PR DESCRIPTION
**Pull request by emostov**

### CODE REVIEW

**Comment by emostov** [comment]
/benchmark runtime polkadot runtime_parachains::configuration

**Comment by shawntabrizi** [comment]
/benchmark runtime polkadot runtime_parachains::configuration

**Comment by shawntabrizi** [comment]
/benchmark runtime polkadot runtime_parachains::configuration

**Comment by KiChjang** [comment]
bot merge

**Pull request merged**
