### PR TITLE
[DO NOT MERGE] test new vm runner for weights 1

### PR DESCRIPTION
**Pull request by alvicsam**
cc https://github.com/paritytech/ci_cd/issues/697

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2227647

**Comment by alvicsam** [comment]
bot rebase

**Comment by alvicsam** [comment]
bot rebase

**Comment by alvicsam** [comment]
bot rebase

**Pull request closed without merging**
