### PR TITLE
Companion for #7789 (BabeApi::current_epoch)

### PR DESCRIPTION
**Pull request by rphmeier**
Just bumps all our BabeApi definitions.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]
You need to revert the branch changes/

**Review by andresilva — CHANGES_REQUESTED** [review]
Good to go once the branch is reverted to master.

**Comment by rphmeier** [comment]
@bkchr I clearly haven't contributed to Substrate in a while :)

**Comment by rphmeier** [comment]
bot merge

**Review by shawntabrizi — APPROVED** [review]

**Pull request merged**
