### PR TITLE
Companion PR to #5560 - Also includes polkadot#979 and polkadot#986

### PR DESCRIPTION
**Pull request by tomaka**
https://github.com/paritytech/substrate/pull/5560

### CODE REVIEW

**Comment by gnunicorn** [comment]
@tomaka test's failing.

**Comment by tomaka** [comment]
> test's failing but that is fine because it is introduced through the substrate PR, right?

I'm not sure exactly how it works here, but yes the build fails because it's relying on the changes in Substrate.

**Comment by bkchr** [comment]
After the Substrate pr is merged, update the `Cargo.lock`, push it and we merge this pr when it is green.

**Comment by tomaka** [comment]
Err.. the build fails because of errors in the runtime.

**Comment by tomaka** [comment]
I merged https://github.com/paritytech/polkadot/pull/979 in this one. The build should hopefully be green.

**Comment by tomaka** [comment]
Also merged https://github.com/paritytech/polkadot/pull/986 here.

**Pull request merged**
