### PR TITLE
[Substrate companion] update libp2p to 0.52.0

### PR DESCRIPTION
**Pull request by melekes**
PR: https://github.com/paritytech/substrate/pull/14429

cumulus companion: https://github.com/paritytech/cumulus/pull/2838

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3139833

**Comment by melekes** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3156258

**Comment by melekes** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3198410

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3198828

**Comment by melekes** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3209316

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3210560

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3212614

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3217127

**Comment by melekes** [comment]
```
[2023-07-19 06:52:13] error: failed to select a version for `sha2`.
[2023-07-19 06:52:13]     ... required by package `sp-core-hashing v9.0.0 (/builds/parity/mirrors/substrate/primitives/core/hashing)`
[2023-07-19 06:52:13]     ... which satisfies path dependency `sp-core-hashing` of package `sp-core v21.0.0 (/builds/parity/mirrors/substrate/primitives/core)`
[2023-07-19 06:52:13]     ... which satisfies path dependency `sp-core` of package `frame-benchmarking v4.0.0-dev (/builds/parity/mirrors/substrate/frame/benchmarking)`
[2023-07-19 06:52:13]     ... which satisfies path dependency `frame-benchmarking` of package `frame-benchmarking-cli v4.0.0-dev (/builds/parity/mirrors/substrate/utils/frame/benchmarking-cli)`
[2023-07-19 06:52:13]     ... which satisfies git dependency `frame-benchmarking-cli` (locked to 4.0.0-dev) of package `polkadot-cli v0.9.43 (/builds/parity/mirrors/substrate/companions/polkadot/cli)`
[2023-07-19 06:52:13]     ... which satisfies path dependency `polkadot-cli` (locked to 0.9.43) of package `polkadot v0.9.43 (/builds/parity/mirrors/substrate/companions/polkadot)`
[2023-07-19 06:52:13] versions that meet the requirements `^0.10.7` are: 0.10.7
[2023-07-19 06:52:13] 
[2023-07-19 06:52:13] all possible versions conflict with previously selected packages.
[2023-07-19 06:52:13] 
[2023-07-19 06:52:13]   previously selected package `sha2 v0.10.6`
[2023-07-19 06:52:13]     ... which satisfies dependency `sha2 = "^0.10.2"` (locked to 0.10.6) of package `tiny-bip39 v1.0.0`
[2023-07-19 06:52:13]     ... which satisfies dependency `tiny-bip39 = "^1.0.0"` (locked to 1.0.0) of package `sc-cli v0.10.0-dev (/builds/parity/mirrors/substrate/client/cli)`
[2023-07-19 06:52:13]     ... which satisfies path dependency `sc-cli` of package `frame-benchmarking-cli v4.0.0-dev (/builds/parity/mirrors/substrate/utils/frame/benchmarking-cli)`
[2023-07-19 06:52:13]     ... which satisfies git dependency `frame-benchmarking-cli` (locked to 4.0.0-dev) of package `polkadot-cli v0.9.43 (/builds/parity/mirrors/substrate/companions/polkadot/cli)`
[2023-07-19 06:52:13]     ... which satisfies path dependency `polkadot-cli` (locked to 0.9.43) of package `polkadot v0.9.43 (/builds/parity/mirrors/substrate/companions/polkadot)`
```

don't understand why cargo refuses to update `sha2` to `0.10.7`?

**Comment by altonen** [comment]
I get similar error but for `smallvec`

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3218231

**Review by dmitry-markin — APPROVED** [review]

**Review by altonen — APPROVED** [review]

**Comment by melekes** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3252535

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3253611

**Comment by melekes** [comment]
bot rebase

**Comment by ordian** [comment]
bot merge

**Comment by ordian** [comment]
bot merge

**Pull request merged**
