### PR TITLE
Update mmr pallet to FRAME v2

### PR DESCRIPTION
**Pull request by shaunxw**
Part of #2882 

Converts the `Mmr` pallet to the new pallet attribute macro introduced in #6877.

Following the upgrade guidelines here: https://crates.parity.io/frame_support/attr.pallet.html#upgrade-guidelines.

## ⚠️ Breaking Change ⚠️ 

From https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines

> storages now use PalletInfo for module_prefix instead of the one given to decl_storage: Thus any use of this pallet in construct_runtime! should be careful to update name in order not to break storage or to upgrade storage (moreover for instantiable pallet). If pallet is published, make sure to warn about this breaking change.

So users of the `Mmr` pallet must be careful about the name they used in `construct_runtime!`. Hence the `runtime-migration` label, which might not be needed depending on the configuration of the `Mmr` pallet.

### CODE REVIEW

**Review by KiChjang — APPROVED** [review]

**Comment by shawntabrizi** [comment]
Pallet MMR does not seem to be used anywhere in Polkadot or Cumulus runtimes.

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Comment by tomusdrw** [comment]
CC @musnit @denalimarsh @philipstanislaus when Rococo&Wococo is upgrade to this new format it might change the storage keys / storage proofs for you.

**Comment by philipstanislaus** [comment]
Thanks for the note, also pinging @vgeddes and @Rizziepit here

**Pull request merged**
