### PR TITLE
technical committee is using the weight of council, but should have its own generated weight instead

### PR DESCRIPTION
**Pull request by thiolliere**
currently technical committee is using the weight of council, but should have its own generated weight instead

when I read https://substrate.dev/rustdocs/latest/frame_benchmarking/macro.add_benchmark.html I see that in case of instances the path is the concatenation of both pallet path and pallet name

cc @shawntabrizi

* [x] requires https://github.com/paritytech/substrate/pull/9626

### TODO

Rerun benchmarks:

* [x] benchmark runtime polkadot pallet_collective
* [x] benchmark runtime kusama pallet_collective

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Comment by thiolliere** [comment]
the bot generates an implementation of the trait which is incomplete, I need to look into it

**Comment by thiolliere** [comment]
actually I think we should simply use unique names, the doc given on add_benchmark is confusing to me as I don't understand in which context does the output file name get the suffix. And I think having multiple benchmark with the same name is making this weird result.

Instead I know use unique names for each pallets.

**Comment by thiolliere** [comment]
/benchmark runtime polkadot pallet_collective_technical_committee

**Comment by thiolliere** [comment]
/benchmark runtime polkadot pallet_collective_technical_committee

**Comment by thiolliere** [comment]
ah but this still doesn't work, because it writes: 
```
impl<T: frame_system::Config> pallet_collective_council::WeightInfo for WeightInfo<T> {
```
where I want
```
impl<T: frame_system::Config> pallet_collective::WeightInfo for WeightInfo<T> {
```

Maybe we should give an optional name to add_benchmark/list_benchmark for giving a unique name for the benchmark which is different from the pallet name. :-/

**Comment by thiolliere** [comment]
this should be now good to go

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
thanks for figuring out the issues with the pipeline

**Comment by thiolliere** [comment]
bot merge

**Review by apopiak — APPROVED** [review]

**Comment by thiolliere** [comment]
bot merge

**Pull request merged**
