### PR TITLE
availability-recovery: use `IfDisconnected::TryConnect` for chunks

### PR DESCRIPTION
**Pull request by ordian**
I was looking at how https://github.com/paritytech/cumulus/blob/master/client/pov-recovery works and it seems to me that it doesn't unless I'm overlooking something obvious.

[Here](https://github.com/paritytech/cumulus/blob/9f09698a07ec6ace3351138292153aef23e13bd6/client/pov-recovery/src/active_candidate_recovery.rs#L54-L63) we issue a recovery request without backing fast-path, so it will try to request chunks from all validators. 

But you need to be connected ~~over `/validation/1` peerset, which has limited number of slots (up to 10) for non-validators. And these connection requests are only issued in `gossip-support` only for validators if `IfDisconnected::ImmediateError` is used.~~ to at least 1/3 of validators for the recovery to work.

I've changed that to `IfDisconnected::TryConnect` (only for chunk requests).

Related https://github.com/paritytech/cumulus/issues/1423.

cumulus companion: https://github.com/paritytech/cumulus/pull/1711

- [x] fix tests
- [x] ensure companion works

### CODE REVIEW

**Comment by bkchr** [comment]
Hmm, given the docs and your explanation it sounds sensible. So, this only works in our tests because all nodes are already connected? 

We have a zombienet test, could you please make one validator being only connected to one other validator using `--reserved-nodes`? Then this test should fail and start working with your test.

**Comment by ordian** [comment]
> We have a zombienet test, could you please make one validator being only connected to one other validator using --reserved-nodes? Then this test should fail and start working with your test.

I assume you mean [this](https://github.com/paritytech/cumulus/blob/master/zombienet_tests/0002-pov_recovery.toml) test. Interesting. Last time I talked to @eskimor about req/resp protocols, our understanding was that it needs a connections specifically over `/validation/1` peerset, not just `--reserved-nodes`. Looks like that assumption is not correct. But even if not, we'd still need that change in polkadot to make it work for collators.

**Comment by bkchr** [comment]
I mean the docs are talking about peer:
```
/// When sending a request, what to do on a disconnected recipient.
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum IfDisconnected {
	/// Try to connect to the peer.
	TryConnect,
	/// Just fail if the destination is not yet connected.
	ImmediateError,
}
```

What I meant with my changes is that currently on the zombienet test we are probably connected to all peers. So, when we do this request on the validation peerset, we actually already have a connection to the peer, but not yet on the validation peerset.

**Comment by bkchr** [comment]
> But even if not, we'd still need that change in polkadot to make it work for collators.

Which is fine and I'm not against the fix ;) I just want to have a regression test that this behavior not is coming back by accident.

**Comment by ordian** [comment]
> > But even if not, we'd still need that change in polkadot to make it work for collators.
> 
> Which is fine and I'm not against the fix ;) I just want to have a regression test that this behavior not is coming back by accident.

Yes, I'll tweak the test to see if it work with 1 peer connection.

**Comment by eskimor** [comment]
No the peerset does not matter -as long as some connection exists, req/resp. works.

**Review by eskimor — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by ordian** [comment]
bot merge

**Pull request merged**
