### PR TITLE
Companion for #14178: Update color-eyre to v0.6.2

### PR DESCRIPTION
**Pull request by lexnv**
Companion for: https://github.com/paritytech/substrate/pull/14178

cumulus companion: https://github.com/paritytech/cumulus/pull/2623

// @paritytech/subxt-team

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2873983

**Review by bkchr — APPROVED** [review]

**Review by koute — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2882685

**Review by niklasad1 — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2884606

**Comment by lexnv** [comment]
This PR has been effectively handled by Cargo.lock update in https://github.com/paritytech/polkadot/pull/7276/commits/d0d50f3f0b04dfe6fa5712b978906cee79f0b96b from https://github.com/paritytech/polkadot/pull/7276. 

Closing this as duplicate, the companion CI is passing for that merged PR.

**Pull request closed without merging**
