### PR TITLE
[WIP] migrate unmigrated claims

### PR DESCRIPTION
**Pull request by joshua-mir**
Rel: #932, #910

236 accounts on
the claims pallet currently remain unmigrated because they were omitted from `claims.scale` 

This PR reintroduces migration code to migrate these accounts.

TODO:

- [ ] identify 236 accounts from [the polkascan scrapes](https://gist.github.com/emielvanderhoek/5c68b9da5444d15b62936dee9c3d0d48) which need to be migrated (235 have been identified so far, remaining one does not appear to correspond to any known DOT allocation on ethereum.)
- [ ] convert  [identified accounts](https://github.com/paritytech/polkadot/files/4481915/identified.txt) into a `claims.scale` file.

Alternatively to this PR: we can call batch mint_claims for these accounts, and kill their old keys.

### CODE REVIEW

**Comment by bkchr** [comment]
Couldn't this be done by an council motion that sets the data in the storage directly?

**Comment by joshua-mir** [comment]
I'm personally okay with minting new claims and killing all old keys

**Comment by emielvanderhoek** [comment]
I am okay with that too as long as we are 100% transparent about what happened. That seems like the easiest way to make those impacted happy (again). That said, I’ll leave it to the experts.

**Comment by joshua-mir** [comment]
closing in favor of a council proposal

**Pull request closed without merging**
