### PR TITLE
Companion for substrate#14471

### PR DESCRIPTION
**Pull request by andresilva**

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3080300

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3080633

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3080797

**Review by koute — APPROVED** [review]

**Review by davxy — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Review by skunert — APPROVED** [review]

**Comment by ggwpez** [comment]
Test failure here @andresilva in `running_the_node_works_and_can_be_interrupted` https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3212284

I will merge https://github.com/paritytech/polkadot/pull/7507 into here - otherwise there will be a companion deadlock again 🤦‍♂️

**Review by franciscoaguirre — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3213518

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
