### PR TITLE
Companion: Substrate#13869

### PR DESCRIPTION
**Pull request by bkchr**
https://github.com/paritytech/substrate/pull/13869

cumulus companion: https://github.com/paritytech/cumulus/pull/2631

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2718536

**Review by ggwpez — APPROVED** [review]

**Review by ordian — APPROVED** [review]

**Review by eskimor — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2886954

**Review by sam0x17 — APPROVED** [review]

**Comment by bkchr** [comment]
bot fmt

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
