### PR TITLE
Revert "req/resp: use IfDisconnected::ImmediateError (#4253)"

### PR DESCRIPTION
**Pull request by rphmeier**
This reverts commit c18d42d495d686979d96c1777628064ca074bc35.

### CODE REVIEW

**Comment by rphmeier** [comment]
I will present some graphs, scraped with github.com/ordian/kuddelmuddel from Kusama

There are 2 sets of 2 graphs showing the amount of block delay for backing and availability. The first set is at approximately block 11,000,000 (before 0.9.16). The second set is at approximately block 11,630,000 or around now.

## Backing and Inclusion at 11,000,000 on Kusama

11005000-backing-2023
11005000-inclusion-2023

## Backing and Inclusion at 11,630,000 on Kusama

11630000-backing-2023
11630000-inclusion-2023


We can see that both backing and availability have gotten markedly worse, not just backing. This is consistent with the theories in https://github.com/paritytech/polkadot/issues/4911 
  1. The issues are validator-side, not collator-side
  2. The issues manifested in 0.9.16

**Review by ordian — APPROVED** [review]
Thanks for the confirmation. It seem to indicate authority discovery doesn't work well?

**Comment by rphmeier** [comment]
Quite possibly. Either that or reserved peers.

**Comment by rphmeier** [comment]
stale, unwanted? definitely obsolete

**Pull request closed without merging**
