### PR TITLE
Companion PR for `Add a `DefaultQueue` type alias to remove the need to use `sp_api::TransactionFor``

### PR DESCRIPTION
**Pull request by expenses**
https://github.com/paritytech/substrate/pull/6761

### CODE REVIEW

**Comment by expenses** [comment]
Is there a way to get the substrate PR merged without switching the branch on this one temporarily so the tests pass?

**Comment by bkchr** [comment]
You don't need to have tests passed here.

**Comment by andresilva** [comment]
The tests here shouldn't need to pass for the substrate companion build to pass, I think it only checks whether this PR is mergeable or not (without enforcing all CI tasks here are green).

**Comment by cecton** [comment]
> Is there a way to get the substrate PR merged without switching the branch on this one temporarily so the tests pass?

I have a PR that fixes that. All the tests here will be green. (for all future companion pr) #1455

**Pull request merged**
