### PR TITLE
Remove migration done by runtime version 9090

### PR DESCRIPTION
**Pull request by thiolliere**
Remove migration done by runtime version 9090 or 9100.

To be merged once polkadot have migrated

### CODE REVIEW

**Comment by gavofyork** [comment]
polkadot is still 9080 - won't this need this migration?

**Comment by ordian** [comment]
> and I suppose we want to apply runtime 9090 for polkadot before 9100. (kusama already have 9090)

if polkadot runtime will be upgraded straight to 9100 bypassing 9090, then we need this migration, but I don't know what's the plan here

**Comment by gavofyork** [comment]
Maybe @rrtti can chime in on expected rollout of 9090 to Polkadot.

**Comment by rrtti** [comment]
@gavofyork @thiolliere motion is scheduled for today, if/after the motion is approved by council, it is expected for the community to vote until Monday 06.08. Same day enactment.

**Comment by thiolliere** [comment]
So I kept polkadot runtime migration for now. So that the migration of the polkadot runtime on master is still consistent with what is on chain.
Once in I'll update polkadot runtime migration.

**Comment by thiolliere** [comment]
the migration `MigratePalletVersionToStorageVersion` can run multiple time as far as I can tell, as long as we don't use the storage version (because the migration just overwrite the storage version with the latest storage version).

So this PR doesn't need to go before 9.10, however it would be good to have it because it is a useless migration.
For polkadot we can keep the migration in case 9.9 is not applied somehow.

**Comment by thiolliere** [comment]
So polkadot is 9090 this is ready to merge

**Comment by thiolliere** [comment]
bot merge

**Comment by JoshOrndorff** [comment]
For future code historians: The migrations that this PR removes were originally added in #3459

**Pull request merged**
