### PR TITLE
Remove unused files

### PR DESCRIPTION
**Pull request by kianenigma**

### CODE REVIEW

**Comment by kianenigma** [comment]
unless if that `runtime/common/src/claims.scale` is serving some purpose?

**Comment by shawntabrizi** [comment]
It was being used in the migration of accounts.

We should also remove migration code here.

**Comment by bkchr** [comment]
The migration code was already removed.

**Comment by bkchr** [comment]
https://github.com/paritytech/polkadot/commit/e19d50b8f6dc907cbcc322230f845961defda730#diff-6713ee0e82ee03f026aa21e5e99fb055L144

**Pull request merged**
