### PR TITLE
[DON'T MERGE] paritydb testing.

### PR DESCRIPTION
**Pull request by cheme**
This PR is not to be merged, I just want to run zombinet with paritydb backend, before asking for more real condition testing.

### CODE REVIEW

**Comment by shawntabrizi** [comment]
Were there any results from this testing?

**Comment by cheme** [comment]
Mostly I did not know how the ci work and retry a lot, until I understood (if upload jobs are canceled there is no use relaunching the zombienet tests).
Running correctly the ci, then the zombienet tests did pass (got one case with timeout though, but cannot reproduce).

This is related to what a user experiences when running paritydb after a resynch (mpsc filling, unresponsivness).
I did observe some big peek of cpu usage by testing locally but both rocksdb and paritydb.
So at this point I am waiting to see how things go with devops switching westend then kusama validators to paritydb.

**Comment by cheme** [comment]
Actually the peaks I observed on rocksdb are shorter and less impacting.
cc @PierreBesson there is probably something wrong with paritydb on 0.9.18, I think it is still important to roll out validator in westend (so we can observe it at least).
(probably related to the way we delete prefix, but I need to test a bit more to confirm)

**Comment by cheme** [comment]
Nevermind the peaks are from background synch (without warp synch I don't have them).
Still got my node parachain subsystem ending without alert when testing after 1h20 running (chain continue to synch but no more logging from av-store and parachain-selection at least).

**Pull request closed without merging**
