### PR TITLE
Fix XCM bench for new substrate refs

### PR DESCRIPTION
**Pull request by acatangiu**

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2344373

**Comment by acatangiu** [comment]
@muharem @ggwpez @bkchr Polkadot companion https://github.com/paritytech/polkadot/pull/6598 for https://github.com/paritytech/substrate/pull/13146 passed CI and was merged successfully, but now all new CI jobs are failing because of it.

I can't figure out why exactly though.. test is complaining `try_successful_origin` not implemented in `xcm/xcm-builder/src/origin_conversion.rs:247`, but I see it actually is.

Both the trait fn definition and said impl are guarded by same `#[cfg(feature = "runtime-benchmarks")]` so that doesn't seem to be the issue either (unless we somehow compile `xcm-builder` **without** `feature = "runtime-benchmarks"` but compile `frame-support` (trait definition) **with** `feature = "runtime-benchmarks"` ???)

Any ideas?

**Comment by ggwpez** [comment]
Which CI is failing @acatangiu ? Link please

**Comment by acatangiu** [comment]
Failing test: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2344373 (same test fails on all PRs)

**Review by bkontur — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2344758

**Comment by acatangiu** [comment]
Still same test failing (https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2344758) on compiling `xcm-builder` (error impl trait at `xcm/xcm-builder/src/origin_conversion.rs:247`)

**Review by lexnv — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
Looks like this is now blocked by https://github.com/paritytech/polkadot/pull/6528 on the cumulus check.  
Probably have to ignore it.

**Comment by ggwpez** [comment]
@muharem now one of the referenda benches fails.

**Comment by acatangiu** [comment]
> Looks like this is now blocked by #6528 on the cumulus check. Probably have to ignore it.
> 
> Or maybe you can revert your Cargo update.

Also weird because the used substrate reference is one before needing #6528

**Comment by acatangiu** [comment]
I'm traveling rn so have limited availability. Feel free to change substrate refs if needed to get this to pass, the point is to unblock CI for all PRs

**Comment by ggwpez** [comment]
I cannot update substrate here as it says `beefy-merkle-tree`, so well have to merge red and then fix it in https://github.com/paritytech/polkadot/pull/6528

**Comment by acatangiu** [comment]
I had just pulled all of these in https://github.com/paritytech/polkadot/pull/6528, but it works either way.

Thanks @ggwpez !

**Pull request merged**
