### PR TITLE
Companion: restructure macro related exports

### PR DESCRIPTION
**Pull request by juangirini**
Restructure `frame_benchmarking` and `frame_support` macro related exports

Companion for https://github.com/paritytech/substrate/pull/14745

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]
Lets merge this ahead of the upstream Substrate MR.

**Comment by juangirini** [comment]
bot rebase

**Comment by juangirini** [comment]
bot fmt

**Review by kpp — APPROVED** [review]

**Review by liamaharon — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by juangirini** [comment]
bot rebaes

**Comment by juangirini** [comment]
bot rebase

**Review by ordian — APPROVED** [review]

**Comment by juangirini** [comment]
bot rebase

**Comment by juangirini** [comment]
bot merge

**Pull request merged**
