### PR TITLE
Polkadot: add Council to SpendOrigin

### PR DESCRIPTION
**Pull request by muharem**
The bounties are supposed to be approved by Council. But this was broken when new `SpendOrigin`, defined as `Root`, was introduced https://github.com/paritytech/substrate/pull/12808, and replaced the `ApproveOrigin`.

In the PR we extending the `SpendOrigin` with 3/5 of Council.

Note: `SpendOrigin` is shared type between `treasury` and `bounties` pallets, and used to guard, `treasury.spend`, `bounties. approve_bounty`, and `bounties. propose_curator` calls.

### CODE REVIEW

**Review by joepetrowski — APPROVED** [review]
It works to get Bounties functioning again, but the introduction of OpenGov #6701 we should remove Council.

**Comment by muharem** [comment]
> It works to get Bounties functioning again, but the introduction of OpenGov #6701 we should remove Council.

yes, with OpenGov, its going to be only `TreasurySpender` https://github.com/paritytech/polkadot/pull/6701/files#diff-e5e76e02c0d16e79c70b024cbe3c6ea56f3249382a0f987ba203c34fcb40ed66R677

but probably, this we can get with the next release.

**Review by sam0x17 — APPROVED** [review]
looks good to me!

**Review by bkchr — APPROVED** [review]

**Review by ordian — APPROVED** [review]

**Comment by muharem** [comment]
bot merge

**Pull request merged**
