### PR TITLE
cargo +nightly fmt

### PR DESCRIPTION
**Pull request by shawntabrizi**
follow up to https://github.com/paritytech/polkadot/pull/3491

### CODE REVIEW

**Review by kianenigma — APPROVED** [review]

**Comment by ordian** [comment]
I think we should add a CI check here as well as was done in https://github.com/paritytech/substrate/pull/9394.

**Comment by ordian** [comment]
Also the weights autogeneration needs to account for that as well as https://github.com/paritytech/polkadot/pull/3421#discussion_r669033485.

**Comment by shawntabrizi** [comment]
> Also the weights autogeneration needs to account for that as well as [#3421 (comment)](https://github.com/paritytech/polkadot/pull/3421#discussion_r669033485).

Something for the backlog.

**Review by ordian — APPROVED** [review]

**Review by pepyakin — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Comment by shawntabrizi** [comment]
bot merge

**Review by HCastano — APPROVED** [review]
❤️ ❤️ ❤️

**Comment by HCastano** [comment]
On second though, before you merge this can you add this config option:

```
ignore = [
    "bridges",
]
```

The bridges repo doesn't use the same `rustfmt` options and it'll create some unnecessary noise when updating.

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
