### PR TITLE
Revert orchestra update

### LINKED ISSUE #6912: dispute-coordinator: subsystem stalls during dispute load test
https://grafana.parity-mgmt.parity.io/goto/6WbF6r-4k?orgId=1

This seems to be happening since https://github.com/paritytech/polkadot/pull/6854 . Once I removed this change I got no more stalls. 

I suspect this was introduced by https://github.com/paritytech/orchestra/pull/36 or other changes in metered channel.

CC @vstakhov

### PR DESCRIPTION
**Pull request by vstakhov**
Reverts paritytech/polkadot#6854

Fixes #6912

Cumulus companion: https://github.com/paritytech/cumulus/pull/2349

### CODE REVIEW

**Comment by vstakhov** [comment]
bot merge

**Comment by ordian** [comment]
@vstakhov please merge PRs with companions with `bot`. Currently, we have a hanging unmerged companion which will block other PRs: https://github.com/paritytech/cumulus/pull/2349. This is a problem, because there's another unmerged companion: https://github.com/paritytech/cumulus/pull/2334

**Comment by ggwpez** [comment]
I guess in this case the Currency MR should go green since it is not rebased on this one.

**Comment by vstakhov** [comment]
> @vstakhov please merge PRs with companions with `bot`. Currently, we have a hanging unmerged companion which will block other PRs: [paritytech/cumulus#2349](https://github.com/paritytech/cumulus/pull/2349).

Got it, thank you! I was under impression that bot merge is required merely from a dependent PR side (cumulus in this case).

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-41-v0-9-42/2828/1

**Pull request merged**
