### PR TITLE
Enable Babe RPC for getting epoch authorship

### PR DESCRIPTION
**Pull request by octol**
Enable `babe_epochAuthorship` that was added in https://github.com/paritytech/substrate/pull/4729, which returns all the slots that can be claimed in the current epoch.

### CODE REVIEW

**Comment by octol** [comment]
When testing this locally I noticed that the substrate code it calls can take some time to complete. Almost 7sec locally in release mode (and probably about 5x that in debug)

**Comment by andresilva** [comment]
@octol On what network did you try it? Kusama? That's a bit worrying if we end up blocking the authorship task for so long. This information can (and should be) cached though, it only goes stale once a new epoch starts.

**Comment by octol** [comment]
Let's mark this as in progress until I've investigated this performance aspect further

**Comment by octol** [comment]
Raised the issue https://github.com/paritytech/substrate/issues/5948 to resolve the performance bottleneck before we merge this

**Comment by octol** [comment]
With https://github.com/paritytech/substrate/issues/5948 merged getting epoch authorship is now significantly faster, just under 300 ms on a local dev chain on my machine

**Comment by gavofyork** [comment]
@andresilva any reservations here or shall i merge?

**Pull request merged**
