### PR TITLE
` XcmContext` to `buy_weight / refund_weight`

### PR DESCRIPTION
**Pull request by bkontur**
As a part of https://github.com/paritytech/cumulus/pull/2601#issuecomment-1561346944

Cumulus companion: https://github.com/paritytech/cumulus/pull/2956

### CODE REVIEW

**Review by muharem — APPROVED** [review]

**Review by PatricioNapoli — APPROVED** [review]

**Review by KiChjang — APPROVED** [review]

**Review by vstam1 — APPROVED** [review]

**Comment by bkontur** [comment]
bot rebase

**Review by gilescope — APPROVED** [review]

**Review by franciscoaguirre — APPROVED** [review]

**Review by sergejparity — APPROVED** [review]

**Comment by bkontur** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3305930

**Comment by bkontur** [comment]
bot merge

**Pull request merged**
