### PR TITLE
[Don't merge] Log authority key if node is a validator to telemetry

### PR DESCRIPTION
**Pull request by maciejhirsz**

### CODE REVIEW

**Comment by maciejhirsz** [comment]
Just noticed this doesn't work when the node is reconnecting.

**Comment by arkpar** [comment]
Eventually this needs to be in the substrate

**Comment by maciejhirsz** [comment]
@arkpar can it be in substrate? If I move it that will actually make it much easier, since Substrate already has a closure that gets called on all reconnects: https://github.com/paritytech/substrate/blob/2f593df12d4225d9a5fbf1675407de5866469d6b/substrate/service/src/lib.rs#L250

I've put in here since the role (whether the node is a validator or not) is Polkadot business logic, or is that a bad assumption?

**Comment by arkpar** [comment]
Substrate has a notion of authority so I think it would be fine. I'd also move key selection logic (https://github.com/paritytech/polkadot/pull/13/files#diff-32562a9cc266a6c93662b535a7803970R224) into substrate service function as well.

**Comment by maciejhirsz** [comment]
Closing in favor of https://github.com/paritytech/substrate/pull/702

**Pull request closed without merging**
