### PR TITLE
Switch to the master branch of libp2p

### LINKED ISSUE #376: varint: duplicate source
I have build troubles of `polkadot v0.2` via `cargo-vendor` because some packages have duplicate sources:

```
  found duplicate version of package `varint v0.1.0` vendored from two sources:                                                        

        source 1: https://github.com/libp2p/rust-libp2p#857c6653
        source 2: https://github.com/tomaka/libp2p-rs?rev=727e0e099b53a4032a7e2330994c819fe866add7#727e0e09                            
```

### PR DESCRIPTION
**Pull request by tomaka**
Fixes #376 as a side-effect.

Use the "master" branch of libp2p.
This is in fact not the master branch, but the branch `polkadot-2` of my fork, which contains master and all the important open PRs merged.

Do not merge yet, as there are some issues with https://github.com/libp2p/rust-libp2p/pull/355

### CODE REVIEW

**Comment by tomaka** [comment]
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build is too long for travis :man_facepalming:

**Comment by arkpar** [comment]
`substrate-network-libp2p` takes too long to compile on my machine as well

**Comment by gavofyork** [comment]
also on my cloud node.

**Comment by tomaka** [comment]
Pushed a commit that reduces to "only" three minutes on my machine.

**Comment by tomaka** [comment]
This PR is now ready. It should fix tons of issues with libp2p, most notably with connections not being dropped properly, and another memory leak.

Once #370 is done, I think the network will be robust.

**Pull request merged**
