### PR TITLE
Make sure adder collator test is executed in CI

### PR DESCRIPTION
**Pull request by bkchr**
…overseer (#1947)"

This reverts commit 355558ae880b6f2d256550f02fc41f680b0f752b.

### CODE REVIEW

**Review by ordian — APPROVED** [review]
Is there a way to accomplish what #1947 was trying to solve?
Namely, not run this test with `cargo test --workspace --release`?

**Comment by bkchr** [comment]
We could change to the directory and run it directly. However this will probably require a huge rebuild and this will increase the already not so small CI time. 

However, I don't expect this feature to last for that long and I added a comment to the test if it is failing to make the user aware that the feature needs to be activated.

**Comment by bkchr** [comment]
And the test is also timing out after 10 minutes.

**Comment by bkchr** [comment]
Okay, CI difference is below 2 minutes. Fine by me, we can keep this for now.

**Pull request merged**
