### PR TITLE
Companion for paritytech/substrate#12219

### PR DESCRIPTION
**Pull request by KiChjang**
Companion for paritytech/substrate#12219

cumulus companion: https://github.com/paritytech/cumulus/pull/1610

### CODE REVIEW

**Review by nitwit69 — APPROVED** [review]
tACK

**Comment by KiChjang** [comment]
bot merge

**Comment by KiChjang** [comment]
bot merge

**Comment by KiChjang** [comment]
bot merge

**Comment by ordian** [comment]
bot merge force

**Pull request merged**
