### PR TITLE
Companion for #14237: Use latest sp-crates

### PR DESCRIPTION
**Pull request by lexnv**
Companion for: https://github.com/paritytech/substrate/pull/14237

This PR is a placeholder for the CI-bot to update the Cargo.lock of substrate.
After the substrate patch is merged, the first commit of this patch will be reverted.

cumulus companion: https://github.com/paritytech/cumulus/pull/2643

// @paritytech/subxt-team

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2902597

**Review by niklasad1 — COMMENTED** [review]
It should be sufficient to just update `Cargo.lock` I think and then the merge bot should take of the rest.

Obviously not super familiar with the merge bot details but the `Cargo.toml's` shouldn't be committed in general.

**Review by niklasad1 — APPROVED** [review]

**Review by jsdw — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2909214

**Comment by niklasad1** [comment]
bot merge

**Pull request merged**
