### PR TITLE
Update Weight for Pallet Staking including Kick

### PR DESCRIPTION
**Pull request by shawntabrizi**
This PR will run the benchmarking bot on the latest changes to Pallet Staking.

Replacing: https://github.com/paritytech/polkadot/pull/2290

### CODE REVIEW

**Review by apopiak — APPROVED** [review]
LGTM, read/write counts for `kick` were checked in the introducing PR, right?

**Comment by shawntabrizi** [comment]
@apopiak yes, you can confirm that if you like here: https://github.com/paritytech/substrate/pull/7930

**Comment by shawntabrizi** [comment]
bot merge

**Review by gavofyork — APPROVED** [review]

**Comment by gavofyork** [comment]
bot merge

**Pull request merged**
