### PR TITLE
[ci] Run check-runtime only for PRs

### PR DESCRIPTION
**Pull request by alvicsam**
Close https://github.com/paritytech/ci_cd/issues/538

### CODE REVIEW

**Review by sergejparity — APPROVED** [review]

**Review by radupopa2010 — APPROVED** [review]

**Review by chevdor — APPROVED** [review]

**Comment by ordian** [comment]
> Run check-runtime only for PRs 

The issue is about running it only for (PRs to) release branches.

**Comment by alvicsam** [comment]
> The issue is about running it only for (PRs to) release branches

Good catch, thank you. I added rule `release-v*` and keep rule for PR because we can't distinguish difference between PR into master or into other branch in gitlab

**Comment by ordian** [comment]
> > The issue is about running it only for (PRs to) release branches
> 
> Good catch, thank you. I added rule `release-v*` and keep rule for PR because we can't distinguish difference between PR into master or into other branch in gitlab

Can we use something like `CI_MERGE_REQUEST_TARGET_BRANCH_NAME`? The purpose of the issue is to remove this check for PRs into master (on github) and currently this PR doesn't do it.

**Comment by alvicsam** [comment]
Hm, the issue has this text:

> It would be good to keep this check but remove it from master and ensure it runs in the release branches

The PR removes the `check-runtime` from master and runs it on release branches.

@ordian you mentioned that it also should run in PRs to release branches. We mirror Github branches to Gitlab with custom solution and all PRs are mirrored as branches with PR number. So currently there is no way to run the `check-runtime` job only for PRs into release branches. I can either disable it for PRs at all or keep for all PRs.

**Comment by ordian** [comment]
Well, if we can't distinguish between PRs to master or a release branch, not sure if this check is useful at all. IIRC, it was introduced so that we bump the spec version when needed, but only when needed on master. But now we have a release process that bumps the version on every release. So what value does this check bring? Maybe we should remove it? @bkchr

**Comment by bkchr** [comment]
> Maybe we should remove it?

From my side we can remove it. I mean there should be no need anymore

**Comment by alvicsam** [comment]
@chevdor wdyt? do you need it for `release-v*` branches?

**Review by coderobe — APPROVED** [review]

**Comment by chevdor** [comment]
> @chevdor wdyt? do you need it for `release-v*` branches?

any release branch yes

**Pull request merged**
