### PR TITLE
Remove parachain/-thread distinction in host config

### PR DESCRIPTION
**Pull request by alexgparity**

### CODE REVIEW

**Review by sandreim — COMMENTED** [review]
Shouldn't this PR be targeting `master` as it looks it doesn't really touch the work done for on-demand parachains? Any concerns ?

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2861303

**Comment by alexgparity** [comment]
> Shouldn't this PR be targeting `master` as it looks it doesn't really touch the work done for on-demand parachains? Any concerns ?

Good point. Though, it is part of the work for unifying on-demand and non-on-demand parachains which is part of the on-demand parachains work. So maybe it shouldn't target `master`?

**Comment by sandreim** [comment]
It would be one extra migration to worry about later when we want to merge the on-demand parachains work into `master` and also make this distinction go away sooner rather than later which is a good thing to do.

**Comment by alexgparity** [comment]
> It would be one extra migration less to worry about later when we want to merge the on-demand parachains work into `master` and also make this distinction go away sooner rather than later which is a good thing to do.

Will target `master` with a new PR once the errors are fixed.

**Comment by alexgparity** [comment]
Closed in favour of https://github.com/paritytech/polkadot/pull/7265

**Pull request closed without merging**
