### PR TITLE
[DNM] benchmark paras_inherent w/o disputes

### PR DESCRIPTION
**Pull request by tdimitrov**

### CODE REVIEW

**Comment by tdimitrov** [comment]
bot bench $ runtime kusama runtime_parachains::paras_inherent

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2543982

**Comment by tdimitrov** [comment]
bot bench $ runtime rococo runtime_parachains::paras_inherent

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2544532

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2545037

**Comment by tdimitrov** [comment]
bot bench $ runtime polkadot runtime_parachains::paras_inherent

**Comment by tdimitrov** [comment]
bot bench $ runtime polkadot runtime_parachains::paras_inherent

**Comment by tdimitrov** [comment]
bot bench $ runtime rococo runtime_parachains::paras_inherent

**Pull request closed without merging**
