### PR TITLE
Add `force_open_hrmp_channel` Call

### PR DESCRIPTION
**Pull request by joepetrowski**
Open an HRMP channel using the Root origin. This will avoid the nested messages referenda needed to establish channels with common good chains.

Supersedes https://github.com/paritytech/polkadot/pull/4998
Closes https://github.com/paritytech/polkadot/issues/4648

### CODE REVIEW

**Comment by joepetrowski** [comment]
/cmd queue -c bench-bot $ pallet westend-dev polkadot-runtime-parachains::hrmp

**Comment by ggwpez** [comment]
/cmd queue -c bench-bot $ pallet westend-dev runtime_parachains::hrmp
/cmd queue -c bench-bot $ pallet kusama-dev runtime_parachains::hrmp

**Comment by ggwpez** [comment]
/cmd queue -c bench-bot $ runtime westend-dev runtime_parachains::hrmp

**Review by ggwpez — APPROVED** [review]

**Review by muharem — APPROVED** [review]

**Review by ordian — APPROVED** [review]

**Review by gavofyork — APPROVED** [review]

**Comment by joepetrowski** [comment]
bot merge

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis/1026/2

**Pull request merged**
