### PR TITLE
avoid creating duplicate unbacked spans when we see extra statements

### PR DESCRIPTION
**Pull request by rphmeier**
Receiving a `CandidateBackingMessage::Second` or seeing a `Statement::Seconded` after we'd already seen requisite votes for backing led us to create extra unbacked spans that were never cleaned up. 

image

### CODE REVIEW

**Comment by rphmeier** [comment]
honestly, this is related to a larger bug in candidate backing (hooray) where we validate the candidate a second time as well.

**Comment by rphmeier** [comment]
will merge this so we can redeploy; touches no actual logic, just logging

**Comment by burdges** [comment]
I suppose a signature that seconds already references who proposed?

**Comment by rphmeier** [comment]
@burdges the receipt contains the collator address and signature

**Comment by coriolinus** [comment]
@rphmeier Just following up on

> this is related to a larger bug in candidate backing

Does that larger bug have its own issue? If so, I can't seem to find it: the most recent issue created which contains the phrase "candidate backing" seems to have been from 10 days before this PR.

**Comment by rphmeier** [comment]
@coriolinus I didn't file one, no, but please go ahead if you like. It's not a terrible bug since the sanity checks before statement issuance will protect us from issuing conflicting statements. Just wasted a little bit of CPU

**Pull request merged**
